// This file is licensed under the Elastic License 2.0. Copyright 2021-present, StarRocks Inc.

#pragma once

#include "exec/pipeline/scan/chunk_source.h"
#include "exec/pipeline/scan/morsel.h"
#include "exec/pipeline/scan/olap_scan_context.h"
namespace starrocks::pipeline {
// EOSChunkSource is an ChunkSource created from EOSMorsel, it only returns an EOS chunk when invoking
// _read_chunk method.
// When an original ScanMorsel is split into several SplitMorsels, we can not know the exact number of
// SplitMorsels that would be generated beforehand, because morsel splitting adopts splitting the morsel one-by-one
// on command style instead all-at-once style. so we add EOSMorsel as the last SplitMorsel of the original
// ScanMorsel as an indicator of the current ScanMorsel is done.
// For an example:
// ScanMorsel A will generate SplitMorsels a0, a1, a2 sequentially, now we add an EOSMorsel e, so we get
// four SplitMorsels a0, a1, a2, e. each Morsel can generate a EOS chunk, so we know when we count the number of EOS
// Chunks to four in the ScanOperator::pull_chunk, then we have received all of the Chunks generated by the
// original ScanMorsel, we can emit only one EOS chunk safely for this ScanMorsel, the first three EOS chunks
// are ignored because the ScanMorsel is not processed completely.

class EOSChunkSource : public ChunkSource {
public:
    EOSChunkSource(int32_t scan_operator_id, RuntimeProfile* runtime_profile, MorselPtr&& morsel,
                   vectorized::OlapScanNode* scan_node, OlapScanContext* scan_ct)
            : ChunkSource(scan_operator_id, runtime_profile, std::move(morsel), scan_ct->get_chunk_buffer()) {}
    ~EOSChunkSource() override = default;
    Status prepare(starrocks::RuntimeState* state) override { return Status::OK(); }
    void close(starrocks::RuntimeState* state) override {}

protected:
    Status _read_chunk(RuntimeState* state, vectorized::ChunkPtr* chunk) override;
    const workgroup::WorkGroupScanSchedEntity* _scan_sched_entity(const workgroup::WorkGroup* wg) const override;
};
} // namespace starrocks::pipeline