// Copyright 2021-present StarRocks, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.starrocks.sql.analyzer.mv;

/**
 * Describes who is responsible for producing the value of the {@code __ROW_ID__} column
 * for an incremental materialized view.
 *
 * <p>The analyzer decides the strategy while rewriting the MV's query definition.
 * Downstream code (schema generation, refresh SQL generation) dispatches on this value.
 *
 * <p>Future extensions (e.g. encoding a source primary key for a non-aggregate MV over
 * a retractable source, or encoding join keys for a join-based MV) are internal to
 * {@link #QUERY_COMPUTED}: they are new rewrite rules that inject an appropriate
 * expression, but they do not require new enum values. This enum is designed to stay
 * stable across such extensions.
 */
public enum RowIdStrategy {

    /**
     * The query itself computes {@code __ROW_ID__} as an expression in its output.
     * Examples:
     * <ul>
     *   <li>Aggregate MV: {@code encode(group_by_keys)}</li>
     *   <li>Future — non-aggregate MV over a retractable source: {@code encode(source_pk)}</li>
     *   <li>Future — join-based MV: {@code encode(join_keys)}</li>
     * </ul>
     * MV schema: {@code __ROW_ID__} is a regular primary-key column (e.g. VARCHAR),
     * not AUTO_INCREMENT.
     */
    QUERY_COMPUTED,

    /**
     * {@code __ROW_ID__} is auto-generated by the storage engine at insert time.
     * Only valid for append-only sources — a storage-generated id cannot be reused to
     * propagate DELETE/UPDATE events back to the MV row.
     * MV schema: {@code __ROW_ID__} is {@code BIGINT AUTO_INCREMENT}.
     */
    AUTO_INCREMENT
}
