// Copyright 2021-present StarRocks, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.starrocks.lake;

import com.google.common.base.Preconditions;
import com.starrocks.alter.AlterJobV2Builder;
import com.starrocks.alter.LakeTableAlterJobV2Builder;
import com.starrocks.catalog.Database;
import com.starrocks.catalog.OlapTable;
import com.starrocks.common.Config;
import com.starrocks.server.GlobalStateMgr;
import com.starrocks.server.RunMode;
import com.starrocks.transaction.TransactionState;

import java.util.List;

public class LakeTableHelper {
    static boolean deleteTable(long dbId, OlapTable table, boolean replay) {
        Preconditions.checkState(table.isCloudNativeTableOrMaterializedView());
        table.removeTableBinds(replay);
        // LakeTable's data cleaning operation is a time-consuming operation that may need to be repeated
        // many times before it succeeds, so we chose to let the recycle bin perform this work for two purposes:
        // 1. to avoid blocking the user's session for too long
        // 2. to utilize the recycle bin's delete retry capability to perform retries.
        GlobalStateMgr.getCurrentState().getRecycleBin().recycleTable(dbId, table, false);
        return true;
    }

    static boolean deleteTableFromRecycleBin(long dbId, OlapTable table, boolean replay) {
        Preconditions.checkState(table.isCloudNativeTableOrMaterializedView());
        table.removeTableBinds(replay);
        if (replay) {
            table.removeTabletsFromInvertedIndex();
            return true;
        }
        LakeTableCleaner cleaner = new LakeTableCleaner(table);
        boolean succ = cleaner.cleanTable();
        if (succ) {
            table.removeTabletsFromInvertedIndex();
        }
        return succ;
    }


    static AlterJobV2Builder alterTable(OlapTable table) {
        Preconditions.checkState(table.isCloudNativeTableOrMaterializedView());
        return new LakeTableAlterJobV2Builder(table);
    }

    public static boolean supportCombinedTxnLog(long dbId, List<Long> tableIdList,
                                                TransactionState.LoadJobSourceType sourceType) {
        if (!RunMode.isSharedDataMode() || !Config.lake_use_combined_txn_log) {
            return false;
        }
        // For the time being, we only support combined txn logs for stream loads and route loads,
        // because currently the combined log is generated by the OlapTableSink operator.
        // To ensure that the combined txn log is complete and unique, there can only be one OlapTableSink
        // operator to write the combined txn log, and currently only stream load and route load can
        // guarantee that there will only be one OlapTableSink operator.
        // TODO: Support writing combined txn logs when there are multiple OlapTableSink operators.
        if (!(sourceType == TransactionState.LoadJobSourceType.BACKEND_STREAMING ||
                sourceType == TransactionState.LoadJobSourceType.ROUTINE_LOAD_TASK)) {
            return false;
        }
        Database db = GlobalStateMgr.getCurrentState().getLocalMetastore().getDb(dbId);
        if (db == null) {
            return false;
        }
        for (Long tableId : tableIdList) {
            LakeTable table = (LakeTable) db.getTable(tableId);
            if (table == null || table.getState() != OlapTable.OlapTableState.NORMAL) {
                return false;
            }
        }
        return true;
    }
}
