// Copyright 2021-present StarRocks, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package com.starrocks.encryption;

import com.starrocks.proto.EncryptionAlgorithmPB;
import com.starrocks.proto.EncryptionKeyPB;
import com.starrocks.proto.EncryptionKeyTypePB;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * KMS data key, generated by KmsKey, only persist encrypted key
 */
public class KmsDataKey extends EncryptionKey {
    private static final Logger LOG = LoggerFactory.getLogger(KmsDataKey.class);

    private EncryptionAlgorithmPB algorithm;
    private byte[] plainKey;
    private String encryptedKey;

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof KmsDataKey)) {
            return false;
        }
        return encryptedKey.equalsIgnoreCase(((KmsDataKey) obj).encryptedKey);
    }

    @Override
    public String toSpec() {
        return String.format("kms-data:%s:%s", algorithm.toString().toLowerCase(), encryptedKey);
    }

    public KmsDataKey() {
    }

    public KmsDataKey(EncryptionAlgorithmPB algorithm, String encryptedKey) {
        this.algorithm = algorithm;
        this.encryptedKey = encryptedKey;
    }

    public void setPlainKey(byte[] plainKey) {
        this.plainKey = plainKey;
    }

    public byte[] getPlainKey() {
        return plainKey;
    }

    public String getEncryptedKey() {
        return encryptedKey;
    }

    @Override
    public void toPB(EncryptionKeyPB pb, KeyMgr mgr) {
        super.toPB(pb, mgr);
        pb.type = EncryptionKeyTypePB.KMS_DATA_KEY;
        pb.algorithm = algorithm;
        pb.keyDesc = encryptedKey;
    }

    @Override
    public void fromPB(EncryptionKeyPB pb, KeyMgr mgr) {
        super.fromPB(pb, mgr);
        this.algorithm = pb.algorithm;
        this.encryptedKey = pb.keyDesc;
    }

    @Override
    public EncryptionKey generateKey() {
        getPlainKeyIfNecessary();
        NormalKey ret = NormalKey.createRandom(this.algorithm);
        ret.setEncryptedKey(EncryptionUtil.wrapKey(plainKey, this.algorithm, ret.getPlainKey()));
        ret.setParent(this);
        return ret;
    }

    @Override
    public void decryptKey(EncryptionKey key) {
        getPlainKeyIfNecessary();
        if (!(key instanceof NormalKey)) {
            throw new IllegalArgumentException("KmsDataKey cannot not decrypt " + key.getClass().getName());
        }
        NormalKey normalKey = (NormalKey) key;
        normalKey.setPlainKey(EncryptionUtil.unwrapKey(plainKey, algorithm, normalKey.getEncryptedKey()));
    }

    @Override
    public String toString() {
        return String.format("KmsDataKey(id:%d createTime:%d encryptedKey:%s)", id, createTime, encryptedKey);
    }

    private synchronized void getPlainKeyIfNecessary() {
        if (plainKey == null) {
            assert this.parent instanceof KmsKey;
            parent.decryptKey(this);
        }
    }
}
