pull_request_rules:
  - name: assign PRs with the pr author
    conditions:
      - -merged
      
    actions:
      assign:
        add_users: 
          - "{{author}}"

  - name: close pr when conflict
    conditions:
      - label=conflicts
    actions:
      close:
        message:
          "@{{author}}: Backport conflict, please reslove the conflict and resubmit the pr"
