<<<<<<< HEAD

commands_restrictions:
  backport:
    conditions:
      - sender-permission>=read
  rebase:
    conditions:
      - sender-permission>=read
=======
commands_restrictions:
  backport:
    conditions:
      - or:
        - sender-permission>=read
        - sender=github-actions[bot]

  rebase:
    conditions:
      - or:
        - sender-permission>=read
        - sender=github-actions[bot]
>>>>>>> edd5009ce6 ([Doc] Revise Backup Restore according to feedback (#53738))

pull_request_rules:
  - name: assign PRs with the pr author
    conditions:
      - -merged
    actions:
      assign:
        add_users: 
          - "{{author}}"

<<<<<<< HEAD
  - name: assign backport PRs with the pr author
    conditions:
      - merged
    actions:
      backport:
        bot_account: "{{author}}"
        assignees: 
          - "{{author}}"
  
=======
>>>>>>> edd5009ce6 ([Doc] Revise Backup Restore according to feedback (#53738))
  - name: close pr when conflict
    conditions:
      - label=conflicts
    actions:
      close:
        message:
          "@{{author}}: Backport conflict, please reslove the conflict and resubmit the pr"
