#!/usr/bin/env python3

# Copyright 2021-present StarRocks, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
BE_ROOT = REPO_ROOT / "be"
COMMON_CONFIG = BE_ROOT / "src/common/config.h"
DEFAULT_MANIFEST = BE_ROOT / "src/common/config_fwd_headers_manifest.json"

LOCAL_CONFIG_INCLUDE_RE = re.compile(r'^\s*#include\s+"(config_[^"]+\.h)"\s*$')
NAMESPACE_OPEN_RE = re.compile(r'^\s*namespace\s+starrocks::config\s*\{\s*$')
NAMESPACE_CLOSE_RE = re.compile(r'^\s*}\s*//\s*namespace\s+starrocks::config\s*$')
CONDITIONAL_OPEN_RE = re.compile(r'^\s*#\s*(if|ifdef|ifndef)\b')
CONDITIONAL_BRANCH_RE = re.compile(r'^\s*#\s*(elif|else)\b')
CONDITIONAL_CLOSE_RE = re.compile(r'^\s*#\s*endif\b')
CONF_NAME_RE = re.compile(r'^\s*CONF_[A-Za-z0-9_]+\(\s*([A-Za-z0-9_]+)\s*,', re.DOTALL)
CONF_ALIAS_RE = re.compile(
    r'^\s*CONF_Alias\(\s*([A-Za-z0-9_]+)\s*,\s*([A-Za-z0-9_]+)\s*\)\s*;',
    re.DOTALL,
)

HEADER_PREAMBLE = """// Copyright 2021-present StarRocks, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is generated by build-support/gen_config_fwd_headers.py from
// be/src/common/config.h. Do not edit manually.

#pragma once

#include "common/configbase.h"

namespace starrocks::config {
"""

HEADER_POSTAMBLE = """
} // namespace starrocks::config
"""


@dataclass(frozen=True)
class ConfigBlock:
    names: tuple[str, ...]
    text: str
    guards: tuple["GuardFrame", ...] = ()


@dataclass(frozen=True)
class GuardFrame:
    group_id: str
    branch_lines: tuple[str, ...]
    branch_index: int


@dataclass
class ActiveGuard:
    group_id: str
    branch_lines: list[str]
    branch_index: int = 0


def _trim_comment_block(lines: list[str]) -> list[str]:
    start = 0
    end = len(lines)
    while start < end and lines[start].strip() == "":
        start += 1
    while end > start and lines[end - 1].strip() == "":
        end -= 1
    return lines[start:end]


def _collect_local_config_includes(path: Path) -> list[Path]:
    includes: list[Path] = []
    for line in path.read_text().splitlines():
        match = LOCAL_CONFIG_INCLUDE_RE.match(line)
        if not match:
            continue
        include = match.group(1)
        if include.endswith("_fwd.h"):
            continue
        includes.append(path.parent / include)
    return includes


def _extract_config_blocks(path: Path) -> list[ConfigBlock]:
    lines = path.read_text().splitlines(keepends=True)
    in_namespace = False
    pending: list[str] = []
    blocks: list[ConfigBlock] = []
    guard_stack: list[ActiveGuard] = []
    next_guard_id = 0
    index = 0

    while index < len(lines):
        line = lines[index]
        stripped = line.strip()

        if not in_namespace:
            if NAMESPACE_OPEN_RE.match(line):
                in_namespace = True
            index += 1
            continue

        if NAMESPACE_CLOSE_RE.match(line):
            break

        if stripped == "":
            if pending:
                pending.append(line)
            index += 1
            continue

        if stripped.startswith("//"):
            pending.append(line)
            index += 1
            continue

        if stripped.startswith("/*"):
            pending.append(line)
            index += 1
            while index < len(lines):
                pending.append(lines[index])
                if "*/" in lines[index]:
                    index += 1
                    break
                index += 1
            continue

        if CONDITIONAL_OPEN_RE.match(line):
            pending = []
            guard_stack.append(
                ActiveGuard(group_id=f"{path}:{next_guard_id}", branch_lines=[line], branch_index=0)
            )
            next_guard_id += 1
            index += 1
            continue

        if CONDITIONAL_BRANCH_RE.match(line):
            pending = []
            if not guard_stack:
                raise ValueError(f"unexpected conditional branch directive in {path}: {line.rstrip()}")
            guard_stack[-1].branch_lines.append(line)
            guard_stack[-1].branch_index = len(guard_stack[-1].branch_lines) - 1
            index += 1
            continue

        if CONDITIONAL_CLOSE_RE.match(line):
            pending = []
            if not guard_stack:
                raise ValueError(f"unexpected #endif in {path}: {line.rstrip()}")
            guard_stack.pop()
            index += 1
            continue

        if stripped.startswith("CONF_"):
            macro_lines = [line]
            while not re.search(r'\)\s*;\s*(//.*)?$', macro_lines[-1]):
                index += 1
                if index >= len(lines):
                    raise ValueError(f"unterminated config macro in {path}")
                macro_lines.append(lines[index])

            macro_text = "".join(macro_lines)
            alias_match = CONF_ALIAS_RE.match(macro_text)
            if alias_match:
                names = (alias_match.group(1), alias_match.group(2))
            else:
                name_match = CONF_NAME_RE.match(macro_text)
                if not name_match:
                    raise ValueError(f"unable to parse config name from {path}: {macro_text!r}")
                names = (name_match.group(1),)

            block_lines = _trim_comment_block(pending)
            text = "".join(block_lines + macro_lines)
            if not text.endswith("\n"):
                text += "\n"
            blocks.append(
                ConfigBlock(
                    names=names,
                    text=text,
                    guards=tuple(
                        GuardFrame(
                            group_id=guard.group_id,
                            branch_lines=tuple(guard.branch_lines),
                            branch_index=guard.branch_index,
                        )
                        for guard in guard_stack
                    ),
                )
            )
            pending = []
            index += 1
            continue

        pending = []
        index += 1

    if guard_stack:
        raise ValueError(f"unterminated conditional block in {path}")

    return blocks


def collect_config_blocks(path: Path, visiting: set[Path] | None = None) -> list[ConfigBlock]:
    if visiting is None:
        visiting = set()
    if path in visiting:
        raise ValueError(f"detected recursive config include: {path}")
    visiting.add(path)
    blocks: list[ConfigBlock] = []
    for include in _collect_local_config_includes(path):
        blocks.extend(collect_config_blocks(include, visiting))
    blocks.extend(_extract_config_blocks(path))
    visiting.remove(path)
    return blocks


def render_header(config_names: list[str], blocks: list[ConfigBlock]) -> str:
    selected = set(config_names)
    rendered: list[str] = []
    found: set[str] = set()
    current_guards: tuple[GuardFrame, ...] = ()

    for block in blocks:
        if selected.intersection(block.names):
            target_guards = block.guards
            shared_prefix = 0
            while shared_prefix < len(current_guards) and shared_prefix < len(target_guards):
                if current_guards[shared_prefix].group_id != target_guards[shared_prefix].group_id:
                    break
                shared_prefix += 1

            segment: list[str] = []

            for _ in range(len(current_guards) - 1, shared_prefix - 1, -1):
                segment.append("#endif\n")

            for index in range(shared_prefix):
                current = current_guards[index]
                target = target_guards[index]
                if target.branch_index < current.branch_index:
                    raise ValueError(
                        "selected config order regressed within conditional block "
                        f"{target.group_id}: {target.branch_index} < {current.branch_index}"
                    )
                segment.extend(target.branch_lines[current.branch_index + 1 : target.branch_index + 1])

            for target in target_guards[shared_prefix:]:
                segment.extend(target.branch_lines)

            segment.append(block.text.rstrip() + "\n")
            rendered.append("".join(segment).rstrip())
            found.update(selected.intersection(block.names))
            current_guards = target_guards

    if current_guards:
        rendered.append("".join("#endif\n" for _ in range(len(current_guards))).rstrip())

    missing = [name for name in config_names if name not in found]
    if missing:
        raise ValueError(f"configs not found in {COMMON_CONFIG}: {', '.join(missing)}")

    body = "\n\n".join(rendered)
    if body:
        body += "\n"
    return HEADER_PREAMBLE + body + HEADER_POSTAMBLE


def load_manifest(path: Path) -> list[dict[str, object]]:
    manifest = json.loads(path.read_text())
    headers = manifest.get("generated_headers")
    if not isinstance(headers, list):
        raise ValueError("manifest missing generated_headers list")
    return headers


def write_header(path: Path, content: str, force: bool) -> bool:
    if not force and path.exists() and path.read_text() == content:
        return False
    path.write_text(content)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate config_<domain>_fwd.h from common/config.h")
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="fail if generated headers are stale")
    mode.add_argument(
            "--force",
            action="store_true",
            help="rewrite generated headers even if the content is unchanged",
    )
    args = parser.parse_args()

    headers = load_manifest(args.manifest)
    blocks = collect_config_blocks(COMMON_CONFIG)
    changed: list[str] = []
    stale: list[str] = []

    for entry in headers:
        path = REPO_ROOT / entry["path"]
        config_names = entry["configs"]
        if not isinstance(config_names, list) or not all(isinstance(name, str) for name in config_names):
            raise ValueError(f"invalid config list for {entry}")
        content = render_header(config_names, blocks)
        if args.check:
            current = path.read_text() if path.exists() else ""
            if current != content:
                stale.append(str(path.relative_to(REPO_ROOT)))
        else:
            if write_header(path, content, args.force):
                changed.append(str(path.relative_to(REPO_ROOT)))

    if args.check:
        if stale:
            print("stale generated config forward headers:", file=sys.stderr)
            for path in stale:
                print(f"  {path}", file=sys.stderr)
            return 1
        print("OK: generated config forward headers are up to date.")
        return 0

    if changed:
        action = "Regenerated" if args.force else "Updated"
        print(f"{action} generated config forward headers:")
        for path in changed:
            print(f"  {path}")
    else:
        print("Generated config forward headers are already up to date. No files were rewritten.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
