// Copyright 2021-present StarRocks, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#include <cstdint>

namespace starrocks {

// The position index of a column in a specific TabletSchema starts from 0.
// The position of the same column in different TabletSchema may be different, which
// means that the same column may have a different ColumnId in different contexts, depending
// on the TabletSchema used.
// TODO: Change the name
using ColumnId = uint32_t;

// A unique identifier for a column within the Tablet scope, unlike ColumnId, ColumnUID
// is independent of where the column appears in the Tablet schema.
// Since versions 3.2.3, ColumnUID are generated by the FE, which uses the Java int
// type, corresponding to the int32_t.
using ColumnUID = int32_t;

} // namespace starrocks
