// Copyright 2021-present StarRocks, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is generated by build-support/gen_config_fwd_headers.py from
// be/src/common/config.h. Do not edit manually.

#pragma once

#include "common/configbase.h"

namespace starrocks::config {
// Row interval between consecutive sort-key samples recorded by the segment
// writer. Samples are consumed by tablet split and range-split parallel
// compaction to accurately estimate row distribution for overlapping segments.
// Setting to 0 disables sampling. The per-segment value is persisted in
// SegmentMetadataPB.deprecated_sort_key_sample_row_interval so that a runtime change
// does not break cross-version readers.
CONF_mInt64(segment_sort_key_sample_row_interval, "65536");

// Write-time gate. When true, the segment writer ADDITIONALLY writes a full, untruncated,
// all-sort-column order-preserving sort key index page (alongside the always-written legacy
// truncated short key page) and stops writing the metadata sort-key samples. When false, only the
// legacy short key page + metadata samples are written. Default true.
CONF_mBool(enable_full_sort_key_index, "true");

// Read-time gate (rollback valve). When true, query read paths (segment seek + logical split) USE
// the full sort key index page when a segment has one. When false, they fall back to the legacy
// truncated short key page for ALL segments (including ones that already carry a full page) --
// go-forward rollback with no data rewrite. Tablet split / range-split compaction are NOT gated by
// this switch (they consume the full page by presence). Default true.
CONF_mBool(enable_full_sort_key_index_read, "true");

// Maximum size in bytes of one row's encoded full sort key. Mirrors primary_key_limit_size. A load,
// Spark push, or schema change that would admit a row with a wider sort key fails with a
// non-retryable error, which bounds the size of the full sort key index page and the memory it
// occupies once loaded. Compaction and post-commit segment rewrites are not checked, because a
// failure there runs after commit and would put the tablet into an error state. The check applies
// whenever the sort key can be encoded, independently of enable_full_sort_key_index, so that
// admission and segment writing cannot disagree. A non-positive value disables it.
CONF_mInt32(sort_key_limit_size, "1024");

CONF_Bool(enable_transparent_data_encryption, "false");

// CONF_Int32(default_num_rows_per_data_block, "1024");
CONF_mInt32(default_num_rows_per_column_file_block, "1024");

// data and index page size, default is 64k
CONF_Int32(data_page_size, "65536");

// Write-time gate for the segment "small index region" layout. When true, a segment emits every
// column's ordinal index and page zone map as one contiguous run immediately before the short
// key index and the footer, instead of interleaving each column's indexes after that column's
// data pages. Both
// layouts are readable by any binary -- indexes are always located through absolute
// PagePointers -- so this can be flipped at any time and mixed within a tablet.
//
// The point is cold-read latency on shared-data: the reader must load the ordinal index of
// every accessed column, and the page zone map of every predicate column, before it can read
// any data. In the legacy layout those live at N scattered offsets, so they cost N serial
// round trips to remote storage, each pulling a whole cache block. Gathered at the tail they
// cost one.
//
// Every write path that ends in finalize_footer() produces the region, vertical compaction and
// partial-update rewrites included: a vertical writer calls finalize_columns() once per column
// group, and the deferred index writers accumulate across groups so that an early group's
// indexes still land at the tail rather than under a later group's data pages.
CONF_mBool(enable_segment_tail_index_region, "false");

// Read-time gate for the matching prefetch. When true, opening a segment whose footer carries
// a small index region issues ONE read covering the whole region, so that the per-column index
// loads that immediately follow are served from the block cache instead of going remote one at
// a time. Segments without the footer fields are unaffected. Set false to measure the layout
// change without the prefetch, or as a rollback valve.
CONF_mBool(enable_segment_tail_index_prefetch, "true");

// Upper bound on the small index region prefetch. A very wide table can produce a region far
// larger than any query needs, and reading it whole would trade the round trips back for
// wasted bytes. Regions above this size are not prefetched; their indexes are read per column
// as in the legacy layout.
CONF_mInt64(segment_tail_index_prefetch_max_bytes, "16777216");

// Read-time gate for the concurrent data page prefetch. Once a segment's tail index region has
// been parsed, the ordinal index of every accessed column is already in memory, so the absolute
// byte range of every data page the scan is about to read is known before the first one is
// fetched. When true, those ranges are folded onto the cache blocks behind them and the blocks
// are filled several at a time through a dedicated pool, instead of the read loop discovering
// them one at a time and waiting out a full remote round trip for each. The block set is
// exactly the one the read loop would have fetched, so this changes when the blocks are fetched
// and how many at once, not how many.
CONF_mBool(enable_segment_data_page_concurrent_prefetch, "false");

// How many cache blocks of one segment the prefetch above fills at the same time. The effective
// value is capped by the number of independent file handles the scan holds on that segment (one
// per non-DCG column it reads): a cachefs handle serializes on its own persist stream, so two
// blocks can only be fetched concurrently through two handles.
CONF_mInt32(segment_data_page_prefetch_concurrency, "8");

// Size of the pool that runs the prefetch above. Its threads spend their time blocked on remote
// reads rather than on CPU, so this is sized after the scan instances a node runs concurrently,
// not after its cores. The pool is built on first use, so a node with the prefetch off never
// creates it.
CONF_Int32(segment_data_page_prefetch_thread_num, "256");

// Number of consecutive segment iterators whose data-page prefetch may be in flight at once.
// 0 disables cross-segment lookahead. Positive values are bounded to [2, 4] by UnionIterator;
// the current segment is included in the window. This only takes effect when concurrent data-page
// prefetch is enabled and the segment uses the tail-index layout.
CONF_mInt32(segment_iterator_lookahead, "0");

// Read-time gate for serving a segment's small index reads from one shared buffered stream.
// The prefetch above pays off only through a block cache: it warms the region so the per-column
// index loads that follow hit the cache. A scan that bypasses the cache -- skip_local_disk_cache,
// or a table with datacache disabled -- gets nothing from it, and still spends one remote read
// per column on indexes that are now contiguous. Pointing every column's small index reads at a
// single stream closes that gap without a cache: the first read's buffer fill covers the region,
// and the rest are memcpy.
//
// Requires the tail index region. With the indexes scattered per column, consecutive reads land
// outside the buffer window, so sharing a stream would pay a discard and a refill each time and
// buy nothing -- which is why this is gated on the region existing, not on the config above.
CONF_mBool(enable_segment_shared_small_index_stream, "true");

// Upper bound on the shared small index stream's buffer. The buffer is sized to the region so
// that one fill covers it; a region larger than this gets a buffer of this size instead, which
// degrades to a few reads for the whole region rather than one per column.
CONF_mInt64(segment_shared_small_index_stream_max_buffer_bytes, "4194304");

// When true, high-cardinality string columns that fall back to plain encoding are written with
// the PLAIN_ENCODING_DELTA_OFFSET column encoding, whose page offset trailer stores per-value
// deltas (string lengths) instead of absolute offsets. Deltas are near-constant for fixed-ish
// strings and compress far better than monotonically increasing absolute offsets, while the
// uncompressed trailer keeps the same size. The format is identified by the column encoding
// recorded in the segment metadata (not by any in-trailer flag), so a BE that does not know the
// encoding fails to open the segment instead of misreading it. Only the write side is gated by
// this config; default false.
CONF_mBool(enable_binary_plain_delta_offset, "false");

// whether to enable the bitmap index memory cache
CONF_mBool(enable_bitmap_index_memory_page_cache, "true");

// whether to enable the zonemap index memory cache
CONF_mBool(enable_zonemap_index_memory_page_cache, "true");

// whether to enable the ordinal index memory cache
CONF_mBool(enable_ordinal_index_memory_page_cache, "true");

// ========================== ZONEMAP BEGIN ===================================
// Enable ZoneMap for string (CHAR/VARCHAR) columns using prefix-based min/max
CONF_mBool(enable_string_prefix_zonemap, "true");

// Prefix length used for string ZoneMap min/max when enabled
CONF_mInt32(string_prefix_zonemap_prefix_len, "16");

// Max row source mask memory bytes, default is 200M.
// Should be smaller than compaction_mem_limit.
// When the row source mask buffer exceeds this, it will be persisted to a temporary file on the disk.
CONF_Int64(max_row_source_mask_memory_bytes, "209715200");

// Automatically detect whether a char/varchar column to use dictionary encoding
// If the number of keys in a dictionary is greater than this fraction of the total number of rows
// turn off dictionary dictionary encoding. This only will detect first chunk
// set to 1 means always use dictionary encoding
CONF_Double(dictionary_encoding_ratio, "0.7");

// Some data types use dictionary encoding, and this configuration is used to control
// the size of dictionary pages. If you want a higher compression ratio, please increase
// this configuration item, but be aware that excessively large values may lead to
// performance degradation.
CONF_Int32(dictionary_page_size, "1048576");

CONF_Int32(small_dictionary_page_size, "4096");

// Just like dictionary_encoding_ratio, dictionary_encoding_ratio_for_non_string_column is used for
// no-string column.
CONF_Double(dictionary_encoding_ratio_for_non_string_column, "0");

// The minimum chunk size for dictionary encoding speculation
CONF_Int32(dictionary_speculate_min_chunk_size, "10000");

// Metadata cache limit for shared-nothing mode. Not working for PK table now.
// Disable metadata cache when metadata_cache_memory_limit_percent <= 0.
CONF_mInt32(metadata_cache_memory_limit_percent, "30"); // 30%

// The bitmap max filter ratio, valid value range is: [0-1000].
CONF_Int16(bitmap_max_filter_ratio, "1");

// IMPORTANT NOTE: changing this config to 1 must require all BEs to be upgraded to new version,
// which support this config.
// DO NOT change this config unless you known how.
// 0 for BITSHUFFLE_NULL
// 1 for LZ4_NULL
CONF_mInt16(null_encoding, "0");

#ifdef USE_STAROS
CONF_Int32(starlet_star_cache_block_size_bytes, "1048576");

#endif
CONF_mBool(enable_index_segment_level_zonemap_filter, "true");

CONF_mBool(enable_index_page_level_zonemap_filter, "true");

CONF_mBool(enable_index_bloom_filter, "true");

CONF_mBool(enable_index_bitmap_filter, "true");

CONF_mBool(apply_del_vec_after_all_index_filter, "true");

// some internal parameters are used to control the execution strategy of join runtime filter pushdown.
// Do not modify them unless necessary.
CONF_mInt64(rf_sample_rows, "1024");

CONF_mInt64(rf_sample_ratio, "32");

CONF_mInt64(rf_branchless_ratio, "8");

} // namespace starrocks::config
