// Copyright 2021-present StarRocks, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is generated by build-support/gen_config_fwd_headers.py from
// be/src/common/config.h. Do not edit manually.

#pragma once

#include "common/configbase.h"

namespace starrocks::config {
// hdfs hedged read
CONF_Bool(hdfs_client_enable_hedged_read, "false");

// dfs.client.hedged.read.threadpool.size
CONF_Int32(hdfs_client_hedged_read_threadpool_size, "128");

// dfs.client.hedged.read.threshold.millis
CONF_Int32(hdfs_client_hedged_read_threshold_millis, "2500");

CONF_Int32(hdfs_client_max_cache_size, "64");

CONF_Int32(hdfs_client_io_read_retry, "0");

} // namespace starrocks::config
