// Copyright 2021-present StarRocks, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is generated by build-support/gen_config_fwd_headers.py from
// be/src/common/config.h. Do not edit manually.

#pragma once

#include "common/configbase.h"

namespace starrocks::config {
// process memory limit specified as number of bytes
// ('<int>[bB]?'), megabytes ('<float>[mM]'), gigabytes ('<float>[gG]'),
// or percentage of the physical memory ('<int>%').
// defaults to bytes if no unit is given"
// must larger than 0. and if larger than physical memory size,
// it will be set to physical memory size.
CONF_String(mem_limit, "90%");

// Enable the jemalloc tracker, which is responsible for reserving memory
CONF_Bool(enable_jemalloc_memory_tracker, "true");

// The jemalloc runtime options applied via the JEMALLOC_CONF environment variable when the
// process is started in the normal mode (i.e. neither --jemalloc_debug nor --check_mem_leak) and JEMALLOC_CONF is not already set.
// jemalloc reads JEMALLOC_CONF at process init before BE config parsing, so it is exported by
// bin/start_backend.sh. It is ignored under the jemalloc_debug and check_mem_leak modes, which
// force their own JEMALLOC_CONF.
// Updating this config at runtime only re-applies the options that jemalloc itself allows to be
// changed after init, namely dirty_decay_ms, muzzy_decay_ms and prof_active. Adding, removing or
// changing any other option is rejected, because the corresponding `opt.*` mallctl nodes are
// read-only; those need a restart. Note that prof_active can only be turned on when the process
// was started with prof:true.
// NOTE: keep this default in sync with the normal-mode default in bin/start_backend.sh.
CONF_mString(jemalloc_conf,
            "percpu_arena:percpu,oversize_threshold:0,muzzy_decay_ms:5000,dirty_decay_ms:5000,metadata_thp:auto,"
            "background_thread:true,prof:true,prof_active:false");

// Whether abort the process if a large memory allocation is detected which the requested
// size is larger than the available physical memory without wrapping with TRY_CATCH_BAD_ALLOC
CONF_mBool(abort_on_large_memory_allocation, "false");

CONF_Bool(disable_mem_pools, "false");

// Whether to allocate chunk using mmap. If you enable this, you'd better to
// increase vm.max_map_count's value whose default value is 65530.
// you can do it as root via "sysctl -w vm.max_map_count=262144" or
// "echo 262144 > /proc/sys/vm/max_map_count"
// NOTE: When this is set to true, you must set chunk_reserved_bytes_limit
// to a relative large number or the performace is very very bad.
CONF_Bool(use_mmap_allocate_chunk, "false");

// Aligement
CONF_Int32(memory_max_alignment, "16");

} // namespace starrocks::config
