// Copyright 2021-present StarRocks, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is generated by build-support/gen_config_fwd_headers.py from
// be/src/common/config.h. Do not edit manually.

#pragma once

#include "common/configbase.h"

namespace starrocks::config {
// The count of thread to publish version per transaction
CONF_mInt32(transaction_publish_version_worker_count, "0");

// The count of thread to apply rowset in primary key table
// 0 means apply worker count is equal to cpu core count
CONF_mInt32(transaction_apply_worker_count, "0");

CONF_mInt32(get_pindex_worker_count, "0");

CONF_mInt32(transaction_apply_thread_pool_num_min, "0");

CONF_Int32(transaction_apply_worker_idle_time_ms, "500");

CONF_mInt32(update_compaction_per_tablet_min_interval_seconds, "120"); // 2min

// This config controls max memory that we can use for partial update.
CONF_mInt64(partial_update_memory_limit_per_worker, "2147483648"); // 2GB

// === SDCG (Sparse Delta Column Group) ===
// Master gate for the sparse delta column group write path (lake / shared-data only).
// When false the behavior is byte-identical to today: column-mode partial update
// always writes dense `.cols`, and no `.spcols` files are produced or referenced.
CONF_mBool(enable_sparse_dcg, "false");

// Density decision threshold: when (K updated rows / M source-segment rows) is at
// least this ratio, take the dense `.cols` path instead of writing a sparse `.spcols`.
CONF_mDouble(sdcg_dense_threshold, "0.3");

// Absolute cap on K (updated rows in one source segment) for the sparse path: at or
// above this many rows, fall back to dense even if the density ratio is below
// sdcg_dense_threshold (large K makes per-ordinal random seeks costlier than a full
// sequential scan; lake/object-storage favors the conservative cap).
CONF_mInt64(sdcg_sparse_max_rows, "50000");

// Cost-model lower gate on the source-segment row count M: only take the sparse `.spcols` path when the
// base segment is at least this large. Sparse's per-file framing + 8B/row source_rowid + read-amp only
// pay off when dense's whole-column rewrite (M rows × col width) is genuinely expensive, which scales
// with M. On small segments (or K spread thin across many small segments, large R) dense is faster and
// reads flatter even though sparse writes fewer bytes. M below this floor -> dense. Validated: small
// segment (M~31k) sparse LOST, large segment (M>=100k/1M) sparse won 2-7x. 0 disables the gate.
CONF_mInt64(sdcg_sparse_min_segment_rows, "65536");

// SAFETY-VALVE cap on sparse overlay-chain depth. Convergence of the chain is normally done by
// BACKGROUND lake PK compaction (it reads input segments through the DCG overlay and emits fresh dense
// segments, dropping the sparse chain). Only if a chain reaches this HIGH cap before compaction
// converges it does the writer fall back to a synchronous in-place dense rewrite -- a rare safety net,
// no longer a per-batch convergence mechanism, so it does not inflate publish-time p95. (Was 16, which
// fired a depth-16 dense rewrite on the load's critical path every ~16 partial-update batches.)
CONF_mInt32(sdcg_promotion_hard_count, "256");

// UNIFIED single user knob — per-column allowed READ-AMP BUDGET R_max (= max sparse overlay layers a
// read must merge). Collapses the read-amp control into ONE number, mapped internally to the dense/sparse
// gate + the fold trigger:
//   <0 (default -1) = AUTO: per-column-WIDTH defaults (wide cols fold near depth-1 via
//                    sdcg_compaction_trigger_depth_wide, narrow at the default depth) — the validated behavior.
//   0  = force DENSE (no sparse overlay ever): write-time merge via column-dense (supersede) / row;
//        zero sparse read-amp. (Fixed-column path in this first version; flexible-path budget TBD.)
//   N>0 = allow sparse, fold the chain when it would exceed N layers (uniform trigger = N+1), overriding
//        the per-width auto defaults. Larger N = more write throughput, more read-amp.
// Design: handbook/plans/active/2026-06-01-partial-update-sdcg-design.md §5.2.4.
CONF_mInt64(sdcg_read_amp_budget, "-1");

// partial_update_mode=auto level-1 (per-load) column-vs-ROW routing by UPDATE WIDTH. ROW (whole-row
// rewrite) wins over the column overlays when many columns change at once: sparse pays per-column
// machinery (a roaring bitmap + column file + apply-time DCG merge PER updated column) and dense pays
// M_seg*W_upd, both of which exceed row's bulk rewrite once the update is wide. So auto routes ROW when
// the update touches a large fraction of value columns (>= sdcg_auto_row_width_frac) OR a large absolute
// count (>= sdcg_auto_row_width_min_cols); otherwise COLUMN, whose per-segment dense/sparse format is
// chosen at apply. Read-strictness no longer forces ROW (dense is read-flat too) -- it is handled at
// level-2. Calibration knobs (mutable so they can be tuned on a live cluster).
CONF_mDouble(sdcg_auto_row_width_frac, "0.5");

CONF_mInt32(sdcg_auto_row_width_min_cols, "8");

// partial_update_mode=auto level-2 (per-segment) sustained-load penalty: sparse write throughput decays
// as the overlay chain deepens (chains outrun compaction), so scale the sparse/packed WRITE cost by
// (1 + sdcg_auto_sparse_depth_penalty * chain_depth). This makes the cost model migrate sparse->dense as
// depth grows under sustained load, instead of staying on sparse until the hard depth valve trips.
// DEFAULT 0 (disabled): cluster tests showed a nonzero penalty makes auto OSCILLATE sparse<->dense with no
// hysteresis, producing mixed overlay chains that read AND write worse than any single mode, while pure
// sparse self-limits (compaction plateaus its depth). Kept as a mutable knob for future calibration, off
// by default. Mutable for live calibration.
CONF_mDouble(sdcg_auto_sparse_depth_penalty, "0");

// DEPRECATED (no longer drives the write path): the old in-place-promotion threshold as a fraction of
// the base segment row count M. Kept for config compatibility only; convergence is now
// background-compaction-driven, not cum_K/M-threshold-driven.
CONF_mDouble(sdcg_promotion_threshold, "0.3");

// Per-column segment-level zone-map gate refinement. Historically, when a segment has ANY delta
// column group, segment-level zone-map pruning is disabled for ALL non-key columns, because a DCG
// rewrites some columns and the base segment's zone maps are stale for them. That is overly broad:
// a column NOT present in any DCG still has fully valid base zone maps and can be pruned safely.
// When true, segment-level zone-map pruning is restored per-column for columns absent from every
// DCG (and for columns whose DCG layer stack contains no SPARSE overlay -- the dense `.cols` file's
// own zone map already governs page-level pruning, see SegmentZoneMapPruner). Columns covered by a
// SPARSE overlay are never segment-pruned (the overlay carries newer values). This refinement also
// benefits stock dense-DCG tables (flag enable_sparse_dcg off), so it is gated separately. DEFAULT
// false: this is the ONE SDCG read-path refinement that would otherwise change behavior for existing
// dense-DCG tables even with enable_sparse_dcg off; keeping it off preserves the historical
// all-or-nothing pruning so SDCG is fully inert by default (GA opt-in posture). Set true to opt into
// the per-column pruning refinement (correct + reversible).
CONF_mBool(sdcg_enable_per_column_zone_map, "false");

// The minimum threshold of data size for enabling pk index eager build.
// Default is 100MB.
CONF_mInt64(pk_index_eager_build_threshold_bytes, "104857600");

// Compaction threadpool max thread num for cloud native pk index compact in shared-data mode.
CONF_mInt32(pk_index_parallel_compaction_threadpool_max_threads, "0");

// The queue size for pk index parallel compaction threadpool in shared-data mode.
CONF_mInt32(pk_index_parallel_compaction_threadpool_size, "1048576");

// The splitting threshold for PK index compaction tasks — when the total size of the files involved in a task is
// smaller than this threshold, the task will not be split.
// Default is 32MB.
CONF_mInt64(pk_index_parallel_compaction_task_split_threshold_bytes, "33554432");

// Target file size for primary key index in shared-data mode.
// Default is 64MB.
CONF_mInt64(pk_index_target_file_size, "67108864");

// Compaction score ratio for primary key index in shared-data mode.
// E.g. if we have N fileset, the compaction score will be N * pk_index_compaction_score_ratio
// Default is 1.5.
CONF_mDouble(pk_index_compaction_score_ratio, "1.5");

// early sst compaction threshold for primary key index in shared-data mode.
CONF_mInt32(pk_index_early_sst_compaction_threshold, "5");

// Whether enable parallel get for primary key index in shared-data mode.
CONF_mBool(enable_pk_index_parallel_execution, "true");

// The minimum rows threshold to enable parallel get for primary key index in shared-data mode.
CONF_mInt64(pk_index_parallel_execution_min_rows, "16384");

// Maximum number of per-output-segment .lcrm reads kept in flight by
// RowsMapperIterator during light COMPACTION publish. The unit is **sub-chunks**
// (each lake_rows_mapper_sub_chunk_bytes in size, never crossing a segment
// boundary): K controls how many sub-chunk reads stay in flight, decoupled from
// segment count. Memory bound = K * lake_rows_mapper_sub_chunk_bytes. Each chunk
// owns its own RandomAccessFile (no shared file-class state across tasks) and
// is consumed in segment order via vector::swap (zero memcpy when a segment
// fits one sub-chunk). Set to 1 to disable pipelining and fall back to the
// sequential single-shot read path.
CONF_mInt32(lake_rows_mapper_read_parallelism, "32");

// Sub-chunk granularity for RowsMapperIterator pipelined reads. Each segment is
// split into ceil(segment_bytes / sub_chunk_bytes) sub-chunks that the iterator
// pipelines independently. Smaller values raise the achievable parallelism for
// few-but-large output segments at the cost of more range-reads and an extra
// memcpy on consume. Defaults to 4 MiB (starcache disk-tier block-friendly).
CONF_mInt64(lake_rows_mapper_sub_chunk_bytes, "4194304");

// Memory-pressure gate for the parallel prefetch paths used while rebuilding the shared-data
// primary key index. When the update mem tracker is already past this percent (0-100) of its
// limit, the rebuild falls back to a single-pass loop that holds only one decoded column at a
// time, trading the cold-start latency win for bounded peak memory. Gates parallel reads of
// del, segment, and other files during the rebuild.
CONF_mInt32(pk_index_parallel_rebuild_mem_ratio, "50");

// The maximum number of memtables for pk index in shared-data mode.
CONF_mInt32(pk_index_memtable_max_count, "2");

// The maximum wait flush timeout for pk index memtable in shared-data mode, in milliseconds.
CONF_mInt64(pk_index_memtable_max_wait_flush_timeout_ms, "30000");

// The parameters for pk index size-tiered compaction strategy.
CONF_mInt64(pk_index_size_tiered_min_level_size, "131072");

CONF_mInt64(pk_index_size_tiered_level_multiplier, "10");

CONF_mInt64(pk_index_size_tiered_max_level, "5");

// Used to control the sampling interval size for SSTable files.
CONF_mInt64(pk_index_sstable_sample_interval_bytes, "16777216");

// Controls merge condition evaluation behavior within the same transaction for primary key tables.
// When enabled (true), allows load spilling and parallel execution optimizations for condition updates
// by skipping merge condition checks on data from the same transaction. This improves performance
// when ingesting large batches with condition updates, as same-transaction conflicts don't need
// complex comparison logic.
// Default: false (conservative, validates all conditions even within same transaction)
CONF_mBool(ignore_merge_condition_inside_same_transaction, "false");

CONF_Int32(update_memory_limit_percent, "60");

// If enable_retry_apply is set to true, the system will attempt retries when apply fails.
// Retry scenarios for apply operations include the following cases:
//   1. ​Retry indefinitely for explicitly retryable errors (e.g., memory limits)
// ​  2. No retry for explicitly non-retryable errors (e.g., Corruption) → Directly enter error state
// ​  3. Retry until timeout: If still failing after timeout duration → Enter error state
CONF_mBool(enable_retry_apply, "true");

CONF_mInt32(retry_apply_interval_second, "30");

CONF_mInt32(retry_apply_timeout_second, "7200");

// The value must be power of two.
CONF_Int32(pk_index_map_shard_size, "4096");

// The chunk size for vector query engine
CONF_Int32(vector_chunk_size, "4096");

// The maximum number of version per tablet. If the
// number of version exceeds this value, new write
// requests will fail.
CONF_mInt16(tablet_max_versions, "1000");

CONF_mBool(experimental_lake_ignore_pk_consistency_check, "false");

// Persist the in-transaction upsert/delete order (op_offset) for shared-data PK del files.
// DISABLED by default for downgrade safety: when on, a correctly-interleaved load can persist a
// del file that references a key still live in the same rowset (the re-upsert wins). A pre-fix BE
// (rollback, or a not-yet-upgraded node / cross-version OpReplication target) treats deletes as
// "after all segments" and would erase that key on index rebuild while the delvec keeps it live,
// turning a benign "missing row" into a duplicate primary key. Leaving op_offset unset keeps the
// whole apply/persist/rebuild chain on the legacy "delete after all segments" path. Enabled by
// default; set it to false before rolling back to (or running a mixed cluster with) a pre-fix BE so
// the legacy path is used and no incompatible on-disk state is written.
CONF_mBool(lake_enable_pk_preserve_txn_delete_order, "true");

CONF_mBool(enable_primary_key_recover, "false");

// Used for control memory usage of update state cache and compaction state cache
CONF_mInt32(lake_pk_preload_memory_limit_percent, "30");

CONF_mInt32(lake_pk_index_sst_min_compaction_versions, "2");

CONF_mInt32(lake_pk_index_sst_max_compaction_versions, "100");

// When the ratio of cumulative level to base level is greater than this config, use base merge.
CONF_mDouble(lake_pk_index_cumulative_base_compaction_ratio, "0.1");

CONF_Int32(lake_pk_index_block_cache_limit_percent, "10");

// The maximum number of files which need to rebuilt in cloud native pk index.
// If files which need to rebuilt larger than this, we will flush memtable immediately.
CONF_mInt32(cloud_native_pk_index_rebuild_files_threshold, "50");

// Batch row count for PrimaryKeyCompactionConflictResolver::execute() — multiple per-chunk
// `params.index->replace()` calls are accumulated into one call across this many rows. Each
// replace() in LakePersistentIndex runs a memtable flush check + lock round-trip; batching N
// chunks amortises that work by ~N×. Setting this <= vector_chunk_size (4096) effectively
// disables batching. 32 K rows ≈ 8 chunks ≈ ~1.6 MB of accumulated PK bytes.
CONF_mInt32(primary_key_compaction_replace_batch_rows, "32768");

// The maximum number of rows which need to be rebuilt in cloud native pk index.
// If rows which need to be rebuilt exceed this threshold, we will flush memtable immediately
// to reduce index rebuild cost. 0 means disabled.
CONF_mInt64(cloud_native_pk_index_rebuild_rows_threshold, "10000000");

CONF_mInt64(l0_l1_merge_ratio, "10");

// max wal file size in l0, 200MB
CONF_mInt64(l0_max_file_size, "209715200");

// 2MB
CONF_mInt64(l0_min_mem_usage, "2097152");

// 100MB
CONF_mInt64(l0_max_mem_usage, "104857600");

CONF_mInt64(max_tmp_l1_num, "10");

CONF_mBool(enable_parallel_get_and_bf, "false");

// Control if using the minor compaction strategy
CONF_Bool(enable_pindex_minor_compaction, "true");

// if l2 num is larger than this, stop doing async compaction,
// add this config to prevent l2 grow too large.
CONF_mInt64(max_allow_pindex_l2_num, "5");

// Number of max major compaction threads
CONF_mInt32(pindex_major_compaction_num_threads, "0");

// Limit of major compaction per disk.
CONF_mInt32(pindex_major_compaction_limit_per_disk, "1");

// control the persistent index schedule compaction interval
CONF_mInt64(pindex_major_compaction_schedule_interval_seconds, "15");

// control the local persistent index in shared_data gc/evict interval
CONF_mInt64(pindex_shared_data_gc_evict_interval_seconds, "18000"); // 5 hour

// enable use bloom filter for pindex or not
CONF_mBool(enable_pindex_filter, "true");

// enable persistent index compression
CONF_mBool(enable_pindex_compression, "true");

// use bloom filter in pindex can reduce disk io, but in the following scenarios, we should skip the bloom filter
// 1. The records to be found are in the index, bloom filter is no usage
// 2. The records to be found is very small but bloom filter is very large, read bloom filter may cost a lot of disk io
// So the bloom filter bytes should less than the index data we need to scan in disk, and the default strategy is if bloom
// filter bytes is less or equal than 10% of pindex bytes, we will use bloom filter to filter some records
CONF_mInt32(max_bf_read_bytes_percent, "10");

// If primary compaction pick all rowsets, we could rebuild pindex directly and skip read from index.
CONF_mBool(enable_pindex_rebuild_in_compaction, "true");

// enable read pindex by page
CONF_mBool(enable_pindex_read_by_page, "true");

// check need to rebuild pindex or not
CONF_mBool(enable_rebuild_pindex_check, "true");

// Number of max persistent index load threads
CONF_mInt32(pindex_load_thread_pool_num_max, "8");

// Max wait time to rebuild persistent index in full clone
CONF_mInt32(pindex_rebuild_clone_wait_seconds, "120");

// Max wait time to rebuild persistent index in load (preload update state)
CONF_mInt32(pindex_rebuild_load_wait_seconds, "20");

CONF_mBool(enable_pk_value_column_zonemap, "true");

// Max size of key columns size of primary key table, default value is 128 bytes
CONF_mInt32(primary_key_limit_size, "128");

// used for control the max memory cost when batch get pk index in each tablet
CONF_mInt64(primary_key_batch_get_index_memory_limit, "104857600"); // 100MB

// ======================= FLAT JSON end ==============================================

// Allowable intervals for continuous generation of pk dumps
// Disable when pk_dump_interval_seconds <= 0
CONF_mInt64(pk_dump_interval_seconds, "3600"); // 1 hour

CONF_mBool(enable_pk_strict_memcheck, "true");

CONF_mInt32(apply_version_slow_log_sec, "30");

// Do lazy load when PK column larger than this threshold. Default is 300MB.
CONF_mInt64(pk_column_lazy_load_threshold_bytes, "314572800");

// Batch size for column mode partial update when processing insert rows.
// If set to 0 or negative, will be clamped to 1 to avoid infinite loop.
// Default is 4096.
CONF_mInt32(column_mode_partial_update_insert_batch_size, "4096");

} // namespace starrocks::config
