// Copyright 2021-present StarRocks, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is generated by build-support/gen_config_fwd_headers.py from
// be/src/common/config.h. Do not edit manually.

#pragma once

#include "common/configbase.h"

namespace starrocks::config {
// Number of http workers in BE
CONF_Int32(be_http_num_workers, "48");

// Whether to execute load channel RPC requests asynchronously, that is,
// to run RPCs in a separate thread pool instead of within BRPC workers
CONF_mBool(enable_load_channel_rpc_async, "true");

// Time(seconds) for load channel to wait for clean up load id after aborted.
//
// When a load job is cancelled or failed, load channel will be aborted.
// In order to reject any late-arrival request, load channel will keep
// the aborted load id for this duration before cleaning up.
// * Setting it too small may cause late-arrival requests being accepted incorrectly.
// * Setting it too large may cause resources to be held for a long time.
// NOTE: The background thread will clean up periodically.
// In production, the minimum interval is 60 seconds.
// Default is 600 seconds.
CONF_mInt32(load_channel_abort_clean_up_delay_seconds, "600");

// The maximum amount of data that can be processed by a stream load
CONF_mInt64(streaming_load_max_mb, "102400");

// Some data formats, such as JSON, cannot be streamed.
// Therefore, it is necessary to limit the maximum number of
// such data when using stream load to prevent excessive memory consumption.
CONF_mInt64(streaming_load_max_batch_size_mb, "100");

// The alive time of a TabletsChannel.
// If the channel does not receive any data till this time,
// the channel will be removed.
CONF_Int32(streaming_load_rpc_max_alive_time_sec, "1200");

// txn commit rpc timeout
CONF_mInt32(txn_commit_rpc_timeout_ms, "60000");

CONF_Bool(enable_load_colocate_mv, "true");

CONF_mBool(enable_http_stream_load_limit, "false");

CONF_mBool(enable_stream_load_verbose_log, "false");

} // namespace starrocks::config
