// Copyright 2021-present StarRocks, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is generated by build-support/gen_config_fwd_headers.py from
// be/src/common/config.h. Do not edit manually.

#pragma once

#include "common/configbase.h"

namespace starrocks::config {
// If true, clear udf cache every time be starts
CONF_Bool(clear_udf_cache_when_start, "false");

// python envs config
// create time worker timeout
CONF_mInt32(create_child_worker_timeout_ms, "1000");

// report python worker STDERR to client
CONF_Bool(report_python_worker_error, "true");

CONF_Bool(python_worker_reuse, "true");

CONF_Int32(python_worker_expire_time_sec, "300");

// Timeout (ms) for the Arrow Flight call to a Python UDF worker (local or external service_url).
// Applied as the gRPC deadline on the DoExchange stream, so a dead/unreachable/hung worker fails
// the query instead of hanging forever. Note it bounds the whole stream's lifetime, so set it above
// the longest expected UDF query. 0 (default) disables the timeout (wait indefinitely).
CONF_mInt32(python_udf_rpc_timeout_ms, "0");

// Python UDF worker sandbox. Selects how the spawned python worker is isolated:
//   "off"     - no isolation (default; the worker runs as the BE OS user)
//   "seccomp" - seccomp syscall filter + rlimit only (zero privilege, works in any container)
//   "nsjail"  - full Linux-namespace isolation via nsjail (see python_udf_sandbox_mode)
CONF_String(python_udf_sandbox, "off");

// Namespace strategy for the "nsjail" sandbox:
//   "auto"       - rootless (unprivileged user namespace) if available, else CAP_SYS_ADMIN,
//                  else degrade to seccomp-only (unless python_udf_sandbox_required)
//   "rootless"   - force unprivileged user namespace
//   "privileged" - force host CAP_SYS_ADMIN (no user namespace)
CONF_String(python_udf_sandbox_mode, "auto");

// If true, refuse to run a python UDF when the requested sandbox level cannot be
// established (fail-closed). If false, log a warning and fall back (fail-open).
CONF_Bool(python_udf_sandbox_required, "false");

// Path to the nsjail binary used by the "seccomp"/"nsjail" sandbox.
CONF_String(python_udf_nsjail_path, "${STARROCKS_HOME}/lib/nsjail");

// nsjail config file for the full-namespace ("nsjail") sandbox. All isolation
// policy (namespaces, mounts, caps, uid map, rlimits, seccomp policy) lives in
// this file; the BE only renders the deployment paths into it at startup.
CONF_String(python_udf_nsjail_config, "${STARROCKS_HOME}/conf/pyudf-nsjail.conf");

// nsjail config file for the seccomp-only sandbox ("seccomp", and the automatic
// fallback of "nsjail" when namespaces are unavailable).
CONF_String(python_udf_nsjail_seccomp_config, "${STARROCKS_HOME}/conf/pyudf-nsjail-seccomp.conf");

} // namespace starrocks::config
