// Copyright 2021-present StarRocks, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is generated by build-support/gen_config_fwd_headers.py from
// be/src/common/config.h. Do not edit manually.

#pragma once

#include "common/configbase.h"

namespace starrocks::config {
// NOTE: it will be deleted.
CONF_mBool(enable_bitmap_union_disk_format_with_set, "false");

// The bitmap serialize version.
CONF_Int16(bitmap_serialize_version, "1");

// Used by to_base64
CONF_mInt64(max_length_for_to_base64, "200000");

// Used by bitmap functions
CONF_mInt64(max_length_for_bitmap_function, "1000000");

// jit LRU object cache size for total 32 shards, it will be an auto value if it < 0
// mem_limit = system memory or process memory limit if set.
// if mem_limit < 16 GB, disable JIT.
// else it  = min(mem_limit*0.01, 4MB);
CONF_mInt64(jit_lru_object_cache_size, "0");

// jit LRU cache size for total 32 shards, it will be an auto value if it <=0:
// mem_limit = system memory or process memory limit if set.
// if mem_limit < 16 GB, disable JIT.
// else it = min(mem_limit*0.01, 4MB)
CONF_mInt64(jit_lru_cache_size, "0");

// Evaluate each THEN branch of a searched CASE WHEN only on the rows that branch actually owns,
// instead of evaluating it over the whole chunk and picking rows afterwards. Only applies when the
// CASE result is a collection/variant type, where building a row is expensive enough to pay for
// compacting the branch's input rows into a sub-chunk.
// A branch is compacted when `owned_rows * ratio < chunk_rows`, i.e. when its selectivity is below
// 1/ratio; above that threshold copying the branch's input costs more than the skipped evaluation
// saves. 1 means "always compact", and 0 or less turns the whole thing off and restores the previous
// behavior - including the behavior change this carries, namely that a THEN or ELSE which would raise
// an error is no longer evaluated when no row selects it.
CONF_mInt32(case_when_selective_eval_ratio, "2");

} // namespace starrocks::config
