// Copyright 2021-present StarRocks, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is generated by build-support/gen_config_fwd_headers.py from
// be/src/common/config.h. Do not edit manually.

#pragma once

#include "common/configbase.h"

namespace starrocks::config {
// process memory limit specified as number of bytes
// ('<int>[bB]?'), megabytes ('<float>[mM]'), gigabytes ('<float>[gG]'),
// or percentage of the physical memory ('<int>%').
// defaults to bytes if no unit is given"
// must larger than 0. and if larger than physical memory size,
// it will be set to physical memory size.
CONF_String(mem_limit, "90%");

// The count of thread to publish version per transaction
CONF_mInt32(transaction_publish_version_worker_count, "0");

// Number of olap/external scanner thread pool size.
CONF_mInt32(scanner_thread_pool_thread_num, "48");

// Number of olap/external scanner thread pool size.
CONF_Int32(scanner_thread_pool_queue_size, "102400");

CONF_Int32(udf_thread_pool_size, "1");

// The threadpool max thread num for pk index get in shared-data mode.
CONF_mInt32(pk_index_parallel_execution_threadpool_max_threads, "0");

// The queue size for pk index parallel get threadpool in shared-data mode.
CONF_mInt32(pk_index_parallel_execution_threadpool_size, "1048576");

// Memtable flush threadpool max thread num for pk index in shared-data mode.
CONF_mInt32(pk_index_memtable_flush_threadpool_max_threads, "0");

// The queue size for pk index memtable flush threadpool in shared-data mode.
CONF_mInt32(pk_index_memtable_flush_threadpool_size, "2048");

// Max threads for lake partial update segment-level parallelism.
// <= 0 means use CPU core count. Runtime on/off is controlled by enable_pk_index_parallel_execution.
CONF_mInt32(lake_partial_update_thread_pool_max_threads, "0");

// Queue size for the lake partial update threadpool.
CONF_mInt32(lake_partial_update_thread_pool_queue_size, "2048");

CONF_Int32(streaming_load_thread_pool_num_min, "0");

CONF_Int32(streaming_load_thread_pool_idle_time_ms, "2000");

CONF_Int32(load_segment_thread_pool_num_max, "128");

CONF_Int32(load_segment_thread_pool_queue_size, "10240");

// Following 2 configs limit the memory consumption of load process on a Backend.
// eg: memory limit to 80% of mem limit config but up to 100GB(default)
// NOTICE(cmy): set these default values very large because we don't want to
// impact the load performace when user upgrading StarRocks.
// user should set these configs properly if necessary.
CONF_Int32(query_max_memory_limit_percent, "90");

CONF_Double(query_pool_spill_mem_limit_threshold, "1.0");

CONF_Int64(load_process_max_memory_limit_bytes, "107374182400"); // 100GB

// It's is a soft limit, when this limit is hit,
// memtable in delta writer will be flush to reduce memory cost.
// Load memory beyond this limit is allowed.
CONF_Int32(load_process_max_memory_limit_percent, "30"); // 30%

CONF_Int64(compaction_max_memory_limit, "-1");

CONF_Int32(compaction_max_memory_limit_percent, "100");

CONF_Int64(compaction_memory_limit_per_worker, "2147483648"); // 2GB

CONF_String(consistency_max_memory_limit, "10G");

CONF_Int32(consistency_max_memory_limit_percent, "20");

CONF_Int32(update_memory_limit_percent, "60");

// The max client cache number per each host.
// There are variety of client cache in BE, but currently we use the
// same cache size configuration.
// TODO(cmy): use different config to set different client cache if necessary.
CONF_Int32(max_client_cache_size_per_host, "10");

// Dir to save files downloaded by SmallFileMgr
CONF_String(small_file_dir, "${STARROCKS_HOME}/lib/small_file/");

// The number of scan threads pipeline engine.
CONF_Int64(pipeline_scan_thread_pool_thread_num, "0");

CONF_mDouble(pipeline_connector_scan_thread_num_per_cpu, "8");

// The number of execution threads for pipeline engine.
CONF_Int64(pipeline_exec_thread_pool_thread_num, "0");

// The number of threads for preparing fragment instances in pipeline engine, vCPUs by default.
// *  "n": positive integer, fixed number of threads to n.
// *  "0": default value, means the same as number of cpu cores.
// * "-n": negative integer, means n times of number of cpu cores.
CONF_Int64(pipeline_prepare_thread_pool_thread_num, "0");

CONF_Int64(pipeline_prepare_thread_pool_queue_size, "102400");

// The number of threads for executing sink io task in pipeline engine, vCPUs by default.
CONF_Int64(pipeline_sink_io_thread_pool_thread_num, "0");

CONF_Int64(pipeline_sink_io_thread_pool_queue_size, "102400");

// The number of threads for automatic partition thread pool. Queue size is 10x thread count.
CONF_Int64(automatic_partition_thread_pool_thread_num, "1000");

// Used to reject coming fragment instances, when the number of running drivers
// exceeds it*pipeline_exec_thread_pool_thread_num.
CONF_Int64(pipeline_max_num_drivers_per_exec_thread, "10240");

// hdfs hedged read
CONF_Bool(hdfs_client_enable_hedged_read, "false");

// dfs.client.hedged.read.threadpool.size
CONF_Int32(hdfs_client_hedged_read_threadpool_size, "128");

#ifdef USE_STAROS
// Root dir used for cache if cache enabled.
CONF_String(starlet_cache_dir, "");

#endif
CONF_mInt64(lake_metadata_cache_limit, /*2GB=*/"2147483648");

// max loop count when be waiting its fragments to finish. It has no effect if the var is configured with value <= 0.
CONF_mInt64(loop_count_wait_fragments_finish, "2");

// Determines whether to await at least one frontend heartbeat response indicating SHUTDOWN status before completing graceful exit.
//
// When enabled, the graceful shutdown process remains active until a SHUTDOWN confirmation is responded via heartbeat RPC,
// ensuring the frontend has sufficient time to detect the termination state between two regular heartbeat intervals.
CONF_mBool(graceful_exit_wait_for_frontend_heartbeat, "false");

// spill dirs
CONF_String(spill_local_storage_dir, "${STARROCKS_HOME}/spill");

CONF_Int32(internal_service_query_rpc_thread_num, "-1");

CONF_Int32(internal_service_datacache_rpc_thread_num, "-1");

// Used by query cache, cache entries are evicted when it exceeds its capacity(500MB in default)
CONF_Int64(query_cache_capacity, "536870912");

CONF_Bool(enable_resource_group_bind_cpus, "true");

CONF_mBool(enable_resource_group_cpu_borrowing, "true");

CONF_mInt32(dictionary_cache_refresh_threadpool_size, "8");

// config ENV PYTHONPATH
CONF_Strings(python_envs, "");

// Current supported modules:
// 1. data_cache (data cache for shared-nothing table, data cache for external table, data cache for shared-data table)
// 2. connector_scan_executor
// 3. non_pipeline_scan_thread_pool
// 4. pipeline_prepare_thread_pool
// 5. pipeline_sink_io_thread_pool
// 6. query_rpc_thread_pool
// 7. publish_version_worker_pool
// 8. olap_scan_executor
// 9. wg_driver_executor
// use commas to separate:
// * means release all above
// TODO(zhangqiang)
// can not set data_cache right now because release datacache may cause BE hang
// https://github.com/StarRocks/starrocks/issues/59226
CONF_mString(try_release_resource_before_core_dump, "");

CONF_Int32(merge_commit_thread_pool_num_min, "0");

CONF_Int32(merge_commit_thread_pool_num_max, "512");

CONF_Int32(merge_commit_thread_pool_queue_size, "4096");

CONF_mInt32(put_combined_txn_log_thread_pool_num_max, "64");

} // namespace starrocks::config
