#!/usr/bin/env python
# encoding: utf-8

"""
  Copyright 2021-present StarRocks, Inc. All rights reserved.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

       https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
"""

"""Generate SQL function reference sections from the in-source doc payload.

The payload lives in ``functions.py`` next to the signatures it documents, so a
developer changing a function has its documentation in the same file. This
script renders the payload into the Markdown pages under
``docs/<lang>/sql-reference/sql-functions/``.

Generated content is fenced by per-section markers::

    {/* AUTOGENERATED_START:syntax */}
    ## Syntax
    ...
    {/* AUTOGENERATED_END:syntax */}

Everything outside those markers is hand-written and preserved byte for byte.
Per-section (rather than whole-page) markers matter because hand-written
sections are interleaved with generated ones, and the interleaving order
differs between pages and between languages.

English pages get every section. Chinese and Japanese pages get only the
language-neutral sections -- syntax and examples -- under localized headings;
argument and return-value prose stays with the translation workflow. This is
deliberate: generating English only would let zh/ja signatures drift further,
which is the gap ``docs/scripts/sql_sample_parity.py`` already measures.

Usage::

    python3 gen_function_docs.py              # write
    python3 gen_function_docs.py --check      # exit 1 if anything would change
    python3 gen_function_docs.py --notes      # advisory: missing translations
    python3 gen_function_docs.py --function lpad --lang en
"""

import argparse
import os
import re
import sys

import functions

# ---------------------------------------------------------------------------
# Layout
# ---------------------------------------------------------------------------

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(_SCRIPT_DIR, "..", ".."))
DOCS_ROOT = os.path.join(REPO_ROOT, "docs")

LANGUAGES = ("en", "zh", "ja")

# Sections rendered per language, in the order they should appear when a
# section has to be inserted into a page that lacks it.
SECTION_ORDER = ("syntax", "parameters", "returns", "usage", "examples")

GENERATED_SECTIONS = {
    "en": ("syntax", "parameters", "returns", "usage", "examples"),
    "zh": ("syntax", "examples"),
    "ja": ("syntax", "examples"),
}

# The heading each generated section is written with.
HEADINGS = {
    "en": {
        "syntax": "Syntax",
        "parameters": "Parameters",
        "returns": "Return value",
        "usage": "Usage notes",
        "examples": "Examples",
    },
    "zh": {
        "syntax": "语法",
        "parameters": "参数说明",
        "returns": "返回值说明",
        "usage": "使用说明",
        "examples": "示例",
    },
    "ja": {
        "syntax": "構文",
        "parameters": "パラメータ",
        "returns": "戻り値",
        "usage": "使用上の注意",
        "examples": "例",
    },
}

# Headings recognized as an existing instance of a section, so that generation
# replaces it in place rather than adding a duplicate. Localized pages that
# were written with English headings are matched here too -- that is how the
# ja bit-functions heading split gets normalized.
HEADING_ALIASES = {
    "syntax": ("syntax", "语法", "文法", "構文"),
    "parameters": (
        "parameters", "parameter", "arguments", "argument",
        "参数说明", "参数", "パラメータ", "パラメーター", "引数",
    ),
    "returns": (
        "return value", "return values", "returned value", "return",
        "返回值说明", "返回值", "戻り値", "返り値",
    ),
    "usage": (
        "usage notes", "usage note", "usage",
        "使用说明", "注意事项", "使用上の注意", "使用上の注意事項",
    ),
    "examples": (
        "examples", "example",
        "示例", "例子", "例", "使用例",
    ),
}

# Fence languages. `sql` makes the query blocks visible to
# docs/scripts/extract_sql_samples.py, which only harvests ```sql fences --
# so generating them brings these examples under the doc-rot checker.
FENCE_QUERY = "sql"
FENCE_RESULT = "plaintext"

# MDX comments, not HTML comments. Docusaurus parses these .md pages as MDX,
# where `<!-- ... -->` is invalid; docs/styles/local/HTMLComment.yml enforces
# that as a Vale error and ci-vale.yml gates docs PRs on it.
MARKER_START = "{/* AUTOGENERATED_START:%s */}"
MARKER_END = "{/* AUTOGENERATED_END:%s */}"
MARKER_ANY = re.compile(
    r"^(?:\{/\*\s*AUTOGENERATED_(?:START|END):([a-z_]+)\s*\*/\}"
    r"|<!--\s*AUTOGENERATED_(?:START|END):([a-z_]+)\s*-->)$"
)

REQUIRED_FIELDS = ("category", "description", "syntax")


class DocError(Exception):
    """A payload or page problem that should stop generation."""


# ---------------------------------------------------------------------------
# Payload validation
# ---------------------------------------------------------------------------


def declared_function_names():
    """Every function name that has at least one signature in functions.py."""
    return set(entry[1] for entry in functions.vectorized_functions)


def validate_payload(payload, known_names):
    """Return a list of human-readable problems with the payload.

    Mirrors the hard-failure style of gen_functions.py, which exits on
    duplicate ids and duplicate signatures rather than generating something
    subtly wrong.
    """
    problems = []
    for name in sorted(payload):
        doc = payload[name]
        where = "function_docs['%s']" % name

        if name not in known_names:
            problems.append("%s: no signature named '%s' in vectorized_functions" % (where, name))

        for field in REQUIRED_FIELDS:
            if not doc.get(field):
                problems.append("%s: missing required field '%s'" % (where, field))

        description = doc.get("description", "")
        if len(description) >= 160:
            problems.append(
                "%s: description is %d chars; the frontmatter limit is 160"
                % (where, len(description))
            )
        if "\n" in description:
            problems.append("%s: description must be a single line" % where)

        for argument in doc.get("arguments", ()):
            if len(argument) != 3:
                problems.append(
                    "%s: each argument must be (name, types, description), got %r"
                    % (where, argument)
                )

        returned = doc.get("returned_value")
        if returned is not None and len(returned) != 2:
            problems.append("%s: returned_value must be (types, description)" % where)

        for example in doc.get("examples", ()):
            if len(example) != 3:
                problems.append(
                    "%s: each example must be (caption, query, result), got %r"
                    % (where, example)
                )
            elif not example[1].strip():
                problems.append("%s: example has an empty query" % where)

    return problems


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _fence(language, body):
    return "```%s\n%s\n```" % (language, body.rstrip("\n"))


def _format_types(spec):
    """Render a type spec as code spans.

    Bare angle brackets are parsed as JSX by MDX and break the Docusaurus
    build, so a type like ARRAY<VARCHAR> has to reach the page inside
    backticks (see docs/styles/local/BareAngleBrackets.yml). Specs that
    already contain markup, such as "Same as `x`", are left alone.
    """
    if "`" in spec:
        return spec
    return ", ".join("`%s`" % part.strip() for part in spec.split(",") if part.strip())


def render_syntax(doc, lang):
    return _fence(FENCE_QUERY, doc["syntax"])


def render_parameters(doc, lang):
    arguments = doc.get("arguments")
    if not arguments:
        return "None."
    lines = []
    for name, types, description in arguments:
        lines.append("- `%s` (%s): %s" % (name, _format_types(types), description))
    body = "\n".join(lines)
    # Prose that qualifies the arguments as a group rather than any single one,
    # e.g. "x and y must agree in data type". Kept verbatim so converting a
    # hand-written page cannot drop it.
    note = doc.get("parameters_note")
    if note:
        body = "%s\n\n%s" % (body, note)
    return body


def render_returns(doc, lang):
    returned = doc.get("returned_value")
    if not returned:
        return None
    types, description = returned
    return "%s\n\nType: %s" % (description, _format_types(types))


def render_usage(doc, lang):
    notes = doc.get("usage_notes")
    if not notes:
        return None
    return "\n".join("- %s" % note for note in notes)


def render_examples(doc, lang, captions=None):
    """Render the examples.

    ``captions`` overrides the payload captions positionally. Localized pages
    pass the captions already on the page: a caption is prose, so replacing a
    translated one with the English payload text would put English into the
    zh/ja docs. The query and the result table are language-neutral and are
    always regenerated.
    """
    examples = doc.get("examples")
    if not examples:
        return None
    chunks = []
    for index, (caption, query, result) in enumerate(examples):
        if captions is not None:
            caption = captions[index] if index < len(captions) else ""
        parts = []
        if caption:
            parts.append(caption)
        parts.append(_fence(FENCE_QUERY, query))
        if result:
            parts.append(_fence(FENCE_RESULT, result))
        chunks.append("\n\n".join(parts))
    return "\n\n".join(chunks)


def existing_captions(text):
    """Pull the caption preceding each example from a page's examples section.

    Handles both the hand-written shape (one fence per example, holding a
    client transcript) and the generated shape (a ```sql fence followed by a
    ```plaintext fence). Consecutive fences with no prose between them belong
    to the same example.
    """
    _, sections = split_sections(text)
    body = None
    for section_id, _, block_lines in sections:
        if section_id == "examples":
            body = block_lines[1:]
            break
    if body is None:
        return []

    captions = []
    pending = []
    in_fence = False
    just_closed = False
    for line in body:
        if _FENCE_RE.match(line):
            if in_fence:
                in_fence = False
                just_closed = True
            else:
                in_fence = True
                prose = "\n".join(pending).strip()
                if prose:
                    captions.append(prose)
                elif not just_closed:
                    captions.append("")
                pending = []
                just_closed = False
            continue
        if in_fence:
            continue
        if line.strip():
            pending.append(line)
            just_closed = False
    return captions


RENDERERS = {
    "syntax": render_syntax,
    "parameters": render_parameters,
    "returns": render_returns,
    "usage": render_usage,
    "examples": render_examples,
}


def render_section(section_id, doc, lang, captions=None):
    """Return the full marker-wrapped section, or None if there is nothing."""
    if section_id == "examples":
        body = render_examples(doc, lang, captions)
    else:
        body = RENDERERS[section_id](doc, lang)
    if body is None:
        return None
    heading = HEADINGS[lang][section_id]
    return "\n".join([
        MARKER_START % section_id,
        "## %s" % heading,
        "",
        body,
        "",
        MARKER_END % section_id,
    ])


# ---------------------------------------------------------------------------
# Markdown page model
# ---------------------------------------------------------------------------

_HEADING_RE = re.compile(r"^##\s+(.*?)\s*$")
_FENCE_RE = re.compile(r"^\s*(```+|~~~+)")


def split_sections(text):
    """Split a page into (preamble, [(section_id_or_None, heading, block)]).

    ``block`` keeps the heading line and everything up to the next level-2
    heading.

    Existing AUTOGENERATED markers are dropped here rather than carried
    through. A start marker sits *above* its heading, so keeping it would
    attach it to the preceding block and leave a stray copy behind every time
    the page is regenerated. Since every generated section is rewritten whole,
    the old markers hold nothing worth preserving.

    Fence-aware: a ``## `` line inside a code block is content, not a heading,
    and a marker-looking line inside a fence is left alone.
    """
    lines = text.split("\n")
    preamble = []
    sections = []
    current = None
    fence = None

    for line in lines:
        fence_match = _FENCE_RE.match(line)
        if fence_match:
            token = fence_match.group(1)[0] * 3
            if fence is None:
                fence = token
            elif line.strip().startswith(fence):
                fence = None

        if fence is None and MARKER_ANY.match(line.strip()):
            continue

        heading_match = None if fence else _HEADING_RE.match(line)
        if heading_match:
            if current is not None:
                sections.append(current)
            title = heading_match.group(1).strip()
            current = [_identify(title), title, [line]]
        elif current is None:
            preamble.append(line)
        else:
            current[2].append(line)

    if current is not None:
        sections.append(current)

    return preamble, [(sid, title, body) for sid, title, body in sections]


def _identify(title):
    """Map a heading title to a section id, or None if it is hand-written."""
    normalized = title.strip().strip(":： ").lower()
    for section_id, aliases in HEADING_ALIASES.items():
        if normalized in aliases:
            return section_id
    return None


def _block_text(block_lines):
    return "\n".join(block_lines).strip("\n")


def anchor(heading):
    """Approximate the id Docusaurus derives from a heading.

    Latin text is lowercased and spaced-hyphenated; CJK headings keep their
    characters, which is why the zh pages link to `#示例`.
    """
    slug = heading.strip().lower().replace(" ", "-")
    return re.sub(r"[^\w\-]", "", slug, flags=re.UNICODE)


def repair_anchors(text):
    """Repoint intra-page links that no longer resolve to a section heading.

    Several ja pages carry `[Examples](#examples)` in hand-written prose; once
    the heading is `## 例` that link dangles. Rather than tracking renames made
    during this run -- which would miss pages already in that state, and one ja
    page was already broken before any generation -- this works from whatever
    is on the page: a dangling anchor that names a section the page actually
    has is pointed at that section's current heading.
    """
    dangling = dangling_anchors(text)
    if not dangling:
        return text

    _, sections = split_sections(text)
    present = {}
    for section_id, title, _ in sections:
        if section_id is not None and section_id not in present:
            present[section_id] = anchor(title)

    for target in dangling:
        for section_id, aliases in HEADING_ALIASES.items():
            if section_id not in present:
                continue
            if any(anchor(alias) == target for alias in aliases):
                text = text.replace("(#%s)" % target, "(#%s)" % present[section_id])
                break
    return text


def dangling_anchors(text):
    """Return intra-page anchors with no matching heading in the same page."""
    headings = set()
    for line in text.split("\n"):
        match = re.match(r"^#{1,6}\s+(.*?)\s*$", line)
        if match:
            headings.add(anchor(match.group(1)))
    targets = re.findall(r"\]\(#([^)]+)\)", text)
    return sorted(set(t for t in targets if t not in headings))


def apply_sections(text, generated, lang):
    """Return the page with each generated section replaced or inserted.

    ``generated`` is an ordered mapping of section_id -> rendered block.
    Hand-written sections keep their position and content.
    """
    preamble, sections = split_sections(text)

    # A section can legitimately appear in the source under a heading we
    # recognize; replace the first occurrence and leave any later duplicate
    # alone rather than silently merging them.
    seen = set()
    rebuilt = []
    for section_id, title, block_lines in sections:
        if section_id in generated and section_id not in seen:
            seen.add(section_id)
            rebuilt.append((section_id, generated[section_id]))
        elif section_id is not None and section_id not in generated:
            # A section this language does not generate -- zh/ja argument and
            # return-value prose. Normalize only its heading so a localized
            # page cannot end up with `## 構文` sitting next to `## Parameters`;
            # the body stays with the translation workflow.
            canonical = HEADINGS[lang][section_id]
            body = _block_text(block_lines[1:]).strip("\n")
            rebuilt.append((section_id, "## %s\n\n%s" % (canonical, body) if body else "## %s" % canonical))
        else:
            rebuilt.append((section_id, _block_text(block_lines)))

    # Insert sections the page does not have yet, in canonical order.
    for section_id in SECTION_ORDER:
        if section_id not in generated or section_id in seen:
            continue
        successors = SECTION_ORDER[SECTION_ORDER.index(section_id) + 1:]

        position = None
        for index, (existing_id, _) in enumerate(rebuilt):
            if existing_id in successors:
                position = index
                break

        if position is None:
            # No later reference section exists. Land after the last section we
            # recognize rather than at the end of the page, so trailing
            # hand-written sections such as "References" or "keyword" stay last.
            last_known = None
            for index, (existing_id, _) in enumerate(rebuilt):
                if existing_id in SECTION_ORDER:
                    last_known = index
            position = len(rebuilt) if last_known is None else last_known + 1

        rebuilt.insert(position, (section_id, generated[section_id]))
        seen.add(section_id)

    head = "\n".join(preamble).rstrip("\n")
    body = "\n\n".join(block for _, block in rebuilt)
    return repair_anchors("%s\n\n%s\n" % (head, body))


# ---------------------------------------------------------------------------
# Driving
# ---------------------------------------------------------------------------


def page_path(name, doc, lang):
    return os.path.join(
        DOCS_ROOT, lang, "sql-reference", "sql-functions", doc["category"], "%s.md" % name
    )


def frontmatter_description(text):
    match = re.search(r"^description:\s*(.*?)\s*$", text, re.MULTILINE)
    if not match:
        return None
    return match.group(1).strip().strip('"').strip("'")


def generate_page(name, doc, lang, text):
    # English captions come from the payload; localized pages keep whatever
    # translated captions they already carry.
    captions = None if lang == "en" else existing_captions(text)

    generated = {}
    for section_id in GENERATED_SECTIONS[lang]:
        block = render_section(section_id, doc, lang, captions)
        if block is not None:
            generated[section_id] = block
    return apply_sections(text, generated, lang)


def untranslated_captions(name, doc, lang, text):
    """Examples on a localized page that have no caption to reuse.

    Reported rather than filled in: writing the English caption there would
    put English prose into the zh/ja docs.
    """
    if lang == "en":
        return 0
    have = len([c for c in existing_captions(text) if c])
    want = len([c for c, _, _ in doc.get("examples", ()) if c])
    return max(0, want - have)


def run(payload, languages, only, check, show_notes=False):
    problems = validate_payload(payload, declared_function_names())
    if problems:
        for problem in problems:
            sys.stderr.write("ERROR: %s\n" % problem)
        return 2

    changed = []
    notes = []
    missing = []

    for name in sorted(payload):
        if only and name not in only:
            continue
        doc = payload[name]
        for lang in languages:
            path = page_path(name, doc, lang)
            if not os.path.exists(path):
                missing.append(os.path.relpath(path, REPO_ROOT))
                continue

            with open(path, "r") as handle:
                original = handle.read()

            updated = generate_page(name, doc, lang, original)

            broken = dangling_anchors(updated)
            if broken:
                # Refuse to write a page whose own links do not resolve.
                sys.stderr.write(
                    "ERROR: %s: link(s) to a heading that does not exist: %s\n"
                    % (os.path.relpath(path, REPO_ROOT), ", ".join("#" + b for b in broken))
                )
                return 2

            if lang == "en":
                declared = frontmatter_description(original)
                if declared and declared != doc["description"]:
                    notes.append(
                        "%s: frontmatter description differs from the payload\n"
                        "    frontmatter: %s\n    payload:     %s"
                        % (os.path.relpath(path, REPO_ROOT), declared, doc["description"])
                    )
            else:
                short = untranslated_captions(name, doc, lang, original)
                if short:
                    notes.append(
                        "%s: %d example(s) have no translated caption; the English "
                        "payload has one. A translator needs to supply it."
                        % (os.path.relpath(path, REPO_ROOT), short)
                    )

            if updated != original:
                changed.append(os.path.relpath(path, REPO_ROOT))
                if not check:
                    with open(path, "w") as handle:
                        handle.write(updated)

    for path in missing:
        sys.stderr.write("WARNING: no page at %s\n" % path)
    # Notes are an advisory task list (translations to write, frontmatter to
    # reconcile), not check failures. In --check they would bury the real
    # message, so they are opt-in there.
    if show_notes:
        for note in notes:
            sys.stderr.write("NOTE: %s\n" % note)
    elif notes and not check:
        sys.stdout.write("%d advisory note(s); re-run with --notes to see them.\n" % len(notes))

    if check:
        if changed:
            sys.stderr.write(
                "\n%d page(s) are out of date with the payload in functions.py:\n" % len(changed)
            )
            for path in changed:
                sys.stderr.write("  %s\n" % path)
            sys.stderr.write("\nRun: python3 gensrc/script/gen_function_docs.py\n")
            return 1
        sys.stdout.write("All generated sections are up to date.\n")
        return 0

    for path in changed:
        sys.stdout.write("updated %s\n" % path)
    sys.stdout.write("%d page(s) updated.\n" % len(changed))
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if any page is out of date",
    )
    parser.add_argument(
        "--lang",
        action="append",
        choices=LANGUAGES,
        help="restrict to a language (repeatable; default all)",
    )
    parser.add_argument(
        "--notes",
        action="store_true",
        help="show advisory notes (missing translations, frontmatter drift)",
    )
    parser.add_argument(
        "--function",
        action="append",
        help="restrict to a function name (repeatable; default all)",
    )
    args = parser.parse_args(argv)

    payload = getattr(functions, "function_docs", {})
    if not payload:
        sys.stderr.write("ERROR: functions.py defines no function_docs payload\n")
        return 2

    return run(
        payload,
        tuple(args.lang) if args.lang else LANGUAGES,
        set(args.function) if args.function else None,
        args.check,
        args.notes,
    )


if __name__ == "__main__":
    sys.exit(main())
