// Copyright 2021-present StarRocks, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.starrocks.sql.ast;

import com.starrocks.sql.ast.expression.TypeDef;
import com.starrocks.sql.parser.NodePosition;
import com.starrocks.type.Type;

import java.util.List;

public class StructFieldDesc implements ParseNode {
    /**
     * Struct field description which is generated by SQL syntax parser
     * User can add a new struct field into a struct column or drop an exist struct field
     * Syntax:
     * name type (FIRST | AFTER fieldName)
     * note:
     * not support not null
     * not support default value
     * |fieldName| : new added field name or target drop field name
     * |nestedParentFieldNames| : the nested parent field names
     * |typeDef| : the type definition for new added field (null in drop field)
     * |fieldPos| : the field position for new added field (null in drop field)
     * <p>
     * Example:
     * c1 is a struct column and definiton is STRUCT<v1 INT, v2 STRUCT<v3, v4>>
     * 1. modify column c1 add field v2.v5 int after v1
     * |fieldName|: v5
     * |nestParentFieldNames|: {v2}
     * |typeDef|: type int
     * |fieldPos| : after v1
     * 2. modify column c1 drop field v2.v3
     * |fieldName| : v3
     * |nestedParentFieldNames|: {v2}
     * |typeDef|: null
     * |fieldPos|: null
     */
    private final String fieldName;
    private final List<String> nestedParentFieldNames;
    private final TypeDef typeDef;
    private final ColumnPosition fieldPos;

    public StructFieldDesc(String fieldName, List<String> nestedParentFieldNames, TypeDef typeDef, ColumnPosition fieldPos) {
        this.fieldName = fieldName;
        this.nestedParentFieldNames = nestedParentFieldNames;
        this.typeDef = typeDef;
        this.fieldPos = fieldPos;
    }

    @Override
    public NodePosition getPos() {
        return null;
    }

    public List<String> getNestedParentFieldNames() {
        return nestedParentFieldNames;
    }

    public String getFieldName() {
        return fieldName;
    }

    public Type getType() {
        return typeDef.getType();
    }

    public TypeDef getTypeDef() {
        return typeDef;
    }

    public ColumnPosition getFieldPos() {
        return fieldPos;
    }
}
