version: "3.9"
services:
  starrocks-fe:
    image: starrocks/fe-ubuntu:main
    hostname: starrocks-fe
    container_name: starrocks-fe
    command:
      /opt/starrocks/fe/bin/start_fe.sh
    ports:
      - 8030:8030
      - 9020:9020
      - 9030:9030
    # volumes:
    #   - ../../conf/fe.conf:/opt/starrocks/fe/conf/fe.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9030"]
      interval: 5s
      timeout: 5s
      retries: 30

  starrocks-be:
    image: starrocks/be-ubuntu:main
    command:
      - /bin/bash
      - -c
      - |
        sleep 15s; mysql --connect-timeout 2 -h starrocks-fe -P9030 -uroot -e "alter system add backend \"starrocks-be:9050\";"
        /opt/starrocks/be/bin/start_be.sh
    ports:
      - 8040:8040
    hostname: starrocks-be
    container_name: starrocks-be
    depends_on:
      - starrocks-fe
    # volumes:
    #   - ../../conf/be.conf:/opt/starrocks/be/conf/be.conf
