version: "3.3"
services:
  starrocks-fe:
    image: starrocks/fe-ubuntu:main
    hostname: starrocks-fe
    container_name: starrocks-fe
    command:
      /opt/starrocks/fe/bin/start_fe.sh
    ports:
      - 8030:8030
      - 9020:9020
      - 9030:9030
#    volumes:
#      - ../../conf/fe.conf:/opt/starrocks/fe/conf/fe.conf
#      - ./starrocks-fe/meta:/opt/starrocks/fe/meta


  starrocks-be:
    image: starrocks/be-ubuntu:main
    command:
      - /bin/bash
      - -c
      - |
        sleep 15s; mysql --connect-timeout 2 -h starrocks-fe -P9030 -uroot -e "alter system add backend \"starrocks-be:9050\";"
        /opt/starrocks/be/bin/start_be.sh
    ports:
      - 8040:8040
    hostname: starrocks-be
    container_name: starrocks-be
    depends_on:
      - starrocks-fe
#    Make sure to substitute path left of the ":" to a directory of the host.
#    volumes:
#      - ../../be/be.conf:/opt/starrocks/be/conf/be.conf
#      - ./starrocks-be/storage:/opt/starrocks/be/storage
