-- name: test_variant_comparable
SELECT
    CASE WHEN CAST(1 AS VARIANT) = CAST(1 AS VARIANT) THEN 'PASS' ELSE 'FAIL' END AS v_eq,
    CASE WHEN CAST(1 AS VARIANT) != CAST(2 AS VARIANT) THEN 'PASS' ELSE 'FAIL' END AS v_ne,
    CASE WHEN CAST(NULL AS VARIANT) IS NULL THEN 'PASS' ELSE 'FAIL' END AS v_is_null,
    CASE WHEN CAST(NULL AS VARIANT) IS NOT NULL THEN 'FAIL' ELSE 'PASS' END AS v_is_not_null,
    CASE WHEN CAST(NULL AS VARIANT) <=> CAST(NULL AS VARIANT) THEN 'PASS' ELSE 'FAIL' END AS v_null_safe_eq;
-- result:
PASS	PASS	PASS	PASS	PASS
-- !result
