Package: starrocks-fe
Version: 0.0.0
Section: database
Priority: optional
Architecture: amd64
Depends: openjdk-17-jre-headless | openjdk-17-jdk, bash, procps
Maintainer: sunghj1118 <sunghj1118@gmail.com>
Description: StarRocks Frontend (FE)
 StarRocks is a next-generation real-time analytical warehouse.
 This package contains the Frontend (FE) nodes responsible for 
 metadata management and query planning.
