FROM alpine:3.14

RUN set -eux && sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

RUN apk update \
    && apk upgrade  \
    && apk add --update openjdk11 tzdata curl unzip bash mysql-client procps vim  eudev-dev \
    && rm -rf /var/cache/apk/*
ENV JAVA_HOME=/usr/lib/jvm/default-jvm/
ENV STARROCKS_ROOT=/opt/starrocks  
USER root
RUN mkdir -p /opt/starrocks/fe/meta/
COPY /fe /opt/starrocks/fe/
Copy fe_entrypoint.sh fe_prestop.sh /opt/starrocks/ 
Workdir /opt/starrocks
