name: Docs Bug
description: Report a problem with documentation.
labels: docs/bug
title: "[Docs Bug]: " 
body:
- type: markdown
  attributes:
    value: |
      > This repository is for StarRocks DOCS ONLY. If you need assistance on StarRocks usage, [file an issue in StarRocks repository](https://github.com/StarRocks/starrocks/issues/new/choose).
- type: textarea
  attributes:
    label: Link to the Docs
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the Bug 
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Info
    description: |
      Screenshots or anything that will give us more context about the issue you are encountering!
  validations:
    required: false
