blank_issues_enabled: false
contact_links:
  - name: Need help or have a question?
    url: https://join.slack.com/t/starrocks/shared_invite/zt-z5zxqr0k-U5lrTVlgypRIV8RbnCIAzg
    about: Visit our slack channel.
