// Copyright 2021-present StarRocks, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "exec/paimon/paimon_delete_file_builder.h"

#include <gtest/gtest.h>

#include "base/testutil/assert.h"
#include "fs/fs.h"
#include "gen_cpp/PlanNodes_types.h"

namespace starrocks {

class PaimonDeleteFileBuilderTest : public testing::Test {
public:
    PaimonDeleteFileBuilderTest() = default;
    ~PaimonDeleteFileBuilderTest() override = default;
};

// v1 (BitmapDeletionVector): 1 deleted row
TEST_F(PaimonDeleteFileBuilderTest, TestDeletionVectorV1) {
    SkipRowsContextPtr skip_rows_ctx = std::make_shared<SkipRowsContext>();
    PaimonDeleteFileBuilder builder(FileSystem::Default(), skip_rows_ctx);

    TPaimonDeletionFile paimon_deletion_file;
    paimon_deletion_file.__set_path(
            "./be/test/exec/test_data/paimon_data/index-41b983cd-b835-450a-ad38-6ffee8ddbebd-0");
    paimon_deletion_file.__set_offset(1);
    paimon_deletion_file.__set_length(22);

    ASSERT_OK(builder.build(&paimon_deletion_file));
    ASSERT_EQ(1, skip_rows_ctx->deletion_bitmap->get_cardinality());
}

// v2 (Bitmap64DeletionVector): 2 deleted rows (row 3 and row 7)
// Test data generated by Paimon's Bitmap64DeletionVector.serializeTo()
TEST_F(PaimonDeleteFileBuilderTest, TestDeletionVectorV2) {
    SkipRowsContextPtr skip_rows_ctx = std::make_shared<SkipRowsContext>();
    PaimonDeleteFileBuilder builder(FileSystem::Default(), skip_rows_ctx);

    TPaimonDeletionFile paimon_deletion_file;
    paimon_deletion_file.__set_path("./be/test/exec/test_data/paimon_data/index-dv-v2-test");
    paimon_deletion_file.__set_offset(1);
    paimon_deletion_file.__set_length(44);

    ASSERT_OK(builder.build(&paimon_deletion_file));
    ASSERT_EQ(2, skip_rows_ctx->deletion_bitmap->get_cardinality());

    std::vector<uint64_t> deleted_rows(skip_rows_ctx->deletion_bitmap->get_cardinality());
    skip_rows_ctx->deletion_bitmap->to_array(deleted_rows);
    ASSERT_EQ(2, deleted_rows.size());
    ASSERT_EQ(3, deleted_rows[0]);
    ASSERT_EQ(7, deleted_rows[1]);
}

} // namespace starrocks
