services:

  gotenberg:
    image: gotenberg/gotenberg
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:3000/health"]

  docusaurus:
    build: ../
    environment:
      - DISABLE_VERSIONING='true'
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    ports:
        - 3000:3000
    volumes:
      - ../../PDFoutput:/app/PDFoutput
      - ../../en:/app/docusaurus/docs
      - ../../zh:/app/docusaurus/i18n/zh/docusaurus-plugin-content-docs/current
    working_dir: /app/docusaurus
    healthcheck:
      test: curl --fail http://docusaurus:3000 || exit 1
      interval: 10s
      retries: 20
      start_period: 140s
      timeout: 5s
    entrypoint: >
      /bin/bash -c "
      cd PDF && yarn install &&
      python3 -m venv .venv &&
      source .venv/bin/activate &&
      pip3 install pdfcombine &&
      cd /app/docusaurus &&
      npm install -g docusaurus-prince-pdf@1.2.1 &&
      yarn install &&
      yarn build &&
      yarn serve -p 3000 -h 0.0.0.0 &&
      tail -f /dev/null
      "

