name: markdownlint

on: [push, pull_request]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: markdownlint-cli
      uses: articulate/actions-markdownlint@v1
      with:
        config: .markdownlint.yaml
<<<<<<< HEAD
        ignore: assets
=======
        ignore: assets
    - name: Check Markdown links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: 'mlc_config.json'
        folder-path: '.'
>>>>>>> b42eff7ae3 ([Doc] Add meaning of 0 for variables (#53714))
