-- DDL for catalog_sales_flat Table
CREATE TABLE catalog_sales_flat (
    -- Catalog Sales Columns
    cs_sold_time_sk BIGINT, 
    cs_ship_date DATE, 
    cs_bill_customer_sk BIGINT, 
    cs_bill_cdemo_sk BIGINT, 
    cs_bill_hdemo_sk BIGINT, 
    cs_bill_addr_sk BIGINT, 
    cs_ship_customer_sk BIGINT, 
    cs_ship_cdemo_sk BIGINT, 
    cs_ship_hdemo_sk BIGINT, 
    cs_ship_addr_sk BIGINT, 
    cs_call_center_sk BIGINT, 
    cs_catalog_page_sk BIGINT, 
    cs_ship_mode_sk BIGINT, 
    cs_warehouse_sk BIGINT, 
    cs_item_sk BIGINT, 
    cs_promo_sk BIGINT, 
    cs_order_number BIGINT, 
    cs_quantity INT, 
    cs_wholesale_cost DECIMAL(7,2), 
    cs_list_price DECIMAL(7,2), 
    cs_sales_price DECIMAL(7,2), 
    cs_ext_discount_amt DECIMAL(7,2), 
    cs_ext_sales_price DECIMAL(7,2), 
    cs_ext_wholesale_cost DECIMAL(7,2), 
    cs_ext_list_price DECIMAL(7,2), 
    cs_ext_tax DECIMAL(7,2), 
    cs_coupon_amt DECIMAL(7,2), 
    cs_ext_ship_cost DECIMAL(7,2), 
    cs_net_paid DECIMAL(7,2), 
    cs_net_paid_inc_tax DECIMAL(7,2), 
    cs_net_paid_inc_ship DECIMAL(7,2), 
    cs_net_paid_inc_ship_tax DECIMAL(7,2), 
    cs_net_profit DECIMAL(7,2), 
    --
    bill_ca_address_sk BIGINT, 
    bill_ca_street_number VARCHAR(255), 
    bill_ca_street_name VARCHAR(255), 
    bill_ca_street_type VARCHAR(255), 
    bill_ca_suite_number VARCHAR(255), 
    bill_ca_city VARCHAR(255), 
    bill_ca_county VARCHAR(255), 
    bill_ca_state VARCHAR(255), 
    bill_ca_zip VARCHAR(255), 
    bill_ca_country VARCHAR(255), 
    bill_ca_gmt_offset DECIMAL(5,2), 
    bill_ca_location_type VARCHAR(255), 
    bill_cd_demo_sk BIGINT, 
    bill_cd_gender VARCHAR(10), 
    bill_cd_marital_status VARCHAR(10), 
    bill_cd_education_status VARCHAR(255), 
    bill_cd_purchase_estimate INT, 
    bill_cd_credit_rating VARCHAR(50), 
    bill_cd_dep_count INT, 
    bill_cd_dep_employed_count INT, 
    bill_cd_dep_college_count INT, 
    bill_hd_demo_sk BIGINT, 
    bill_hd_income_band_sk BIGINT, 
    bill_hd_buy_potential VARCHAR(50), 
    bill_hd_dep_count INT, 
    bill_hd_vehicle_count INT, 
    bill_ib_income_band_sk BIGINT, 
    bill_ib_lower_bound INT, 
    bill_ib_upper_bound INT,
    ship_ca_address_sk BIGINT, 
    ship_ca_street_number VARCHAR(255), 
    ship_ca_street_name VARCHAR(255), 
    ship_ca_street_type VARCHAR(255), 
    ship_ca_suite_number VARCHAR(255), 
    ship_ca_city VARCHAR(255), 
    ship_ca_county VARCHAR(255), 
    ship_ca_state VARCHAR(255), 
    ship_ca_zip VARCHAR(255), 
    ship_ca_country VARCHAR(255), 
    ship_ca_gmt_offset DECIMAL(5,2), 
    ship_ca_location_type VARCHAR(255), 
    ship_cd_demo_sk BIGINT, 
    ship_cd_gender VARCHAR(10), 
    ship_cd_marital_status VARCHAR(10), 
    ship_cd_education_status VARCHAR(255), 
    ship_cd_purchase_estimate INT, 
    ship_cd_credit_rating VARCHAR(50), 
    ship_cd_dep_count INT, 
    ship_cd_dep_employed_count INT, 
    ship_cd_dep_college_count INT, 
    ship_hd_demo_sk BIGINT, 
    ship_hd_income_band_sk BIGINT, 
    ship_hd_buy_potential VARCHAR(50), 
    ship_hd_dep_count INT, 
    ship_hd_vehicle_count INT, 
    ship_ib_income_band_sk BIGINT, 
    ship_ib_lower_bound INT, 
    ship_ib_upper_bound INT,

    -- Catalog Page Columns
    cp_catalog_page_sk BIGINT, 
    cp_catalog_page_id VARCHAR(255), 
    cp_start_date DATE, 
    cp_end_date DATE, 
    cp_department VARCHAR(255), 
    cp_catalog_number INT, 
    cp_catalog_page_number INT,

    -- Call Center Columns
    cc_call_center_sk BIGINT, 
    cc_call_center_id VARCHAR(255), 
    cc_rec_start_date DATE, 
    cc_rec_end_date DATE, 
    cc_closed_date_sk BIGINT, 
    cc_open_date_sk BIGINT, 
    cc_name VARCHAR(255), 
    cc_class VARCHAR(255), 
    cc_employees INT, 
    cc_sq_ft INT, 
    cc_hours VARCHAR(255), 
    cc_manager VARCHAR(255), 
    cc_mkt_id INT, 
    cc_mkt_class VARCHAR(255), 
    cc_mkt_desc VARCHAR(255), 
    cc_market_manager VARCHAR(255), 
    cc_division INT, 
    cc_division_name VARCHAR(255), 
    cc_company INT, 
    cc_company_name VARCHAR(255), 
    cc_street_number VARCHAR(255), 
    cc_street_name VARCHAR(255), 
    cc_street_type VARCHAR(255), 
    cc_suite_number VARCHAR(255), 
    cc_city VARCHAR(255), 
    cc_county VARCHAR(255), 
    cc_state VARCHAR(255), 
    cc_zip VARCHAR(255), 
    cc_country VARCHAR(255), 
    cc_gmt_offset DECIMAL(5,2), 
    cc_tax_percentage DECIMAL(5,2),

    -- Ship Mode Columns
    sm_ship_mode_sk BIGINT, 
    sm_ship_mode_id VARCHAR(255), 
    sm_type VARCHAR(255), 
    sm_code VARCHAR(255), 
    sm_carrier VARCHAR(255), 
    sm_contract VARCHAR(255),

    -- Promotion Columns
    p_promo_sk BIGINT, 
    p_promo_id VARCHAR(255), 
    p_start_date DATE, 
    p_end_date DATE, 
    p_item_sk BIGINT, 
    p_cost DECIMAL(15,2), 
    p_response_target INT, 
    p_promo_name VARCHAR(255), 
    p_channel_dmail VARCHAR(255), 
    p_channel_email VARCHAR(255), 
    p_channel_catalog VARCHAR(255), 
    p_channel_tv VARCHAR(255), 
    p_channel_radio VARCHAR(255), 
    p_channel_press VARCHAR(255), 
    p_channel_event VARCHAR(255), 
    p_channel_demo VARCHAR(255), 
    p_channel_details VARCHAR(255), 
    p_purpose VARCHAR(255), 
    p_discount_active VARCHAR(255),

    -- Constructed Sold Datetime Column
    sold_datetime DATETIME,
    cs_sold_date DATE
) PARTITION BY(cs_sold_date)

PROPERTIES (
  "replication_num" = "1"
);
