-- DDL for store_sales_flat Table
CREATE TABLE store_sales_flat (
    -- Store Sales Columns
    ss_sold_date_sk BIGINT, 
    ss_sold_time_sk BIGINT, 
    ss_item_sk BIGINT, 
    ss_customer_sk BIGINT, 
    ss_cdemo_sk BIGINT, 
    ss_hdemo_sk BIGINT, 
    ss_addr_sk BIGINT, 
    ss_store_sk BIGINT, 
    ss_promo_sk BIGINT, 
    ss_ticket_number BIGINT, 
    ss_quantity INT, 
    ss_wholesale_cost DECIMAL(7,2), 
    ss_list_price DECIMAL(7,2), 
    ss_sales_price DECIMAL(7,2), 
    ss_ext_discount_amt DECIMAL(7,2), 
    ss_ext_sales_price DECIMAL(7,2), 
    ss_ext_wholesale_cost DECIMAL(7,2), 
    ss_ext_list_price DECIMAL(7,2), 
    ss_ext_tax DECIMAL(7,2), 
    ss_coupon_amt DECIMAL(7,2), 
    ss_net_paid DECIMAL(7,2), 
    ss_net_paid_inc_tax DECIMAL(7,2), 
    ss_net_profit DECIMAL(7,2), 

    --
        -- Customer Address Columns
    ca_address_sk BIGINT, 
    ca_street_number VARCHAR(255), 
    ca_street_name VARCHAR(255), 
    ca_street_type VARCHAR(255), 
    ca_suite_number VARCHAR(255), 
    ca_city VARCHAR(255), 
    ca_county VARCHAR(255), 
    ca_state VARCHAR(255), 
    ca_zip VARCHAR(255), 
    ca_country VARCHAR(255), 
    ca_gmt_offset DECIMAL(5,2), 
    ca_location_type VARCHAR(255), 

    -- Customer Demographics Columns
    cd_demo_sk BIGINT, 
    cd_gender VARCHAR(10), 
    cd_marital_status VARCHAR(10), 
    cd_education_status VARCHAR(255), 
    cd_purchase_estimate INT, 
    cd_credit_rating VARCHAR(50), 
    cd_dep_count INT, 
    cd_dep_employed_count INT, 
    cd_dep_college_count INT, 

    -- Household Demographics Columns
    hd_demo_sk BIGINT, 
    hd_income_band_sk BIGINT, 
    hd_buy_potential VARCHAR(50), 
    hd_dep_count INT, 
    hd_vehicle_count INT, 

    -- Income Band Columns
    ib_income_band_sk BIGINT, 
    ib_lower_bound INT, 
    ib_upper_bound INT,

    -- Store Columns
    s_store_sk BIGINT, 
    s_store_id VARCHAR(255), 
    s_rec_start_date DATE, 
    s_rec_end_date DATE, 
    s_closed_date_sk BIGINT, 
    s_store_name VARCHAR(255), 
    s_number_employees INT, 
    s_floor_space INT, 
    s_hours VARCHAR(255), 
    s_manager VARCHAR(255), 
    s_market_id INT, 
    s_geography_class VARCHAR(255), 
    s_market_desc VARCHAR(255), 
    s_market_manager VARCHAR(255), 
    s_division_id INT, 
    s_division_name VARCHAR(255), 
    s_company_id INT, 
    s_company_name VARCHAR(255), 
    s_street_number VARCHAR(255), 
    s_street_name VARCHAR(255), 
    s_street_type VARCHAR(255), 
    s_suite_number VARCHAR(255), 
    s_city VARCHAR(255), 
    s_county VARCHAR(255), 
    s_state VARCHAR(255), 
    s_zip VARCHAR(255), 
    s_country VARCHAR(255), 
    s_gmt_offset DECIMAL(5,2), 
    s_tax_percentage DECIMAL(5,2), 

    -- Promotion Columns
    p_promo_sk BIGINT, 
    p_promo_id VARCHAR(255), 
    p_start_date DATE, 
    p_end_date DATE, 
    p_item_sk BIGINT, 
    p_cost DECIMAL(15,2), 
    p_response_target INT, 
    p_promo_name VARCHAR(255), 
    p_channel_dmail VARCHAR(255), 
    p_channel_email VARCHAR(255), 
    p_channel_catalog VARCHAR(255), 
    p_channel_tv VARCHAR(255), 
    p_channel_radio VARCHAR(255), 
    p_channel_press VARCHAR(255), 
    p_channel_event VARCHAR(255), 
    p_channel_demo VARCHAR(255), 
    p_channel_details VARCHAR(255), 
    p_purpose VARCHAR(255), 
    p_discount_active VARCHAR(255), 

    -- Constructed Sold Datetime Column (Using DATETIME Type)
    sold_datetime DATETIME,
    ss_sold_date DATE
) PARTITION BY(ss_sold_date)
PROPERTIES (
  "replication_num" = "1"
);
