-- DDL for web_returns_flat Table
CREATE TABLE web_returns_flat (
    -- Web Returns Columns
    wr_returned_time_sk BIGINT, 
    wr_item_sk BIGINT, 
    wr_refunded_customer_sk BIGINT, 
    wr_refunded_cdemo_sk BIGINT, 
    wr_refunded_hdemo_sk BIGINT, 
    wr_refunded_addr_sk BIGINT, 
    wr_returning_customer_sk BIGINT, 
    wr_returning_cdemo_sk BIGINT, 
    wr_returning_hdemo_sk BIGINT, 
    wr_returning_addr_sk BIGINT, 
    wr_web_page_sk BIGINT, 
    wr_reason_sk BIGINT, 
    wr_order_number BIGINT, 
    wr_return_quantity INT, 
    wr_return_amt DECIMAL(7,2), 
    wr_return_tax DECIMAL(7,2), 
    wr_return_amt_inc_tax DECIMAL(7,2), 
    wr_fee DECIMAL(7,2), 
    wr_return_ship_cost DECIMAL(7,2), 
    wr_refunded_cash DECIMAL(7,2), 
    wr_reversed_charge DECIMAL(7,2), 
    wr_account_credit DECIMAL(7,2), 
    wr_net_loss DECIMAL(7,2), 
    -- 
    returning_ca_address_sk BIGINT, 
    returning_ca_street_number VARCHAR(255), 
    returning_ca_street_name VARCHAR(255), 
    returning_ca_street_type VARCHAR(255), 
    returning_ca_suite_number VARCHAR(255), 
    returning_ca_city VARCHAR(255), 
    returning_ca_county VARCHAR(255), 
    returning_ca_state VARCHAR(255), 
    returning_ca_zip VARCHAR(255), 
    returning_ca_country VARCHAR(255), 
    returning_ca_gmt_offset DECIMAL(5,2), 
    returning_ca_location_type VARCHAR(255), 
    returning_cd_demo_sk BIGINT, 
    returning_cd_gender VARCHAR(10), 
    returning_cd_marital_status VARCHAR(10), 
    returning_cd_education_status VARCHAR(255), 
    returning_cd_purchase_estimate INT, 
    returning_cd_credit_rating VARCHAR(50), 
    returning_cd_dep_count INT, 
    returning_cd_dep_employed_count INT, 
    returning_cd_dep_college_count INT, 
    returning_hd_demo_sk BIGINT, 
    returning_hd_income_band_sk BIGINT, 
    returning_hd_buy_potential VARCHAR(50), 
    returning_hd_dep_count INT, 
    returning_hd_vehicle_count INT, 
    returning_ib_income_band_sk BIGINT, 
    returning_ib_lower_bound INT, 
    returning_ib_upper_bound INT,
    refunded_ca_address_sk BIGINT, 
    refunded_ca_street_number VARCHAR(255), 
    refunded_ca_street_name VARCHAR(255), 
    refunded_ca_street_type VARCHAR(255), 
    refunded_ca_suite_number VARCHAR(255), 
    refunded_ca_city VARCHAR(255), 
    refunded_ca_county VARCHAR(255), 
    refunded_ca_state VARCHAR(255), 
    refunded_ca_zip VARCHAR(255), 
    refunded_ca_country VARCHAR(255), 
    refunded_ca_gmt_offset DECIMAL(5,2), 
    refunded_ca_location_type VARCHAR(255), 
    refunded_cd_demo_sk BIGINT, 
    refunded_cd_gender VARCHAR(10), 
    refunded_cd_marital_status VARCHAR(10), 
    refunded_cd_education_status VARCHAR(255), 
    refunded_cd_purchase_estimate INT, 
    refunded_cd_credit_rating VARCHAR(50), 
    refunded_cd_dep_count INT, 
    refunded_cd_dep_employed_count INT, 
    refunded_cd_dep_college_count INT, 
    refunded_hd_demo_sk BIGINT, 
    refunded_hd_income_band_sk BIGINT, 
    refunded_hd_buy_potential VARCHAR(50), 
    refunded_hd_dep_count INT, 
    refunded_hd_vehicle_count INT, 
    refunded_ib_income_band_sk BIGINT, 
    refunded_ib_lower_bound INT, 
    refunded_ib_upper_bound INT,
    -- Web Page Columns
    wp_web_page_sk BIGINT, 
    wp_web_page_id VARCHAR(255), 
    wp_creation_date DATE, 
    wp_access_date DATE, 
    wp_autogen_flag CHAR(1), 
    wp_customer_sk BIGINT, 
    wp_url VARCHAR(255), 
    wp_type VARCHAR(255), 
    wp_char_count INT, 
    wp_link_count INT, 
    wp_image_count INT, 
    wp_max_ad_count INT,

    -- Reason Columns
    r_reason_sk BIGINT, 
    r_reason_id VARCHAR(255), 
    r_reason_desc VARCHAR(255),

    -- Constructed Returned Datetime Column
    returned_datetime DATETIME,
    wr_returned_date DATE
) PARTITION BY(wr_returned_date)

PROPERTIES (
  "replication_num" = "1"
);
