-- DDL for web_sales_flat Table
CREATE TABLE web_sales_flat (
    -- Web Sales Columns
    ws_sold_time_sk BIGINT, 
    ws_ship_date_sk BIGINT, 
    ws_item_sk BIGINT, 
    ws_bill_customer_sk BIGINT, 
    ws_bill_cdemo_sk BIGINT, 
    ws_bill_hdemo_sk BIGINT, 
    ws_bill_addr_sk BIGINT, 
    ws_ship_customer_sk BIGINT, 
    ws_ship_cdemo_sk BIGINT, 
    ws_ship_hdemo_sk BIGINT, 
    ws_ship_addr_sk BIGINT, 
    ws_web_page_sk BIGINT, 
    ws_web_site_sk BIGINT, 
    ws_ship_mode_sk BIGINT, 
    ws_warehouse_sk BIGINT, 
    ws_promo_sk BIGINT, 
    ws_order_number BIGINT, 
    ws_quantity INT, 
    ws_wholesale_cost DECIMAL(7,2), 
    ws_list_price DECIMAL(7,2), 
    ws_sales_price DECIMAL(7,2), 
    ws_ext_discount_amt DECIMAL(7,2), 
    ws_ext_sales_price DECIMAL(7,2), 
    ws_ext_wholesale_cost DECIMAL(7,2), 
    ws_ext_list_price DECIMAL(7,2), 
    ws_ext_tax DECIMAL(7,2), 
    ws_coupon_amt DECIMAL(7,2), 
    ws_ext_ship_cost DECIMAL(7,2), 
    ws_net_paid DECIMAL(7,2), 
    ws_net_paid_inc_tax DECIMAL(7,2), 
    ws_net_paid_inc_ship DECIMAL(7,2), 
    ws_net_paid_inc_ship_tax DECIMAL(7,2), 
    ws_net_profit DECIMAL(7,2), 
    --
    bill_ca_address_sk BIGINT, 
    bill_ca_street_number VARCHAR(255), 
    bill_ca_street_name VARCHAR(255), 
    bill_ca_street_type VARCHAR(255), 
    bill_ca_suite_number VARCHAR(255), 
    bill_ca_city VARCHAR(255), 
    bill_ca_county VARCHAR(255), 
    bill_ca_state VARCHAR(255), 
    bill_ca_zip VARCHAR(255), 
    bill_ca_country VARCHAR(255), 
    bill_ca_gmt_offset DECIMAL(5,2), 
    bill_ca_location_type VARCHAR(255), 
    bill_cd_demo_sk BIGINT, 
    bill_cd_gender VARCHAR(10), 
    bill_cd_marital_status VARCHAR(10), 
    bill_cd_education_status VARCHAR(255), 
    bill_cd_purchase_estimate INT, 
    bill_cd_credit_rating VARCHAR(50), 
    bill_cd_dep_count INT, 
    bill_cd_dep_employed_count INT, 
    bill_cd_dep_college_count INT, 
    bill_hd_demo_sk BIGINT, 
    bill_hd_income_band_sk BIGINT, 
    bill_hd_buy_potential VARCHAR(50), 
    bill_hd_dep_count INT, 
    bill_hd_vehicle_count INT, 
    bill_ib_income_band_sk BIGINT, 
    bill_ib_lower_bound INT, 
    bill_ib_upper_bound INT,
    ship_ca_address_sk BIGINT, 
    ship_ca_street_number VARCHAR(255), 
    ship_ca_street_name VARCHAR(255), 
    ship_ca_street_type VARCHAR(255), 
    ship_ca_suite_number VARCHAR(255), 
    ship_ca_city VARCHAR(255), 
    ship_ca_county VARCHAR(255), 
    ship_ca_state VARCHAR(255), 
    ship_ca_zip VARCHAR(255), 
    ship_ca_country VARCHAR(255), 
    ship_ca_gmt_offset DECIMAL(5,2), 
    ship_ca_location_type VARCHAR(255), 
    ship_cd_demo_sk BIGINT, 
    ship_cd_gender VARCHAR(10), 
    ship_cd_marital_status VARCHAR(10), 
    ship_cd_education_status VARCHAR(255), 
    ship_cd_purchase_estimate INT, 
    ship_cd_credit_rating VARCHAR(50), 
    ship_cd_dep_count INT, 
    ship_cd_dep_employed_count INT, 
    ship_cd_dep_college_count INT, 
    ship_hd_demo_sk BIGINT, 
    ship_hd_income_band_sk BIGINT, 
    ship_hd_buy_potential VARCHAR(50), 
    ship_hd_dep_count INT, 
    ship_hd_vehicle_count INT, 
    ship_ib_income_band_sk BIGINT, 
    ship_ib_lower_bound INT, 
    ship_ib_upper_bound INT,

    -- Web Page Columns
    wp_web_page_sk BIGINT, 
    wp_web_page_id VARCHAR(255), 
    wp_creation_date DATE, 
    wp_access_date DATE, 
    wp_autogen_flag CHAR(1), 
    wp_customer_sk BIGINT, 
    wp_url VARCHAR(255), 
    wp_type VARCHAR(255), 
    wp_char_count INT, 
    wp_link_count INT, 
    wp_image_count INT, 
    wp_max_ad_count INT,

    -- Web Site Columns
    web_site_sk BIGINT, 
    web_site_id VARCHAR(255), 
    web_rec_start_date DATE, 
    web_rec_end_date DATE, 
    web_name VARCHAR(255), 
    web_open_date DATE, 
    web_close_date DATE, 
    web_class VARCHAR(255), 
    web_manager VARCHAR(255), 
    web_mkt_id INT, 
    web_mkt_class VARCHAR(255), 
    web_mkt_desc VARCHAR(255), 
    web_market_manager VARCHAR(255), 
    web_company_id INT, 
    web_company_name VARCHAR(255), 

    -- Ship Mode Columns
    sm_ship_mode_sk BIGINT, 
    sm_ship_mode_id VARCHAR(255), 
    sm_type VARCHAR(255), 
    sm_code VARCHAR(255), 
    sm_carrier VARCHAR(255), 
    sm_contract VARCHAR(255), 

    -- Promotion Columns
    p_promo_sk BIGINT, 
    p_promo_id VARCHAR(255), 
    p_start_date DATE, 
    p_end_date DATE, 
    p_item_sk BIGINT, 
    p_cost DECIMAL(15,2), 
    p_response_target INT, 
    p_promo_name VARCHAR(255), 
    p_channel_dmail VARCHAR(255), 
    p_channel_email VARCHAR(255), 
    p_channel_catalog VARCHAR(255), 
    p_channel_tv VARCHAR(255), 
    p_channel_radio VARCHAR(255), 
    p_channel_press VARCHAR(255), 
    p_channel_event VARCHAR(255), 
    p_channel_demo VARCHAR(255), 
    p_channel_details VARCHAR(255), 
    p_purpose VARCHAR(255), 
    p_discount_active VARCHAR(255),

    -- Constructed Sold Datetime Column
    sold_datetime DATETIME,
    ws_sold_date DATE
) PARTITION BY(ws_sold_date)

PROPERTIES (
  "replication_num" = "1"
);
