#!/usr/bin/env python3
"""Reject hand edits inside AUTOGENERATED regions of the SQL function docs.

Generated sections are fenced by markers::

    {/* AUTOGENERATED_START:syntax */}
    ## Syntax
    ...
    {/* AUTOGENERATED_END:syntax */}

Content inside them comes from the ``function_docs`` payload in
``gensrc/script/functions.py``. Editing the page instead of the payload means
the next regeneration silently reverts the edit, so this check fails the build
and points at the payload.

This is adapted from ClickHouse's ci/jobs/scripts/docs/check_autogenerated_regions.py,
with two deliberate differences:

* ClickHouse compares marked regions between two git revisions, because their
  generator needs a running server and so cannot run in a PR job. StarRocks'
  generator reads a Python table and needs nothing, so this check simply runs
  it and asserts that nothing changes. That catches strictly more: a hand edit
  inside a region *and* a payload change that was never regenerated, with no
  need for an "intentional regeneration" label.
* ClickHouse excludes localized doc trees, treating them as static
  translations. Here zh and ja carry generated regions too, so all three
  languages are checked.

Usage::

    python3 docs/scripts/check_autogenerated_regions.py
    python3 docs/scripts/check_autogenerated_regions.py --base-ref origin/main
"""

import argparse
import os
import re
import subprocess
import sys

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
GENERATOR = os.path.join(REPO_ROOT, "gensrc", "script", "gen_function_docs.py")

MARKER_RE = re.compile(
    r"^(?:\{/\*\s*AUTOGENERATED_(START|END):([a-z_]+)\s*\*/\}"
    r"|<!--\s*AUTOGENERATED_(START|END):([a-z_]+)\s*-->)$",
    re.MULTILINE,
)
HTML_MARKER_RE = re.compile(r"<!--\s*AUTOGENERATED_(?:START|END):[a-z_]+\s*-->")


def run_generator_check():
    """Return (ok, output) from `gen_function_docs.py --check`."""
    result = subprocess.run(
        [sys.executable, GENERATOR, "--check"],
        cwd=os.path.dirname(GENERATOR),
        capture_output=True,
        text=True,
    )
    return result.returncode == 0, (result.stdout + result.stderr).strip()


def changed_docs(base_ref):
    """Docs paths changed since base_ref, or None if not scoping to a diff."""
    if not base_ref:
        return None
    result = subprocess.run(
        ["git", "diff", "--name-only", "--diff-filter=d", base_ref, "--", "docs/"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    if result.returncode:
        sys.stderr.write("warning: cannot diff against %s; checking all pages\n" % base_ref)
        return None
    return [p for p in result.stdout.split() if p.endswith(".md")]


def iter_doc_files(paths):
    if paths is not None:
        for path in paths:
            full = os.path.join(REPO_ROOT, path)
            if os.path.exists(full):
                yield path, full
        return
    root = os.path.join(REPO_ROOT, "docs")
    for dirpath, _, filenames in os.walk(root):
        for filename in filenames:
            if filename.endswith(".md"):
                full = os.path.join(dirpath, filename)
                yield os.path.relpath(full, REPO_ROOT), full


def scan_markers(paths):
    """Find unbalanced regions and markers written as HTML comments."""
    unbalanced = []
    html_comments = []
    for relative, full in iter_doc_files(paths):
        with open(full, "r") as handle:
            content = handle.read()
        if "AUTOGENERATED_" not in content:
            continue

        if HTML_MARKER_RE.search(content):
            # Docusaurus parses these pages as MDX, where HTML comments are
            # invalid; docs/styles/local/HTMLComment.yml flags them as errors.
            html_comments.append(relative)

        depth = {}
        for match in MARKER_RE.finditer(content):
            kind = match.group(1) or match.group(3)
            section = match.group(2) or match.group(4)
            depth[section] = depth.get(section, 0) + (1 if kind == "START" else -1)
        for section, value in sorted(depth.items()):
            if value != 0:
                unbalanced.append("%s: region '%s' is not balanced" % (relative, section))
    return unbalanced, html_comments


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--base-ref",
        help="only scan docs changed since this revision (marker scan only; "
        "the generator check always covers every documented function)",
    )
    args = parser.parse_args(argv)

    failures = []

    ok, output = run_generator_check()
    if not ok:
        failures.append(
            "Generated sections do not match the payload in gensrc/script/functions.py.\n"
            "%s\n"
            "If you edited a doc page directly, move the change into the\n"
            "function_docs payload instead. Then run:\n"
            "    python3 gensrc/script/gen_function_docs.py" % output
        )

    unbalanced, html_comments = scan_markers(changed_docs(args.base_ref))
    if unbalanced:
        failures.append("Unbalanced AUTOGENERATED markers:\n  " + "\n  ".join(unbalanced))
    if html_comments:
        failures.append(
            "AUTOGENERATED markers written as HTML comments (use {/* ... */}):\n  "
            + "\n  ".join(html_comments)
        )

    if failures:
        sys.stderr.write("\n\n".join(failures) + "\n")
        return 1

    print("OK: generated regions match the payload and all markers are balanced.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
