// Copyright 2021-present StarRocks, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "formats/paimon/paimon_delete_file_builder.h"

#include <gtest/gtest.h>

#include <cstdio>
#include <fstream>
#include <limits>

#include "base/testutil/assert.h"
#include "fs/fs.h"
#include "gen_cpp/PlanNodes_types.h"

namespace starrocks::formats {

class PaimonDeleteFileBuilderTest : public testing::Test {
public:
    PaimonDeleteFileBuilderTest() = default;
    ~PaimonDeleteFileBuilderTest() override = default;
};

namespace {

constexpr int32_t kMagicV1 = 1581511376;
constexpr int32_t kMagicV2 = 1681511377;

std::string be32(int32_t v) {
    char b[4];
    b[0] = static_cast<char>((v >> 24) & 0xff);
    b[1] = static_cast<char>((v >> 16) & 0xff);
    b[2] = static_cast<char>((v >> 8) & 0xff);
    b[3] = static_cast<char>(v & 0xff);
    return std::string(b, 4);
}

std::string le32(int32_t v) {
    char b[4];
    b[0] = static_cast<char>(v & 0xff);
    b[1] = static_cast<char>((v >> 8) & 0xff);
    b[2] = static_cast<char>((v >> 16) & 0xff);
    b[3] = static_cast<char>((v >> 24) & 0xff);
    return std::string(b, 4);
}

void write_tmp_file(const std::string& path, const std::string& bytes) {
    std::ofstream out(path, std::ios::binary | std::ios::trunc);
    out.write(bytes.data(), bytes.size());
}

} // namespace

// v1 (BitmapDeletionVector): 1 deleted row
TEST_F(PaimonDeleteFileBuilderTest, TestDeletionVectorV1) {
    PaimonDeleteFileBuilder builder(FileSystem::Default());

    TPaimonDeletionFile paimon_deletion_file;
    paimon_deletion_file.__set_path("./be/test/formats/paimon/test_data/index-41b983cd-b835-450a-ad38-6ffee8ddbebd-0");
    paimon_deletion_file.__set_offset(1);
    paimon_deletion_file.__set_length(22);

    ASSIGN_OR_ABORT(auto deletion_bitmap, builder.build(paimon_deletion_file));
    ASSERT_EQ(1, deletion_bitmap->get_cardinality());
}

// v2 (Bitmap64DeletionVector): 2 deleted rows (row 3 and row 7)
// Test data generated by Paimon's Bitmap64DeletionVector.serializeTo()
TEST_F(PaimonDeleteFileBuilderTest, TestDeletionVectorV2) {
    PaimonDeleteFileBuilder builder(FileSystem::Default());

    TPaimonDeletionFile paimon_deletion_file;
    paimon_deletion_file.__set_path("./be/test/formats/paimon/test_data/index-dv-v2-test");
    paimon_deletion_file.__set_offset(1);
    paimon_deletion_file.__set_length(44);

    ASSIGN_OR_ABORT(auto deletion_bitmap, builder.build(paimon_deletion_file));
    ASSERT_EQ(2, deletion_bitmap->get_cardinality());

    std::vector<uint64_t> deleted_rows(deletion_bitmap->get_cardinality());
    deletion_bitmap->to_array(deleted_rows);
    ASSERT_EQ(2, deleted_rows.size());
    ASSERT_EQ(3, deleted_rows[0]);
    ASSERT_EQ(7, deleted_rows[1]);
}

// Magic number matches neither v1 (BE) nor v2 (LE) -> InternalError.
TEST_F(PaimonDeleteFileBuilderTest, TestInvalidMagicNumber) {
    const std::string path = "/tmp/paimon_dv_invalid_magic_test";
    std::string content;
    content.push_back('\1');                           // version byte
    content += be32(12);                               // size field
    content += be32(static_cast<int32_t>(0xDEADBEEF)); // bogus magic
    content.append(4, '\0');                           // padding
    write_tmp_file(path, content);

    PaimonDeleteFileBuilder builder(FileSystem::Default());
    TPaimonDeletionFile paimon_deletion_file;
    paimon_deletion_file.__set_path(path);
    paimon_deletion_file.__set_offset(1);
    paimon_deletion_file.__set_length(12);

    auto result = builder.build(paimon_deletion_file);
    ASSERT_FALSE(result.ok());
    const Status& st = result.status();
    ASSERT_TRUE(st.is_internal_error()) << st;
    ASSERT_NE(std::string::npos, st.to_string().find("invalid paimon deletion vector magic number")) << st;

    std::remove(path.c_str());
}

// size field in the file does not match the expected size derived from DeletionFile.length -> InternalError.
TEST_F(PaimonDeleteFileBuilderTest, TestLengthMismatch) {
    const std::string path = "/tmp/paimon_dv_length_mismatch_test";
    std::string content;
    content.push_back('\1');
    content += be32(999);      // wrong size field
    content += be32(kMagicV1); // valid v1 magic
    content.append(8, '\0');   // bitmap placeholder
    write_tmp_file(path, content);

    PaimonDeleteFileBuilder builder(FileSystem::Default());
    TPaimonDeletionFile paimon_deletion_file;
    paimon_deletion_file.__set_path(path);
    paimon_deletion_file.__set_offset(1);
    paimon_deletion_file.__set_length(12); // expected_size_from_file = 12, file says 999

    auto result = builder.build(paimon_deletion_file);
    ASSERT_FALSE(result.ok());
    const Status& st = result.status();
    ASSERT_TRUE(st.is_internal_error()) << st;
    ASSERT_NE(std::string::npos, st.to_string().find("length mismatch")) << st;

    std::remove(path.c_str());
}

TEST_F(PaimonDeleteFileBuilderTest, TestInvalidOffset) {
    PaimonDeleteFileBuilder builder(FileSystem::Default());
    TPaimonDeletionFile paimon_deletion_file;
    paimon_deletion_file.__set_path("/tmp/paimon_dv_invalid_offset_test");
    paimon_deletion_file.__set_offset(-1);
    paimon_deletion_file.__set_length(8);

    auto result = builder.build(paimon_deletion_file);
    ASSERT_FALSE(result.ok());
    ASSERT_TRUE(result.status().is_invalid_argument()) << result.status();
    ASSERT_NE(std::string::npos, result.status().to_string().find("invalid paimon deletion vector offset"));

    paimon_deletion_file.__set_offset(std::numeric_limits<int64_t>::max());
    auto max_offset_result = builder.build(paimon_deletion_file);
    ASSERT_FALSE(max_offset_result.ok());
    ASSERT_TRUE(max_offset_result.status().is_invalid_argument()) << max_offset_result.status();
    ASSERT_NE(std::string::npos, max_offset_result.status().to_string().find("invalid paimon deletion vector offset"));
}

TEST_F(PaimonDeleteFileBuilderTest, TestShortV1Length) {
    const std::string path = "/tmp/paimon_dv_short_v1_test";
    std::string content;
    content.push_back('\1');
    content += be32(11);
    content += be32(kMagicV1);
    write_tmp_file(path, content);

    PaimonDeleteFileBuilder builder(FileSystem::Default());
    TPaimonDeletionFile paimon_deletion_file;
    paimon_deletion_file.__set_path(path);
    paimon_deletion_file.__set_offset(1);
    paimon_deletion_file.__set_length(11);

    auto result = builder.build(paimon_deletion_file);
    ASSERT_FALSE(result.ok());
    ASSERT_TRUE(result.status().is_invalid_argument()) << result.status();
    ASSERT_NE(std::string::npos, result.status().to_string().find("invalid paimon deletion vector length"));

    std::remove(path.c_str());
}

TEST_F(PaimonDeleteFileBuilderTest, TestShortV2Length) {
    const std::string path = "/tmp/paimon_dv_short_v2_test";
    std::string content;
    content.push_back('\1');
    content += be32(11);
    content += le32(kMagicV2);
    content.append(4, '\0');
    write_tmp_file(path, content);

    PaimonDeleteFileBuilder builder(FileSystem::Default());
    TPaimonDeletionFile paimon_deletion_file;
    paimon_deletion_file.__set_path(path);
    paimon_deletion_file.__set_offset(1);
    paimon_deletion_file.__set_length(19);

    auto result = builder.build(paimon_deletion_file);
    ASSERT_FALSE(result.ok());
    ASSERT_TRUE(result.status().is_invalid_argument()) << result.status();
    ASSERT_NE(std::string::npos, result.status().to_string().find("invalid paimon deletion vector length"));

    std::remove(path.c_str());
}

TEST_F(PaimonDeleteFileBuilderTest, TestOversizedLength) {
    const std::string path = "/tmp/paimon_dv_oversized_length_test";
    std::string content;
    content.push_back('\1');
    content += be32(4);
    content += be32(kMagicV1);
    write_tmp_file(path, content);

    PaimonDeleteFileBuilder builder(FileSystem::Default());
    TPaimonDeletionFile paimon_deletion_file;
    paimon_deletion_file.__set_path(path);
    paimon_deletion_file.__set_offset(1);
    paimon_deletion_file.__set_length(static_cast<int64_t>(std::numeric_limits<int32_t>::max()) + 1);

    auto result = builder.build(paimon_deletion_file);
    ASSERT_FALSE(result.ok());
    ASSERT_TRUE(result.status().is_invalid_argument()) << result.status();
    ASSERT_NE(std::string::npos, result.status().to_string().find("invalid paimon deletion vector length"));

    std::remove(path.c_str());
}

TEST_F(PaimonDeleteFileBuilderTest, TestOversizedV2Length) {
    const std::string path = "/tmp/paimon_dv_oversized_v2_length_test";
    std::string content;
    content.push_back('\1');
    content += be32(4);
    content += le32(kMagicV2);
    write_tmp_file(path, content);

    PaimonDeleteFileBuilder builder(FileSystem::Default());
    TPaimonDeletionFile paimon_deletion_file;
    paimon_deletion_file.__set_path(path);
    paimon_deletion_file.__set_offset(1);
    paimon_deletion_file.__set_length(static_cast<int64_t>(std::numeric_limits<int32_t>::max()) + 1);

    auto result = builder.build(paimon_deletion_file);
    ASSERT_FALSE(result.ok());
    ASSERT_TRUE(result.status().is_invalid_argument()) << result.status();
    ASSERT_NE(std::string::npos, result.status().to_string().find("invalid paimon deletion vector length"));

    std::remove(path.c_str());
}

// v1 path: valid magic + size, but bitmap bytes are not a valid roaring portable cookie -> RuntimeError.
TEST_F(PaimonDeleteFileBuilderTest, TestCorruptV1Bitmap) {
    const std::string path = "/tmp/paimon_dv_corrupt_v1_test";
    std::string content;
    content.push_back('\1');
    content += be32(12);       // size = magic(4) + bitmap(8)
    content += be32(kMagicV1); // v1 magic in BE
    content.append(8, '\0');   // 8 zero bytes -> invalid roaring cookie
    write_tmp_file(path, content);

    PaimonDeleteFileBuilder builder(FileSystem::Default());
    TPaimonDeletionFile paimon_deletion_file;
    paimon_deletion_file.__set_path(path);
    paimon_deletion_file.__set_offset(1);
    paimon_deletion_file.__set_length(12);

    auto result = builder.build(paimon_deletion_file);
    ASSERT_FALSE(result.ok());
    const Status& st = result.status();
    ASSERT_EQ(TStatusCode::RUNTIME_ERROR, st.code()) << st;
    ASSERT_NE(std::string::npos, st.to_string().find("deserialize roaring bitmap error")) << st;

    std::remove(path.c_str());
}

// v2 path: valid magic + size, but bitmap bytes are not a valid roaring64 portable header -> RuntimeError.
TEST_F(PaimonDeleteFileBuilderTest, TestCorruptV2Bitmap) {
    const std::string path = "/tmp/paimon_dv_corrupt_v2_test";
    std::string content;
    content.push_back('\1');
    content += be32(12);       // size field = magic(4) + bitmap(8)
    content += le32(kMagicV2); // v2 magic in LE
    content.append(8, '\xff'); // garbage bitmap body
    content.append(4, '\0');   // CRC placeholder (not validated by reader)
    write_tmp_file(path, content);

    PaimonDeleteFileBuilder builder(FileSystem::Default());
    TPaimonDeletionFile paimon_deletion_file;
    paimon_deletion_file.__set_path(path);
    paimon_deletion_file.__set_offset(1);
    paimon_deletion_file.__set_length(20); // 4(size) + 4(magic) + 8(bitmap) + 4(crc)

    auto result = builder.build(paimon_deletion_file);
    ASSERT_FALSE(result.ok());
    const Status& st = result.status();
    ASSERT_EQ(TStatusCode::RUNTIME_ERROR, st.code()) << st;
    ASSERT_NE(std::string::npos, st.to_string().find("deserialize roaring64 bitmap error")) << st;

    std::remove(path.c_str());
}

} // namespace starrocks::formats
