// Copyright 2021-present StarRocks, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#include <map>
#include <memory>
#include <string>
#include <vector>

namespace starrocks::lake {

class PersistentIndexSstable;

class PersistentIndexSstableFileset {
public:
    PersistentIndexSstableFileset() = default;
    ~PersistentIndexSstableFileset() = default;

    Status init(std::vector<std::unique_ptr<PersistentIndexSstable>>& sstables);
    Status init(std::unique_ptr<PersistentIndexSstable>& sstable);
    Status append(std::unique_ptr<PersistentIndexSstable>& sstable);
    uint64_t fileset_id() const { return _fileset_id; }

    // multi get from sstable fileset
    Status multi_get(const Slice* keys, const KeyIndexSet& key_indexes, int64_t version, IndexValue* values,
                     KeyIndexSet* found_key_indexes) const;

private:
    struct KeyComparator {
        bool operator()(const std::string& a, const std::string& b) const {
            return sstable::BytewiseComparator()->Compare(Slice(a), Slice(b)) < 0;
        }
    };

    // From start_key to <end_key, sstable_ptr>
    std::map<std::string, std::pair<std::string, std::unique_ptr<PersistentIndexSstable>>, KeyComparator> _sstable_map;
    // standalone sstable, it was generated by old version persistent index without key range info
    std::unique_ptr<PersistentIndexSstable> _standalone_sstable;
    uint64_t _fileset_id = 0;
};

} // namespace starrocks::lake