// Copyright 2021-present StarRocks, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#include <string>
#include <vector>

#include "common/status.h"
#include "gen_cpp/lake_types.pb.h"

namespace starrocks {
class Chunk;
class Column;
class TabletSchema;

namespace lake {

class Tablet;

// Basic interface for tablet writers.
class TabletWriter {
public:
    explicit TabletWriter(std::shared_ptr<const TabletSchema> tschema) : _schema(std::move(tschema)) {}

    virtual ~TabletWriter() = default;

    virtual int64_t tablet_id() const = 0;

    // This method is called immediately before any elements are processed, it
    // should contain the writer's initialization logic.
    virtual Status open() = 0;

    // Writes elements from the specified chunk to this rowset.
    //
    // It's guaranteed that the elements in each chunk are arranged in ascending
    // order, and the elements among all chunks written before `flush()` are also
    // arranged in ascending order.
    virtual Status write(const starrocks::Chunk& data) = 0;

    // Write del file to this rowset. PK table only
    virtual Status flush_del_file(const Column& deletes) = 0;

    // Flushes this writer and forces any buffered bytes to be written out to segment files.
    // There is no order guarantee between the data written before a `flush()`
    // and the data written after it.
    virtual Status flush() = 0;

    // This method is called at the end of data processing.
    virtual Status finish() = 0;

    // This method is called at the very end of the operator's life, both in
    // the case of a successful completion of the operation, and in the case
    // of a failure and canceling.
    virtual void close() = 0;

    // Return a list of files generated by this writer.
    // The file paths are relative to the tablet group path.
    //
    // PREREQUISITES: the writer has successfully `finish()`ed but not yet `close()`ed.
    virtual std::vector<std::string> files() const = 0;

    // The sum of all segment file sizes, in bytes.
    virtual int64_t data_size() const = 0;

    // The total number of rows have been written.
    virtual int64_t num_rows() const = 0;

    //  return the rowset txn meta generated by tablet writer
    virtual RowsetTxnMetaPB* rowset_txn_meta() = 0;

    // allow to set custom tablet schema for writer, used in partial update
    void set_tablet_schema(std::shared_ptr<const TabletSchema> tschema) { _schema = std::move(tschema); }

protected:
    std::shared_ptr<const TabletSchema> _schema;
};

} // namespace lake
} // namespace starrocks
