// Copyright 2021-present StarRocks, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#include <atomic>
#include <memory>
#include <optional>
#include <utility>
#include <vector>

#include "column/vectorized_fwd.h"
#include "common/object_pool.h"
#include "common/statusor.h"
#include "exec/pipeline/runtime_filter_core_types.h"
#include "exec/pipeline/runtime_filter_hub.h"
#include "exec/runtime_filter/runtime_filter_descriptor.h"
#include "exec/runtime_filter/runtime_filter_probe.h"
#include "gen_cpp/Types_types.h"

namespace starrocks::pipeline {

struct RuntimeMembershipFilterBuildParam;
using OpTRuntimeBloomFilterBuildParams = std::vector<std::optional<RuntimeMembershipFilterBuildParam>>;

// Parameters used to build runtime bloom-filters.
struct RuntimeMembershipFilterBuildParam {
    RuntimeMembershipFilterBuildParam(bool multi_partitioned, bool eq_null, bool is_empty, Columns columns,
                                      MutableRuntimeFilterPtr runtime_filter, TypeDescriptor type_descriptor)
            : multi_partitioned(multi_partitioned),
              eq_null(eq_null),
              is_empty(is_empty),
              columns(std::move(columns)),
              runtime_filter(std::move(runtime_filter)),
              _type_descriptor(std::move(type_descriptor)) {}
    bool multi_partitioned;
    bool eq_null;
    bool is_empty;
    Columns columns;
    MutableRuntimeFilterPtr runtime_filter;
    // used for skew join
    TypeDescriptor _type_descriptor;
};

// Used to merge runtime in-filters and bloom-filters generated by multiple HashJoinBuildOperator instances.
// When more than one HashJoinBuildOperator instances are appended to LocalExchangeSourceOperator(PartitionExchanger)
// instances, the build side table is partitioned, and each HashJoinBuildOperator instance is applied to the
// partition and a partial filter is generated after hash table has been constructed. the partial filters can
// not take effects on operators in front of LocalExchangeSourceOperators before they are merged into a total one.
class PartialRuntimeFilterMerger {
public:
    PartialRuntimeFilterMerger(ObjectPool* pool, size_t local_rf_limit, size_t global_rf_limit, int func_version,
                               bool enable_join_runtime_bitset_filter)
            : _pool(pool),
              _local_rf_limit(local_rf_limit),
              _global_rf_limit(global_rf_limit),
              _func_version(func_version),
              _enable_join_runtime_bitset_filter(enable_join_runtime_bitset_filter) {}

    void incr_builder() {
        _ht_row_counts.emplace_back(0);
        _partial_in_filters.emplace_back();
        _partial_bloom_filter_build_params.emplace_back();
        _num_active_builders++;
    }

    // mark runtime_filter as always true.
    StatusOr<bool> set_always_true() {
        _always_true = true;
        return _try_do_merge({});
    }

    RuntimeInFilterList get_total_in_filters() {
        // _partial_in_filters is empty means RF _is_always_true
        if (_partial_in_filters.empty()) return {};
        return {_partial_in_filters[0].begin(), _partial_in_filters[0].end()};
    }

    RuntimeMembershipFilterList get_total_bloom_filters() {
        return {_bloom_filter_descriptors.begin(), _bloom_filter_descriptors.end()};
    }

    // HashJoinBuildOperator call add_partial_filters to gather partial runtime filters. the last HashJoinBuildOperator
    // will merge partial runtime filters into total one finally.
    StatusOr<bool> add_partial_filters(size_t idx, size_t ht_row_count, RuntimeInFilters&& partial_in_filters,
                                       OpTRuntimeBloomFilterBuildParams&& partial_bloom_filter_build_params,
                                       RuntimeMembershipFilters&& bloom_filter_descriptors);

    Status merge_local_in_filters();
    Status merge_local_bloom_filters();
    Status merge_singleton_local_bloom_filters();
    Status merge_multi_partitioned_local_bloom_filters();

private:
    StatusOr<bool> _try_do_merge(RuntimeMembershipFilters&& bloom_filter_descriptors);

private:
    ObjectPool* _pool;

    const size_t _local_rf_limit;
    const size_t _global_rf_limit;
    const int _func_version;
    const bool _enable_join_runtime_bitset_filter;

    std::atomic<bool> _always_true{false};
    std::atomic<size_t> _num_active_builders{0};
    std::vector<size_t> _ht_row_counts;
    std::vector<RuntimeInFilters> _partial_in_filters;
    std::vector<OpTRuntimeBloomFilterBuildParams> _partial_bloom_filter_build_params;
    RuntimeMembershipFilters _bloom_filter_descriptors;
};

} // namespace starrocks::pipeline
