-- name: test_cast_to_variant_basic

SELECT
    CASE WHEN CAST(CAST(true AS VARIANT) AS BOOLEAN) = true THEN 'PASS' ELSE 'FAIL' END AS v_bool,
    CASE WHEN CAST(CAST(CAST(1 AS TINYINT) AS VARIANT) AS TINYINT) = 1 THEN 'PASS' ELSE 'FAIL' END AS v_tinyint,
    CASE WHEN CAST(CAST(CAST(2 AS SMALLINT) AS VARIANT) AS SMALLINT) = 2 THEN 'PASS' ELSE 'FAIL' END AS v_smallint,
    CASE WHEN ABS(CAST(CAST(CAST(1.25 AS FLOAT) AS VARIANT) AS FLOAT) - 1.25) < 0.0001 THEN 'PASS' ELSE 'FAIL' END
        AS v_float,
    CASE WHEN CAST(CAST(123 AS VARIANT) AS INT) = 123 THEN 'PASS' ELSE 'FAIL' END AS v_int,
    CASE WHEN CAST(CAST(-456 AS VARIANT) AS BIGINT) = -456 THEN 'PASS' ELSE 'FAIL' END AS v_bigint,
    CASE WHEN ABS(CAST(CAST(3.14 AS VARIANT) AS DOUBLE) - 3.14) < 0.0001 THEN 'PASS' ELSE 'FAIL' END AS v_double,
    CASE WHEN CAST(CAST(CAST('12.34' AS DECIMAL(10,2)) AS VARIANT) AS DECIMAL(10,2)) = CAST('12.34' AS DECIMAL(10,2))
        THEN 'PASS' ELSE 'FAIL' END AS v_dec,
    CASE WHEN CAST(CAST('hello' AS VARIANT) AS VARCHAR) = 'hello' THEN 'PASS' ELSE 'FAIL' END AS v_str,
    CASE WHEN CAST(CAST(CAST('2024-01-02' AS DATE) AS VARIANT) AS DATE) = CAST('2024-01-02' AS DATE)
        THEN 'PASS' ELSE 'FAIL' END AS v_date,
    CASE WHEN CAST(CAST(CAST('2024-01-02 03:04:05' AS DATETIME) AS VARIANT) AS DATETIME) =
        CAST('2024-01-02 03:04:05' AS DATETIME)
        THEN 'PASS' ELSE 'FAIL' END AS v_dt,
    CASE WHEN CAST(CAST(CAST('12:34:56' AS TIME) AS VARIANT) AS TIME) = CAST('12:34:56' AS TIME)
        THEN 'PASS' ELSE 'FAIL' END AS v_time,
    CASE WHEN CAST(CAST(CAST('1969-12-31 23:59:59.999999' AS DATETIME) AS VARIANT) AS DATETIME) =
        CAST('1969-12-31 23:59:59.999999' AS DATETIME)
        THEN 'PASS' ELSE 'FAIL' END AS v_dt_negative_epoch;
