// Copyright 2021-present StarRocks, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.starrocks.connector.paimon;

import com.starrocks.catalog.FunctionSet;
import com.starrocks.catalog.PaimonTable;
import com.starrocks.connector.index.ConnectorIndexType;
import com.starrocks.connector.index.IndexCondition;
import com.starrocks.connector.index.TopNIndexCondition;
import com.starrocks.sql.ast.expression.BinaryType;
import com.starrocks.sql.optimizer.operator.scalar.ArrayOperator;
import com.starrocks.sql.optimizer.operator.scalar.BinaryPredicateOperator;
import com.starrocks.sql.optimizer.operator.scalar.CallOperator;
import com.starrocks.sql.optimizer.operator.scalar.ColumnRefOperator;
import com.starrocks.sql.optimizer.operator.scalar.ConstantOperator;
import com.starrocks.thrift.TResultBatch;
import com.starrocks.type.ArrayType;
import com.starrocks.type.FloatType;
import com.starrocks.type.IntegerType;
import mockit.Expectations;
import mockit.Mocked;
import org.apache.paimon.globalindex.GlobalIndexResult;
import org.apache.paimon.globalindex.GlobalIndexResultSerializer;
import org.apache.paimon.globalindex.ScoredGlobalIndexResult;
import org.apache.paimon.io.DataInputDeserializer;
import org.apache.paimon.utils.RoaringNavigableMap64;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Base64;
import java.util.HexFormat;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicReference;

public class PaimonGlobalIndexServiceTest {
    @Test
    public void testDeserializePaimonCppV1BitmapResult() throws Exception {
        // Generated by the paimon-cpp dependency's GlobalIndexResult::Serialize from the
        // inclusive ranges [7, 9] and [20, 20]. This is a cross-language compatibility
        // fixture for the bytes emitted by BE and consumed by Paimon Java 2.0 on FE.
        byte[] cppBytes = HexFormat.of().parseHex(
                "000000010000001f0100000000000000000000003b30000001000003000200070002001400000000000000");

        GlobalIndexResult result = new GlobalIndexResultSerializer()
                .deserialize(new DataInputDeserializer(cppBytes));

        Assertions.assertEquals(4L, result.results().getLongCardinality());
        Assertions.assertTrue(result.results().contains(7L));
        Assertions.assertTrue(result.results().contains(8L));
        Assertions.assertTrue(result.results().contains(9L));
        Assertions.assertTrue(result.results().contains(20L));
    }

    @Test
    public void testAggregatesDistributedResultsAndQuotesIdentifiers(@Mocked PaimonTable table) throws Exception {
        new Expectations() {{
                table.getCatalogName();
                result = "pa`imon";
                table.getCatalogDBName();
                result = "d`b";
                table.getCatalogTableName();
                result = "t`bl";
            }};

        ColumnRefOperator column = new ColumnRefOperator(1, IntegerType.INT, "k", true);
        BinaryPredicateOperator predicate = new BinaryPredicateOperator(
                BinaryType.EQ, column, ConstantOperator.createInt(7));
        IndexCondition condition = new IndexCondition(
                predicate, Map.of("k", ConnectorIndexType.RANGE));

        AtomicReference<String> executedSql = new AtomicReference<>();
        AtomicInteger timeoutSeconds = new AtomicInteger();
        TResultBatch distributedBatch = batch(result(1L, 3L), null, result(5L));
        PaimonGlobalIndexService service = new PaimonGlobalIndexService(
                table, condition, 9L, (sql, timeout) -> {
                    executedSql.set(sql);
                    timeoutSeconds.set(timeout);
                    return List.of(distributedBatch);
                });

        PaimonGlobalIndexResult result = service.evaluate();

        Assertions.assertEquals(9L, result.getSnapshotId());
        Assertions.assertEquals(3L, result.getResult().results().getLongCardinality());
        Assertions.assertTrue(result.getResult().results().contains(1L));
        Assertions.assertTrue(result.getResult().results().contains(3L));
        Assertions.assertTrue(result.getResult().results().contains(5L));
        Assertions.assertTrue(timeoutSeconds.get() > 0);

        String sql = executedSql.get();
        Assertions.assertTrue(sql.contains("from `pa``imon`.`d``b`.`t``bl$global_index`"));
        Assertions.assertFalse(sql.contains("\"snapshotId\""));
        String prefix = "where `args`='";
        String transport = sql.substring(sql.indexOf(prefix) + prefix.length(), sql.length() - 1);
        Assertions.assertEquals(9L, PaimonGlobalIndexRequest.parseTransport(transport).getSnapshotId());
    }

    @Test
    public void testAggregatesGloballyRankedVectorTopN(@Mocked PaimonTable table) {
        new Expectations() {{
                table.getCatalogName();
                result = "paimon";
                table.getCatalogDBName();
                result = "db";
                table.getCatalogTableName();
                result = "tbl";
            }};

        ColumnRefOperator vector = new ColumnRefOperator(2, ArrayType.ARRAY_FLOAT, "embedding", false);
        ArrayOperator query = new ArrayOperator(ArrayType.ARRAY_FLOAT, false,
                List.of(ConstantOperator.createFloat(1), ConstantOperator.createFloat(2)));
        CallOperator score = new CallOperator(FunctionSet.APPROX_COSINE_SIMILARITY, FloatType.FLOAT,
                List.of(vector, query));
        TopNIndexCondition condition = new TopNIndexCondition(null, score,
                Map.of(vector.getName(), ConnectorIndexType.VECTOR), 2, 1, false);

        AtomicReference<String> executedSql = new AtomicReference<>();
        PaimonGlobalIndexService service = new PaimonGlobalIndexService(
                table, condition, 10L, (sql, timeout) -> {
                    executedSql.set(sql);
                    return List.of(
                            scoredBatch("[7,0.9]", "[3,0.8]"),
                            scoredBatch("[11,0.7]"));
                });

        PaimonGlobalIndexResult result = service.evaluate();

        Assertions.assertEquals(10L, result.getSnapshotId());
        Assertions.assertInstanceOf(ScoredGlobalIndexResult.class, result.getResult());
        ScoredGlobalIndexResult scored = (ScoredGlobalIndexResult) result.getResult();
        Assertions.assertEquals(3L, scored.results().getLongCardinality());
        Assertions.assertEquals(0.9f, scored.scoreGetter().score(7L), 0.0001f);
        Assertions.assertEquals(0.8f, scored.scoreGetter().score(3L), 0.0001f);
        Assertions.assertEquals(0.7f, scored.scoreGetter().score(11L), 0.0001f);

        String sql = executedSql.get();
        Assertions.assertTrue(sql.startsWith("select `row_id`, `score`"));
        Assertions.assertTrue(sql.contains("order by `score` desc limit 3"));
        Assertions.assertFalse(sql.contains("to_base64"));
    }

    @Test
    public void testRejectsInvalidVectorTopNRows(@Mocked PaimonTable table) {
        new Expectations() {{
                table.getCatalogName();
                result = "paimon";
                table.getCatalogDBName();
                result = "db";
                table.getCatalogTableName();
                result = "tbl";
            }};

        ColumnRefOperator vector = new ColumnRefOperator(2, ArrayType.ARRAY_FLOAT, "embedding", false);
        ArrayOperator query = new ArrayOperator(ArrayType.ARRAY_FLOAT, false,
                List.of(ConstantOperator.createFloat(1), ConstantOperator.createFloat(2)));
        CallOperator score = new CallOperator(FunctionSet.APPROX_L2_DISTANCE, FloatType.FLOAT,
                List.of(vector, query));
        TopNIndexCondition condition = new TopNIndexCondition(null, score,
                Map.of(vector.getName(), ConnectorIndexType.VECTOR), 1, 0, true);
        PaimonGlobalIndexService service = new PaimonGlobalIndexService(
                table, condition, 10L, (sql, timeout) -> List.of(scoredBatch("[-1,0.5]")));

        IllegalStateException exception = Assertions.assertThrows(IllegalStateException.class, service::evaluate);
        Assertions.assertTrue(exception.getMessage().contains("row id or score"));
    }

    private static GlobalIndexResult result(long... rowIds) {
        RoaringNavigableMap64 rows = new RoaringNavigableMap64();
        for (long rowId : rowIds) {
            rows.add(rowId);
        }
        return GlobalIndexResult.create(rows);
    }

    private static TResultBatch batch(GlobalIndexResult... results) throws IOException {
        GlobalIndexResultSerializer serializer = new GlobalIndexResultSerializer();
        List<ByteBuffer> rows = new ArrayList<>();
        for (GlobalIndexResult result : results) {
            String value = result == null ? "null"
                    : "\"" + Base64.getEncoder().encodeToString(serializer.serialize(result)) + "\"";
            rows.add(ByteBuffer.wrap(("{\"data\":[" + value + "]}").getBytes(StandardCharsets.UTF_8)));
        }
        TResultBatch batch = new TResultBatch();
        batch.setRows(rows);
        return batch;
    }

    private static TResultBatch scoredBatch(String... dataRows) {
        List<ByteBuffer> rows = new ArrayList<>();
        for (String data : dataRows) {
            rows.add(ByteBuffer.wrap(("{\"data\":" + data + "}").getBytes(StandardCharsets.UTF_8)));
        }
        TResultBatch batch = new TResultBatch();
        batch.setRows(rows);
        return batch;
    }
}
