name: Labels

on:
  pull_request_target:
    types:
      - opened
    paths:
      - 'docs/**'

jobs:
  pr-label:
    runs-on: ubuntu-latest
    steps:
      - name: add document label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: documentation
