name: automerge
on:
  pull_request_target:
    types:
      - labeled
jobs:
  automerge:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'automerge' }}
    steps:
      - name: enable automerge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: rebase
