
name: Blocker

on: 
  pull_request:
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  block-merge-and-commit:
    name: Block Merge Commits
    runs-on: ubuntu-latest
    steps:
      - run: echo "Squash and commit will be ok"
      - name: Block Merge Commits
        uses: Morishiri/block-merge-commits-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
