on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]
name: Sonar Scan
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Build & clean
      run: sh build.sh --clean
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: ${{github.workspace}}
        cmake-opts: ""
        make-opts: sh build.sh --clean
        args: >
          -Dsonar.organization=dulong41
          -Dsonar.projectKey=dulong41_starrocks
          -Dsonar.sources=be/
          -Dsonar.cfamily.build-wrapper-output=${{ github.workspace }}/bw-output
          -Dsonar.cfamily.gcov.reportsPath=ctest
