name: FE Code Style Checker

on:
  pull_request:
  
jobs:
  java-checkstyle:
    name: "CheckStyle"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: recursive
          
      - name: Run java checkstyle
        uses: dbelyaev/action-checkstyle@v0.6.1
        with:
          workdir: "./fe"
          reporter: 'github-pr-check'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          level: error
