name: check_status
on:
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: "Do nothing. Only trigger corresponding workflow_run event"
        run: echo
