name: CI COMMENT TOOLS

on:
  issue_comment:
    types: [ created ]

permissions:
  checks: write
  actions: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:

  info:
    name: INFO
    runs-on: [self-hosted, sync-normal]
    if: >
      ${{ github.event.issue.pull_request }} &&
      !contains(github.event.comment.body, 'BACKPORT to') &&
      !contains(github.event.comment.body, 'BACKPORT ERROR') &&
      (contains(github.event.comment.body, '@Mergify rebase') ||
      contains(github.event.comment.body, '@Mergifyio rebase') ||
      contains(github.event.comment.body, '@Mergify backport') ||
      contains(github.event.comment.body, '@Mergifyio backport') ||
      contains(github.event.comment.body, '@Mergify automerge') ||
      contains(github.event.comment.body, '@Mergifyio automerge'))

    env:
      PR_NUMBER: ${{ github.event.issue.number }}
      SYNC_PAT: ${{ secrets.SYNC_PAT }}
    outputs:
      assignees: ${{ steps.pr-info.outputs.assignees }}
      branch: ${{ steps.pr-info.outputs.branch }}
      state: ${{ steps.pr-info.outputs.state }}
      merge_commit: ${{ steps.pr-info.outputs.merge_commit }}
      title: ${{ steps.pr-info.outputs.title }}
    steps:
      - name: PR INFO
        id: pr-info
        run: |
          cd /var/lib/elastic-service && ./lib/get_pr_info.sh

  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    needs: info
    if: >
      contains(github.event.comment.body, '@Mergify rebase') ||
      contains(github.event.comment.body, '@Mergifyio rebase')
    env:
      PR_NUMBER: ${{ github.event.issue.number }}
      BRANCH: ${{ needs.info.outputs.branch }}
      ASSIGNEES: ${{ needs.info.outputs.assignees }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.8
        with:
          autosquash: ${{ contains(github.event.comment.body, 'autosquash') }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

  backport:
    name: Backport
    runs-on: [self-hosted, sync-normal]
    needs: info
    if: >
      contains(github.event.comment.body, '@Mergify backport') ||
      contains(github.event.comment.body, '@Mergifyio backport')
    env:
      PR_NUMBER: ${{ github.event.issue.number }}
      BRANCH: ${{ needs.info.outputs.branch }}
      ASSIGNEES: ${{ needs.info.outputs.assignees }}
      MERGE_COMMIT: ${{ needs.info.outputs.merge_commit }}
      GITHUB_TOKEN: ${{ secrets.SYNC_PAT }}
      ACTION_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

    steps:
      - name: Check Status
        run: |
          if [[ "${{ needs.info.outputs.state }}" != "MERGED" ]]; then
              gh pr comment ${PR_NUMBER} -R ${{ github.repository }} -b "❌ PR has not been merged yet!"
              exit 1
          fi

      - name: Checkout the latest code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: checkout tools
        uses: actions/checkout@v4
        with:
          repository: StarRocks/elastic-service
          path: './elastic-service'
          token: ${{ secrets.PAT }}
          fetch-depth: 1

      - name: BACKPORT
        id: backport
        run: |
          cd elastic-service
          ./bin/backport.sh "${{ needs.info.outputs.title }}" "${{ github.event.comment.body }}"

      - name: Report
        if: always() && steps.backport.outcome == 'failure'
        run: |
          gh pr comment ${PR_NUMBER} -R ${{ github.repository }} -b "❌ BACKPORT ERROR! <details></br></br>[Workflow details](${ACTION_URL})</details>"
          exit 1

  resolve-conflict-automerge:
    name: resolve conflict automerge
    runs-on: [ self-hosted, sync-normal ]
    if: >
      contains(github.event.comment.body, '@Mergify automerge') ||
      contains(github.event.comment.body, '@Mergifyio automerge')
    needs: info
    env:
      PR_NUMBER: ${{ github.event.issue.number }}
      GH_TOKEN: ${{ secrets.PAT }}

    steps:
      - name: merge directly
        if: contains(needs.info.outputs.branch, '-sync-pr-')
        run: |
          gh pr merge ${PR_NUMBER} -R ${GITHUB_REPOSITORY} -s --admin

  close:
    name: CLOSE PR
    runs-on: ubuntu-latest
    if: >
      contains(github.event.issue.pull_request.html_url, 'pull') &&
      (contains(github.event.comment.body, '@Mergify close') ||
      contains(github.event.comment.body, '@Mergifyio close'))

    env:
      PR_NUMBER: ${{ github.event.issue.number }}
      GITHUB_TOKEN: ${{ secrets.PAT }}

    steps:
      - name: CLOSE
        run: |
          gh pr close ${PR_NUMBER} -R ${{ github.repository }} -c "PR was manually closed."

  automerge:
    name: AutoMerge PR
    runs-on: ubuntu-latest
    if: >
      contains(github.event.issue.pull_request.html_url, 'pull') &&
      contains(github.event.comment.body, '@Mergify automerge')

    env:
      PR_NUMBER: ${{ github.event.issue.number }}

    steps:
      - name: BASE REF
        id: get_base_ref
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          base_ref=$(gh pr view ${PR_NUMBER} -R ${{ github.repository }} --json baseRefName | jq -r '.baseRefName')
          echo "base_ref=${base_ref}" >> $GITHUB_OUTPUT

      - name: AutoMerge
        if: startsWith(steps.get_base_ref.outputs.base_ref, 'mergify/bp')
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          gh pr merge ${PR_NUMBER} -R ${{ github.repository }} -s --auto
