name: DAILY INSPECTION

on:
  schedule:
    - cron: "00 15 * * *"
    - cron: "10 15 * * *"
    - cron: "20 15 * * *"

  workflow_dispatch:
    inputs:
      BRANCH:
        description: 'BRANCH'
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - branch-3.2
          - branch-3.1

env:
  IS_INSPECTION: true

jobs:
  info:
    runs-on: ubuntu-latest
    name: INFO
    env:
      REPO: ${{ github.repository }}
      GH_TOKEN: ${{ github.token }}
    outputs:
      BRANCH: ${{ steps.branch.outputs.branch }}
      BASE_VERSION: ${{ steps.branch.outputs.BASE_SHA }}
    steps:
      - id: branch
        name: BRANCH
        run: |
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            if [[ "${{ github.event.schedule }}" == "00 15 * * *" ]]; then
              branch=main
            elif [[ "${{ github.event.schedule }}" == "10 15 * * *" ]]; then
              branch=branch-3.2
            elif [[ "${{ github.event.schedule }}" == "20 15 * * *" ]]; then
              branch=branch-3.1
            else
              echo "::error::Schedule ERROR!" 
              exit -1 
            fi
          else
            branch=${{ inputs.BRANCH }}
          fi
          
          base_sha=$(gh api /repos/${REPO}/branches/${branch} | jq -r .commit.sha)
          [[ "${base_sha}" == "null" ]] && (echo "::error::Get HEAD SHA error, please check." && exit -1);
          
          echo "branch=${branch}" >> $GITHUB_OUTPUT
          echo "BASE_SHA=${base_sha}" >> $GITHUB_OUTPUT


  clang-format:
    runs-on: [self-hosted, light]
    needs: info
    name: Clang-Format
    env:
      BASE_VERSION: ${{ needs.info.outputs.BASE_VERSION }}
    steps:
      - name: clean
        run: |
          rm -rf ${{ github.workspace }}
          mkdir -p ${{ github.workspace }}

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ needs.info.outputs.BRANCH }}

      - name: Run Clang-Format
        run: |
          git reset ${BASE_VERSION} --hard
          export PATH=/var/lib/llvm/bin:$PATH
          bash build-support/check-format.sh

      - name: Clean ENV
        if: always()
        run: |
          rm -rf ${{ github.workspace }}/*

  be-ut:
    runs-on: [self-hosted, normal]
    needs: [ info, clang-format ]
    timeout-minutes: 180
    name: BE UT
    env:
      BRANCH: ${{ needs.info.outputs.BRANCH }}
      BASE_VERSION: ${{ needs.info.outputs.BASE_VERSION }}
    steps:
      - name: UPDATE ECI & RUN UT
        id: run_ut
        shell: bash
        timeout-minutes: 180
        run: |
          rm -rf ./ci-tool && cp -rf /var/lib/ci-tool ./ci-tool && cd ci-tool && git pull && source lib/init.sh
          ./bin/elastic-ut.sh --branch ${BRANCH} --pr ${BASE_VERSION} --module be --repository ${{ github.repository }}

      - name: clean ECI - ${{ steps.run_ut.outputs.ECI_ID }}
        if: always()
        run: |
          eci rm ${{ steps.run_ut.outputs.ECI_ID }}

      - name: Upload Log
        uses: actions/upload-artifact@v3
        if: always() && steps.run_ut.outcome == 'failure'
        with:
          name: BE UT LOG
          path: ${{ steps.run_ut.outputs.BE_LOG }}
          retention-days: 1

      - name: Clean ENV
        if: always()
        run: |
          rm -f ${{ steps.run_ut.outputs.RES_FILE }}
          rm -f ${{ steps.run_ut.outputs.RES_LOG }}
          rm -rf ${{ steps.run_ut.outputs.BE_LOG }}
          rm -rf ${{ github.workspace }}/*

  clang-tidy:
    runs-on: [self-hosted, normal]
    needs: [ info, clang-format ]
    timeout-minutes: 90
    name: Clang-Tidy
    if: needs.info.outputs.BRANCH == 'main'
    env:
      BRANCH: ${{ needs.info.outputs.BRANCH }}
      BASE_VERSION: ${{ needs.info.outputs.BASE_VERSION }}
    steps:
      - name: clean
        run: |
          rm -rf ${{ github.workspace }}
          mkdir -p ${{ github.workspace }}

      - name: UPDATE ECI & RUN Clang Tidy
        id: run_clang_tidy
        shell: bash
        timeout-minutes: 60
        run: |
          rm -rf ./ci-tool && cp -rf /var/lib/ci-tool ./ci-tool && cd ci-tool && git pull && source lib/init.sh
          ./bin/elastic-build.sh --branch ${BRANCH} --pr ${BASE_VERSION} --repository ${{ github.repository }} --be --clang-tidy

      - name: clean ECI
        if: always()
        run: |
          echo ${{ steps.run_clang_tidy.outputs.ECI_ID }}
          eci rm ${{ steps.run_clang_tidy.outputs.ECI_ID }}

      - name: Clean ENV
        if: always()
        run: |
          rm -f ${{ steps.run_clang_tidy.outputs.RES_FILE }}
          rm -f ${{ steps.run_clang_tidy.outputs.RES_LOG }}
          rm -rf ${{ github.workspace }}/*

  fe-codestyle-check:
    runs-on: ubuntu-latest
    needs: info
    name: FE Code Style Check
    env:
      BRANCH: ${{ needs.info.outputs.BRANCH }}
      BASE_VERSION: ${{ needs.info.outputs.BASE_VERSION }}
    steps:
      - name: clean
        run: |
          rm -rf ${{ github.workspace }}
          mkdir -p ${{ github.workspace }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ needs.info.outputs.BRANCH }}

      - name: Copy checkstyle files
        run: |
          cp fe/checkstyle* .

      - name: Run java checkstyle
        uses: dbelyaev/action-checkstyle@v1.5.6
        with:
          workdir: "./fe"
          checkstyle_config: checkstyle.xml
          reporter: 'github-pr-check'
          github_token: ${{ secrets.PAT }}
          fail_on_error: true
          level: error

  fe-ut:
    runs-on: [self-hosted, normal]
    needs: [info, fe-codestyle-check]
    name: FE UT
    env:
      CODE_PATH: ${{ github.workspace }}
      BRANCH: ${{ needs.info.outputs.BRANCH }}
      GH_TOKEN: ${{ github.token }}
      BASE_VERSION: ${{ needs.info.outputs.BASE_VERSION }}
    steps:
      - name: clean
        run: |
          rm -rf ${{ github.workspace }}
          mkdir -p ${{ github.workspace }}

      - name: BRANCH INFO
        id: branch
        run: |
          repo="${{ github.repository }}"
          bucket_prefix=`echo ${repo%/*} | tr '[:upper:]' '[:lower:]'` 
          echo "bucket_prefix=${bucket_prefix}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ needs.info.outputs.BRANCH }}

      - name: UPDATE ECI & RUN UT
        id: run_ut
        shell: bash
        timeout-minutes: 60
        run: |
          rm -rf ./ci-tool && cp -rf /var/lib/ci-tool ./ci-tool && cd ci-tool && git pull && source lib/init.sh
          ./bin/elastic-ut.sh --module fe --pr ${BASE_VERSION} --branch ${BRANCH} --build Release --repository ${{ github.repository }}

      - name: Clean ECI - ${{ steps.run_ut.outputs.ECI_ID }}
        if: always()
        run: |
          echo ">>> Dmesg info:"
          eci exec ${{ steps.run_ut.outputs.ECI_ID }} bash -c "dmesg -T"
          eci rm ${{ steps.run_ut.outputs.ECI_ID }}

      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: FE UT LOG
          path: ${{ steps.run_ut.outputs.RES_LOG }}
          retention-days: 1

      - name: Clean ENV
        if: always()
        run: |
          rm -rf ${{ steps.run_ut.outputs.FE_REPORT_DIR }}
          rm -f ${{ steps.run_ut.outputs.RES_FILE }}
          rm -f ${{ steps.run_ut.outputs.RES_LOG }}
          rm -rf ${{ steps.run_ut.outputs.COV_DIR }}
          rm -rf ${{ github.workspace }}/*

  build:
    runs-on: [ self-hosted, normal ]
    needs: [ info, clang-format, fe-codestyle-check ]
    name: BUILD
    env:
      BRANCH: ${{ needs.info.outputs.BRANCH }}
      BASE_VERSION: ${{ needs.info.outputs.BASE_VERSION }}
    steps:
      - name: clean
        run: |
          rm -rf ${{ github.workspace }}
          mkdir -p ${{ github.workspace }}

      - name: UPDATE ECI & RUN BUILD
        id: run_build
        shell: bash
        timeout-minutes: 90
        env:
          SKIP_OSS: 'true'
        run: |
          rm -rf ./ci-tool && cp -rf /var/lib/ci-tool ./ci-tool && cd ci-tool && git pull && source lib/init.sh
          ./bin/elastic-build.sh --branch ${BRANCH} --pr ${BASE_VERSION} --repository ${{ github.repository }}

      - name: clean ECI - ${{ steps.run_build.outputs.ECI_ID }}
        if: always()
        run: |
          eci rm ${{ steps.run_build.outputs.ECI_ID }}

      - name: Clean ENV
        if: always()
        run: |
          rm -f ${{ steps.run_build.outputs.RES_FILE }}
          rm -f ${{ steps.run_build.outputs.RES_LOG }}

  report:
    runs-on: [ self-hosted, normal ]
    needs: [ info, clang-format, fe-codestyle-check, be-ut, clang-tidy, fe-ut, build ]
    name: REPORT
    if: >
      always() && needs.info.result == 'success'
    env:
      BRANCH: ${{ needs.info.outputs.BRANCH }}
      ACTION_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

    steps:
      - name: clean
        run: |
          rm -rf ${{ github.workspace }}
          mkdir -p ${{ github.workspace }}

      - name: send
        run: |
          rm -rf ./elastic-service && cp -rf /var/lib/elastic-service ./elastic-service && cd elastic-service && git pull
          python3 lib/daily_inspection_notify.py \
            ${BRANCH} \
            ${ACTION_URL} \
            ${{ needs.clang-format.result }} \
            ${{ needs.be-ut.result }}  \
            ${{ needs.clang-tidy.result }}  \
            ${{ needs.fe-codestyle-check.result }}  \
            ${{ needs.fe-ut.result }}  \
            ${{ needs.build.result }} 

      - name: Clean ENV
        if: always()
        run: |
          rm -rf ${{ github.workspace }}/*
