on: pull_request_review
name: Trigger Jobs
jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
    - uses: luisrjaeger/approved-event-checker@master
      id: approved
      with:
        approvals: 2
        check_changes_requested: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: trigger jenkins job
      if: ${{ steps.approved.outputs.approved == 'true' }}
      run: curl --fail -w %{http_code} -I -u starrocks:${{ secrets.JENKINS_PW }} http://39.101.206.100:8090/job/starrocks_admit_test/buildWithParameters?token=${{ secrets.JENKINS_TOKEN }}
