on: 
#pull_request_review
    push:
name: Trigger Jobs
jobs:
  Trigger-A-Jenkins-Job-With-2-Approval:
    runs-on: ubuntu-latest
    steps:
    #- uses: luisrjaeger/approved-event-checker@master
    #  id: approved
    #  with:
    #    approvals: 2
    #    check_changes_requested: false
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: trigger jenkins job
      shell: bash
      if: ${{ steps.approved.outputs.approved == 'true' }}
      env:
        JENKINS_PW: ${{ secrets.JENKINS_PW }}
        JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        JENKINS_URL: ${{ secrets.JENKINS_URL }}
      run: |
        curl --fail -w %{http_code} -I -u starrocks:"$JENKINS_PW" "$JENKINS_URL"/job/starrocks_admit_test/buildWithParameters?token="$JENKINS_TOKEN"

