name: Trigger Jobs

on: 
  pull_request_review

jobs:
  Trigger-A-Jenkins-Job-With-2-Approval:
    runs-on: ubuntu-latest
    steps:
    - uses: taichi/approved-event-action@master
      id: approved
      with:
        approvals: '2'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      
    - name: trigger jenkins job
      if: ${{ steps.approved.outputs.approved == 'true' }}     
      run: |
        curl --fail -w %{http_code} -I -u starrocks:starrocks@test http://39.101.206.100:8090/job/starrocks_admit_test/buildWithParameters?token=112bc1b04f326123e6668f931a7d26f7dd?GITHUB_PR_NUMBER=11&GITHUB_PR_TARGET_BRANCH=branch2.2

