name: LABEL ACTION

on:
  pull_request_target:
    types:
      - labeled

permissions:
  checks: write
  actions: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  meta-review:
    name: META REVIEW
    if: github.event.label.name == 'META-REVIEW'
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      META_TEAM: meta-committer

    steps:
      - name: ADD REVIEWER
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${PULL_NUMBER}/requested_reviewers" \
            -d "{\"team_reviewers\":[\"${META_TEAM}\"]}" 2>/dev/null
