name: env-cleanup

on:
  pull_request_target:
    types:
      - synchronize
      - closed
    paths:
      - 'be/**'

jobs:
  env-cleanup:
    runs-on: self-hosted
    env:
      PR_NUMBER: ${{ github.event.number }}
    steps:        
      - uses: actions-ecosystem/action-remove-labels@v1
        if: contains(github.event.pull_request.labels.*.name, 'be-build')
        with:
          labels: be-build
