name: Repo Sync

on:

  workflow_dispatch:
    inputs:
      PR_ID:
        description: 'ORI PR ID'
        required: true
        type: string
      COMMIT_ID:
        description: 'ORI COMMIT ID'
        required: true
        type: string
      BRANCH:
        description: 'TARGET BRANCH'
        required: true
        type: string
        default: 'main'
      DEBUG:
        description: 'DEBUG REPO'
        required: true
        type: boolean
        default: false

permissions:
  checks: write
  actions: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:

  pr-info:
    name: Add PR Information
    runs-on: [self-hosted, sync-normal]
    env:
      PR_ID: ${{ inputs.PR_ID }}
      SYNC_PAT: ${{ secrets.SYNC_PAT }}
    outputs:
      assignees: ${{ steps.ori_pr_info.outputs.assignees }}
      body: ${{ steps.ori_pr_info.outputs.body }}
      title: ${{ steps.ori_pr_info.outputs.title }}
    steps:
      - name: Ori PR Info
        id: ori_pr_info
        run: |
          cd /var/lib/elastic-service
          ./lib/get_pr_info.sh 

  repo-sync:
    name: Repo Sync
    runs-on: [self-hosted, sync]
    needs: pr-info
    env:
      PR_BODY: ${{ needs.pr-info.outputs.body }}
    steps:
      - name: clean
        run: |
          rm -rf ${{ github.workspace }}
          mkdir -p ${{ github.workspace }}

      - name: Clean Branches
        env:
          source_branch: ${{ inputs.BRANCH }}-sync-${{ inputs.PR_ID }}
          destination_branch: ${{ inputs.BRANCH }}-sync-pr-${{ inputs.PR_ID }}
        run: |
          curl -s -X DELETE -u username:${{secrets.SYNC_PAT}} https://api.github.com/repos/${{ github.repository }}/git/refs/heads/${{ env.source_branch }}
          curl -s -X DELETE -u username:${{secrets.SYNC_PAT}} https://api.github.com/repos/${{ github.repository }}/git/refs/heads/${{ env.destination_branch }}

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SYNC_PAT }}
          fetch-depth: 0
          ref: ${{ inputs.BRANCH }}

      - uses: repo-sync/github-sync@v2
        name: Sync repo to branch
        with:
          source_repo: StarRocks/starrocks
          source_branch: ${{ inputs.BRANCH }}
          destination_branch: ${{ inputs.BRANCH }}-sync-${{ inputs.PR_ID }}
          github_token: ${{ secrets.SYNC_PAT }}

      - name: checkout tools
        uses: actions/checkout@v3
        with:
          repository: StarRocks/elastic-service
          path: './elastic-service'
          token: ${{ secrets.SYNC_PAT }}
          
      - name: wait previous prs merged
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_PAT }}
        run: |
          cd ${{ github.workspace }}/elastic-service
          python3 lib/pr_sequence_checker.py wait   
          
      - name: pr branch
        run: |
          git pull
          pr_branch=${{ inputs.BRANCH }}-sync-pr-${{ inputs.PR_ID }}
          git branch ${pr_branch} ${{ inputs.BRANCH }}
          git checkout ${pr_branch}
          git push -u origin ${pr_branch}

      - name: previous check
        id: previous-check
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_PAT }}
        run: |
          cd ${{ github.workspace }}/elastic-service
          check_res=$(python3 lib/pr_sequence_checker.py new ${{ inputs.BRANCH }} ${{ inputs.PR_ID }} ${{ inputs.COMMIT_ID }})
          echo ${check_res}
          conflict_prs=$(echo ${check_res} | awk -F'Files:' '{print $1}' | awk -F' ' '{print $NF}')
          echo CONFLICT_PRS=${conflict_prs} >> $GITHUB_OUTPUT
          check_res=$(echo $check_res | tail -n 1)
          echo RES=${check_res} >> $GITHUB_OUTPUT

      - name: cherry pick
        id: cherry-pick
        run: |
          cd ${{ github.workspace }}/elastic-service
          ./lib/run_cherry_pick.sh --pr ${{ inputs.PR_ID }}
          cd ${{ github.workspace }}
          rm -rf elastic-service
          git push -u origin ${{ inputs.BRANCH }}-sync-pr-${{ inputs.PR_ID }}

      - uses: repo-sync/pull-request@v2.12.1
        id: create_pr
        name: Create pull request
        if: steps.previous-check.outputs.RES == 'True'
        with:
          source_branch: ${{ inputs.BRANCH }}-sync-pr-${{ inputs.PR_ID }}
          destination_branch: ${{ inputs.BRANCH }}
          pr_label: "sync,${{ inputs.BRANCH }},${{ steps.cherry-pick.outputs.LABEL }}${{ steps.cherry-pick.outputs.CONFLICT_LABEL }}"
          pr_title: "${{ needs.pr-info.outputs.title }}(sync #${{ inputs.PR_ID }})"
          pr_body: ${{ steps.cherry-pick.outputs.CONFLICT_INFO }}${{ env.PR_BODY }}
          github_token: ${{ secrets.SYNC_PAT }}
          pr_reviewer: ${{ needs.pr-info.outputs.assignees }}
          pr_allow_empty: true

      # previous pr files' check conflict
      - name: Create pending pull request
        id: create_pending_pr
        if: steps.previous-check.outputs.RES != 'True'
        uses: repo-sync/pull-request@v2.12.1
        with:
          source_branch: ${{ inputs.BRANCH }}-sync-pr-${{ inputs.PR_ID }}
          destination_branch: ${{ inputs.BRANCH }}
          pr_label: "sync,${{ inputs.BRANCH }},${{ steps.cherry-pick.outputs.LABEL }},pending"
          pr_title: "${{ needs.pr-info.outputs.title }}(sync #${{ inputs.PR_ID }})"
          pr_body: |
            Previous prs: ${{ steps.previous-check.outputs.CONFLICT_PRS }}
          github_token: ${{ secrets.SYNC_PAT }}
          pr_reviewer: ${{ needs.pr-info.outputs.assignees }}
          pr_allow_empty: true

      # Unexpected failure
      - name: Create Error pull request
        id: create_error_pr
        if: >
          always() && 
          ( steps.previous-check.outcome == 'failure' ||
            steps.cherry-pick.outcome == 'failure' ||
            steps.create_pr.outcome == 'failure' ||
            steps.create_pending_pr.outcome == 'failure')
        uses: repo-sync/pull-request@v2.12.1
        env:
          source_branch: ${{ inputs.BRANCH }}-sync-${{ inputs.PR_ID }}
          destination_branch: ${{ inputs.BRANCH }}-sync-pr-${{ inputs.PR_ID }}
        with:
          source_branch: ${{ env.source_branch }}
          destination_branch: ${{ env.destination_branch }}
          pr_label: "sync,${{ inputs.BRANCH }},${{ steps.cherry-pick.outputs.LABEL }},conflict,error"
          pr_title: "${{ needs.pr-info.outputs.title }}(sync #${{ inputs.PR_ID }})"
          pr_body: |
            # ERROR, please contact us.<br />
            ## cherry-pick #${{ inputs.PR_ID }}(${{ inputs.COMMIT_ID }}) from ${{ env.source_branch }} to ${{ env.destination_branch }} error<br />
            please fix this and then create pr to ${{ inputs.BRANCH }}!<br />
            ${{ env.PR_BODY }}
          github_token: ${{ secrets.SYNC_PAT }}
          pr_reviewer: ${{ needs.pr-info.outputs.assignees }}

      - name: notify
        if: always()
        env:
          branch: ${{ inputs.BRANCH }}
          source_pr: ${{ inputs.PR_ID }}
          source_commit_id: ${{ inputs.COMMIT_ID }}
          action_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          cd ${{ github.workspace }}
          git clone https://${{ secrets.SYNC_PAT }}@github.com/StarRocks/elastic-service.git
          cd elastic-service
          if [[ "${{ steps.cherry-pick.outputs.CONFLICT_LABEL }}" != '' && "${{ steps.create_pr.outcome }}" == 'success' ]]; then
            msg_type="conflict"
            this_pr_url=${{ steps.create_pr.outputs.pr_url }}
          elif [[ "${{ steps.create_pending_pr.outcome }}" == 'success' ]]; then
            msg_type="pending"
            this_pr_url=${{ steps.create_pending_pr.outputs.pr_url }}
          elif [[ "${{ steps.create_pr.outcome }}" == 'success' ]]; then
            exit 0;
          else
            msg_type="error"
            this_pr_url=${{ steps.create_error_pr.outputs.pr_url }}
          fi
          python3 lib/sync_notify.py ${msg_type} ${branch} ${source_pr} ${source_commit_id} ${action_url} ${this_pr_url}
