name: Labeler

on:
  pull_request:
    types: [opened, edited]

jobs:
  Title2Label:
    runs-on: ubuntu-latest
    steps:
      # The action can be used as many times as needed in a single job
      - uses: fregante/title-to-labels-action@v1
        if: contains(github.event.pull_request.labels.*.name, 'conflicts') != 'true'
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          keywords: backport, cherry-pick
          labels: automerge
