name: Labeler

on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  Title2Label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        if: (contains(${{ github.event.pull_request.title }},'backport') || contains(${{ github.event.pull_request.title }},'backport')) && contains(github.event.pull_request.labels.*.name, 'conflicts') != 'true'
        with:
          labels: automerge
      
#       # The action can be used as many times as needed in a single job
#       - uses: fregante/title-to-labels-action@v1
#         if: contains(github.event.pull_request.labels.*.name, 'conflicts') != 'true'
#         with:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           keywords: backport, cherry-pick
#           labels: automerge
