name: Translate changes to Chinese

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - 'docs/en/**'
defaults:
  run:
    shell: bash  # default shell is sh

jobs:
  # -------------------------------------------------------------
  # Event `pull_request`: Returns all changed pull request files.
  # --------------------------------------------------------------
  changed_files:
    # NOTE:
    # This workflow will only translate docs if:
    # - the PR is merged
    # - the `Yes, translate...` box is checked
    # - the `Do not translate` box is unchecked

    if: github.event.pull_request.merged == true && contains(toJson(github.event.pull_request.body), '[x] Yes, translate English markdown files with GPT') && contains(toJson(github.event.pull_request.body), '[ ] Do not translate')
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install gpt_translate

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
            files: docs/en/**/*.{md,mdx}
            output_dir: '.github/outputs' # this is the default dir
            write_output_files: 'true'

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file"
          done
          echo "also cat the generated file all_changed_files.txt"
          cat ./.github/outputs/all_changed_files.txt

      - name: Translate files
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          cp -r docs/translation/configs . # ugh, only works if configs is in cwd
          gpt_translate.files \
            --input_file ./.github/outputs/all_changed_files.txt \
            --config_folder ./configs
          rm -rf configs

      - name: Fix sidebar display
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          sed "s#docs/en#docs/zh#g" ./.github/outputs/all_changed_files.txt > ./.github/outputs/new_files.txt
          cat ./.github/outputs/new_files.txt
          while IFS="" read -r english || [ -n "$english" ]
          do
            sed -i'' '/displayed_sidebar:/s/English/Chinese/' "$english"
          done < ./.github/outputs/new_files.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.TRANSLATE_PAT }}
          commit-message: Translated Docs
          title: Automatic translation
          body: |
            This PR was automatically created by the translate-action when merging [PR](${{ github.event.pull_request.number }})
            Please review the changes and merge if they are correct.
          branch: translate-pr-${{ github.event.pull_request.number }}
          base: main
          delete-branch: true
          labels: translation
          add-paths: |
            docs/zh
