on: pull_request_review
name: Trigger Jobs
jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
    - uses: luisrjaeger/approved-event-checker@master
      id: approved
      with:
        approvals: 2
        check_changes_requested: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: trigger multiple Job
      if: ${{ steps.approved.outputs.approved == 'true' }}
      uses: appleboy/jenkins-action@master
      with:
        url: "http://39.101.206.100:8090/"
        user: "starrocks"
        token: ${{ secrets.JENKINS_TOKEN }}
        job: "master_release"
