WITH `CELONIS__PQL2SQL_ParserContext_Constant_000` AS (
  SELECT
    1 AS `CELONIS__PQL2SQL_ParserContext_primaryKey_001`
),
`PLAN_REMIT_HDR` AS (
  SELECT
    `CELONIS__PQL2SQL_TableScan_Alias_PLAN_REMIT_HDR_000`.`CELONIS__FK_9_CLAIM_HDR_PLAN_REMIT_HDR` AS `CELONIS__FK_9_CLAIM_HDR_PLAN_REMIT_HDR`,
    (`CELONIS__PQL2SQL_TableScan_Alias_PLAN_REMIT_HDR_000`.`TEAM_NAME` IN ( "Immunization - MEDICARE" )) AS `ELIDE`
  FROM
    `af8f13f31_859e_41e7_9fd1_9f1591554933_740fbceb_fd4b_4e8f_8640_c7d1f5766545_a081a018_a884_44fb_a7ca_8866d7a4477e`.`PLAN_REMIT_HDR` AS `CELONIS__PQL2SQL_TableScan_Alias_PLAN_REMIT_HDR_000`
),
`CELONIS__PQL2SQL_TableScanSequence_CLAIM_HDR_000` AS (
  SELECT
    `CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_001`.`CLAIM_ID` AS `CELONIS__PQL2SQL_JoinColumnResolver_Column_CLAIM_ID_000`,
    `CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_001`.`CLAIM_STATE_CD` AS `CELONIS__PQL2SQL_JoinColumnResolver_Column_CLAIM_STATE_CD_000`,
    `CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_001`.`CLAIM_STATUS_CD` AS `CELONIS__PQL2SQL_JoinColumnResolver_Column_CLAIM_STATUS_CD_000`,
    `CELONIS__PQL2SQL_ParserContext_Alias_PLAN_REMIT_HDR_000`.`ELIDE` AS `ELIDE_2`,
    `CELONIS__PQL2SQL_ParserContext_Alias_LUV_CLAIM_STATE_CD_000`.`LOOKUP_DETAIL` AS `CELONIS__PQL2SQL_JoinColumnResolver_Column_LOOKUP_DETAIL_001`,
    `CELONIS__PQL2SQL_ParserContext_Alias_LUV_CLAIM_STATUS_CD_000`.`LOOKUP_DETAIL` AS `CELONIS__PQL2SQL_JoinColumnResolver_Column_LOOKUP_DETAIL_003`
  FROM
    `af8f13f31_859e_41e7_9fd1_9f1591554933_740fbceb_fd4b_4e8f_8640_c7d1f5766545_a081a018_a884_44fb_a7ca_8866d7a4477e`.`CLAIM_HDR` AS `CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_001`
    LEFT JOIN `af8f13f31_859e_41e7_9fd1_9f1591554933_740fbceb_fd4b_4e8f_8640_c7d1f5766545_a081a018_a884_44fb_a7ca_8866d7a4477e`.`LUV_CLAIM_STATE_CD` AS `CELONIS__PQL2SQL_ParserContext_Alias_LUV_CLAIM_STATE_CD_000` ON (`CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_001`.`CELONIS__FK_9_CLAIM_HDR_LUV_CLAIM_STATE_CD` = `CELONIS__PQL2SQL_ParserContext_Alias_LUV_CLAIM_STATE_CD_000`.`CELONIS__FK_9_CLAIM_HDR_LUV_CLAIM_STATE_CD`)
    LEFT JOIN `af8f13f31_859e_41e7_9fd1_9f1591554933_740fbceb_fd4b_4e8f_8640_c7d1f5766545_a081a018_a884_44fb_a7ca_8866d7a4477e`.`LUV_CLAIM_STATUS_CD` AS `CELONIS__PQL2SQL_ParserContext_Alias_LUV_CLAIM_STATUS_CD_000` ON (`CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_001`.`CELONIS__FK_9_CLAIM_HDR_LUV_CLAIM_STATUS_CD` = `CELONIS__PQL2SQL_ParserContext_Alias_LUV_CLAIM_STATUS_CD_000`.`CELONIS__FK_9_CLAIM_HDR_LUV_CLAIM_STATUS_CD`)
    LEFT JOIN `PLAN_REMIT_HDR` AS `CELONIS__PQL2SQL_ParserContext_Alias_PLAN_REMIT_HDR_000` ON (`CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_001`.`CELONIS__FK_9_CLAIM_HDR_PLAN_REMIT_HDR` = `CELONIS__PQL2SQL_ParserContext_Alias_PLAN_REMIT_HDR_000`.`CELONIS__FK_9_CLAIM_HDR_PLAN_REMIT_HDR`)
),
`CELONIS__PQL2SQL_TableScanSequence_CLAIM_HDR_001` AS (
  SELECT
    `CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_002`.`CELONIS__PQL2SQL_JoinColumnResolver_Column_CLAIM_ID_000` AS `CELONIS__PQL2SQL_JoinColumnResolver_Column_CLAIM_ID_000`,
    CONCAT(`CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_002`.`CELONIS__PQL2SQL_JoinColumnResolver_Column_CLAIM_STATE_CD_000`,  " - " , `CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_002`.`CELONIS__PQL2SQL_JoinColumnResolver_Column_LOOKUP_DETAIL_001`) AS `CELONIS__PQL2SQL_OperatorNodeHandler_000`,
    CONCAT(`CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_002`.`CELONIS__PQL2SQL_JoinColumnResolver_Column_CLAIM_STATUS_CD_000`,  " - " , `CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_002`.`CELONIS__PQL2SQL_JoinColumnResolver_Column_LOOKUP_DETAIL_003`) AS `CELONIS__PQL2SQL_OperatorNodeHandler_001`,
    `CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_002`.`ELIDE_2` AS `ELIDE_3`
  FROM
    `CELONIS__PQL2SQL_TableScanSequence_CLAIM_HDR_000` AS `CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_002`
),
`CELONIS__PQL2SQL_TableScanSequence_CLAIM_HDR_002` AS (
  SELECT
    `CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_003`.`CELONIS__PQL2SQL_JoinColumnResolver_Column_CLAIM_ID_000` AS `CELONIS__PQL2SQL_JoinColumnResolver_Column_CLAIM_ID_000`,
    `CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_003`.`CELONIS__PQL2SQL_OperatorNodeHandler_001` AS `CELONIS__PQL2SQL_OperatorNodeHandler_001`,
    (`CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_003`.`CELONIS__PQL2SQL_OperatorNodeHandler_000` IN ( "3 - CLEARED" )) AS `ELIDE_4`,
    (`CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_003`.`CELONIS__PQL2SQL_OperatorNodeHandler_001` IN ( "3 - CLEARED" )) AS `ELIDE_5`,
    `CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_003`.`ELIDE_3` AS `ELIDE_6`
  FROM
    `CELONIS__PQL2SQL_TableScanSequence_CLAIM_HDR_001` AS `CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_003`
),
`CELONIS__PQL2SQL_ParserContext_Table_CLAIM_HDR_000` AS (
  SELECT
    `CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_005`.`CELONIS__PQL2SQL_JoinColumnResolver_Column_CLAIM_ID_000` AS `CELONIS__PQL2SQL_JoinColumnResolver_Column_CLAIM_ID_000`,
    `CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_005`.`CELONIS__PQL2SQL_OperatorNodeHandler_001` AS `CELONIS__PQL2SQL_OperatorNodeHandler_001`,
    (`CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_005`.`ELIDE_6` AND `CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_005`.`ELIDE_4` AND `CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_005`.`ELIDE_5`) AS `ELIDE_10`
  FROM
    `CELONIS__PQL2SQL_TableScanSequence_CLAIM_HDR_002` AS `CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_005`
),
`CELONIS__PQL2SQL_ParserContext_Filter_000` AS (
  SELECT
    `CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_006`.`CELONIS__PQL2SQL_JoinColumnResolver_Column_CLAIM_ID_000` AS `CELONIS__PQL2SQL_JoinColumnResolver_Column_CLAIM_ID_000`,
    `CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_006`.`CELONIS__PQL2SQL_OperatorNodeHandler_001` AS `CELONIS__PQL2SQL_OperatorNodeHandler_001`
  FROM
    `CELONIS__PQL2SQL_ParserContext_Table_CLAIM_HDR_000` AS `CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_006`
  WHERE
    (`CELONIS__PQL2SQL_TableScan_Alias_CLAIM_HDR_006`.`ELIDE_10`)
),
`CELONIS__PQL2SQL_TableScanSequence_Aggregation_000` AS (
  SELECT
    CELONIS_SORTED_FIRST(
      `CELONIS__PQL2SQL_TableScan_Alias_Filter_000`.`CELONIS__PQL2SQL_OperatorNodeHandler_001`
      ORDER BY
        `CELONIS__PQL2SQL_TableScan_Alias_Filter_000`.`CELONIS__PQL2SQL_JoinColumnResolver_Column_CLAIM_ID_000` ASC) AS `CELONIS__PQL2SQL_AggregateComputationsHandler_AGG_000`
  FROM
    `CELONIS__PQL2SQL_ParserContext_Filter_000` AS `CELONIS__PQL2SQL_TableScan_Alias_Filter_000`
),
`CELONIS__PQL2SQL_FilterAndSortHandler_FilterAndSort_000` AS (
  SELECT
    `CELONIS__PQL2SQL_TableScan_Alias_Aggregation_001`.`CELONIS__PQL2SQL_AggregateComputationsHandler_AGG_000` AS `CELONIS__PQL2SQL_AggregateComputationsHandler_AGG_000`
  FROM
    `CELONIS__PQL2SQL_TableScanSequence_Aggregation_000` AS `CELONIS__PQL2SQL_TableScan_Alias_Aggregation_001`
  LIMIT
    50
),
`CELONIS__PQL2SQL_TableOutputHandler_MAIN_000` AS (
  SELECT
    `CELONIS__PQL2SQL_TableScan_Alias_FilterAndSort_000`.`CELONIS__PQL2SQL_AggregateComputationsHandler_AGG_000` AS `CELONIS__PQL2SQL_AggregateComputationsHandler_AGG_000`
  FROM
    `CELONIS__PQL2SQL_FilterAndSortHandler_FilterAndSort_000` AS `CELONIS__PQL2SQL_TableScan_Alias_FilterAndSort_000`
  LIMIT
    50
),
`CELONIS__PQL2SQL_ParserContext_UNION_000` AS (
  (
    SELECT
      `CELONIS__PQL2SQL_TableScan_Alias_MAIN_000`.`CELONIS__PQL2SQL_AggregateComputationsHandler_AGG_000` AS `CELONIS__PQL2SQL_ParserContext_OUTCOLUMN_000`,
      CAST(1 AS BIGINT) AS `CELONIS__PQL2SQL_ParserContext_TAG_000`
    FROM
      `CELONIS__PQL2SQL_TableOutputHandler_MAIN_000` AS `CELONIS__PQL2SQL_TableScan_Alias_MAIN_000`
  )
  UNION ALL
  (
    SELECT
      NULL AS `CELONIS__PQL2SQL_ParserContext_OUTCOLUMN_000`,
      CAST(2 AS BIGINT) AS `CELONIS__PQL2SQL_ParserContext_TAG_000`
    FROM
      `CELONIS__PQL2SQL_ParserContext_Constant_000` AS `CELONIS__PQL2SQL_TableScan_Alias_METADATA_000`
  )
)
SELECT
  `CELONIS__PQL2SQL_TableScan_Alias_UNION_000`.`CELONIS__PQL2SQL_ParserContext_OUTCOLUMN_000` AS `CELONIS__PQL2SQL_ParserContext_OUTCOLUMN_000`,
  `CELONIS__PQL2SQL_TableScan_Alias_UNION_000`.`CELONIS__PQL2SQL_ParserContext_TAG_000` AS `CELONIS__PQL2SQL_ParserContext_TAG_000`
FROM
  `CELONIS__PQL2SQL_ParserContext_UNION_000` AS `CELONIS__PQL2SQL_TableScan_Alias_UNION_000`